improved error handling in advanced_status script

diff --git a/src/bin/advanced_status b/src/bin/advanced_status
--- a/src/bin/advanced_status
+++ b/src/bin/advanced_status
@@ -2,29 +2,52 @@
 
 checkadvanced() {
   if ls /opt/zextras/lib/ext/carbonio/carbonio-advanced-*.jar >/dev/null 2>&1; then
-    echo "Carbonio Advanced installed... checking advanced modules status"
-    for ((i = 0; i < 10; i++)); do
-      check_running_advanced
-      if [ $advanced_is_running = 0 ]; then
-        break
-      fi
-      sleep $1
-    done
-    if [ $advanced_is_running = 0 ]; then
-      /opt/zextras/bin/carbonio --json core getAllServicesStatus | jq -r '.response | .[] | [.commercialName,.running] | join(" is ") | sub("true";"running") | sub("false";"NOT running")'
+    echo "Carbonio Advanced installed."
+    echo -n "Checking advanced modules status"
+    if [ $(exists_command carbonio) = "false" ]; then
+        echo "Failed to check advanced modules status. Carbonio CLI not found!"
     else
-      echo "Failed to check advanced modules status"
+      for ((i = 0; i < 10; i++)); do
+        echo -n "."
+        check_running_advanced
+        if [ $advanced_is_running = 0 ]; then
+          break
+        fi
+        sleep $1
+      done
+      echo ""
+      if [ $advanced_is_running = 0 ]; then
+        /opt/zextras/bin/carbonio --json core getAllServicesStatus | jq -r '.response | .[] | [.commercialName,.running] | join(" is ") | sub("true";"running") | sub("false";"NOT running")'
+        if [ $? != 0 ]; then
+          echo "Failed to check advanced modules status. Carbonio CLI not working!"
+        fi
+      else
+        echo "Failed to check advanced modules status. Carbonio Advanced is not running. Check logs for more information."
+      fi
     fi
   fi
 }
 
 check_running_advanced() {
   local output=$(carbonio core getVersion)
+  if [ $? != 0 ]; then
+      advanced_is_running=1
+  fi
   if [[ "$output" == *"Unable to communicate with server"* ]]; then
       advanced_is_running=1
   else
       advanced_is_running=0
   fi
+}
+
+exists_command() {
+    command -v "$1" >/dev/null 2>&1
+
+    if [[ $? -eq 0 ]]; then
+        echo "true"
+    else
+        echo "false"
+    fi
 }
 
 checkadvanced $1
