chore: format advanced_status

diff --git a/src/bin/advanced_status b/src/bin/advanced_status
--- a/src/bin/advanced_status
+++ b/src/bin/advanced_status
@@ -5,7 +5,7 @@ checkadvanced() {
     echo "Carbonio Advanced installed."
     echo -n "Checking advanced modules status"
     if [ $(exists_command carbonio) = "false" ]; then
-        echo "Failed to check advanced modules status. Carbonio CLI not found!"
+      echo "Failed to check advanced modules status. Carbonio CLI not found!"
     else
       for ((i = 0; i < 10; i++)); do
         echo -n "."
@@ -31,23 +31,23 @@ checkadvanced() {
 check_running_advanced() {
   local output=$(carbonio core getVersion)
   if [ $? != 0 ]; then
-      advanced_is_running=1
+    advanced_is_running=1
   fi
   if [[ "$output" == *"Unable to communicate with server"* ]]; then
-      advanced_is_running=1
+    advanced_is_running=1
   else
-      advanced_is_running=0
+    advanced_is_running=0
   fi
 }
 
 exists_command() {
-    command -v "$1" >/dev/null 2>&1
+  command -v "$1" >/dev/null 2>&1
 
-    if [[ $? -eq 0 ]]; then
-        echo "true"
-    else
-        echo "false"
-    fi
+  if [[ $? -eq 0 ]]; then
+    echo "true"
+  else
+    echo "false"
+  fi
 }
 
 checkadvanced $1
