chore: formatting and split echo content.

diff --git a/src/bin/advanced_status b/src/bin/advanced_status
--- a/src/bin/advanced_status
+++ b/src/bin/advanced_status
@@ -6,7 +6,7 @@ checkadvanced() {
   if ! ls /opt/zextras/lib/ext/carbonio/carbonio-advanced-*.jar >/dev/null 2>&1; then
     return 1
   fi
-  
+
   echo "Carbonio Advanced installed."
   echo -n "Checking advanced modules status"
 
@@ -19,9 +19,9 @@ checkadvanced() {
     echo -n "."
     if check_running_advanced; then
       echo
-      if ! /opt/zextras/bin/carbonio --json core getAllServicesStatus | 
-          jq -r '.response[] | "\(.commercialName) is \(if .running then "running" else "NOT running" end)"'; then
-        
+      if ! /opt/zextras/bin/carbonio --json core getAllServicesStatus |
+        jq -r '.response[] | "\(.commercialName) is \(if .running then "running" else "NOT running" end)"'; then
+
         echo "Failed to check advanced modules status. Carbonio CLI not working!"
         return 1
       fi
@@ -31,7 +31,8 @@ checkadvanced() {
   done
 
   echo
-  echo "Failed to check advanced modules status. Carbonio Advanced is not running. Check logs for more information."
+  echo "Failed to check advanced modules status. Carbonio Advanced is not running."
+  echo "Check logs for more information."
   return 1
 }
 
