refactor: simplify check (advanced is installed).

diff --git a/src/bin/advanced_status b/src/bin/advanced_status
--- a/src/bin/advanced_status
+++ b/src/bin/advanced_status
@@ -3,31 +3,34 @@
 checkadvanced() {
   local timeout="${1:-2}" # Default to 2
 
-  if ls /opt/zextras/lib/ext/carbonio/carbonio-advanced-*.jar >/dev/null 2>&1; then
-    echo "Carbonio Advanced installed."
-    echo -n "Checking advanced modules status"
-    if [ "$(exists_command carbonio)" = "false" ]; then
-      echo "Failed to check advanced modules status. Carbonio CLI not found!"
-    else
-      for ((i = 0; i < 10; i++)); do
-        echo -n "."
-        check_running_advanced
-        if [ $advanced_is_running = 0 ]; then
-          break
-        fi
-        sleep "$timeout"
-      done
-      echo ""
-      if [ "$advanced_is_running" = 0 ]; then
-        /opt/zextras/bin/carbonio --json core getAllServicesStatus |
-          jq -r '.response[] | "\(.commercialName) is \(if .running then "running" else "NOT running" end)"'
-        local rc=$?
-        if [ $rc != 0 ]; then
-          echo "Failed to check advanced modules status. Carbonio CLI not working!"
-        fi
-      else
-        echo "Failed to check advanced modules status. Carbonio Advanced is not running. Check logs for more information."
+  if ! ls /opt/zextras/lib/ext/carbonio/carbonio-advanced-*.jar >/dev/null 2>&1; then
+    return 1
+  fi
+  
+  echo "Carbonio Advanced installed."
+  echo -n "Checking advanced modules status"
+  
+  if [ "$(exists_command carbonio)" = "false" ]; then
+    echo "Failed to check advanced modules status. Carbonio CLI not found!"
+  else
+    for ((i = 0; i < 10; i++)); do
+      echo -n "."
+      check_running_advanced
+      if [ $advanced_is_running = 0 ]; then
+        break
       fi
+      sleep "$timeout"
+    done
+    echo ""
+    if [ "$advanced_is_running" = 0 ]; then
+      /opt/zextras/bin/carbonio --json core getAllServicesStatus |
+        jq -r '.response[] | "\(.commercialName) is \(if .running then "running" else "NOT running" end)"'
+      local rc=$?
+      if [ $rc != 0 ]; then
+        echo "Failed to check advanced modules status. Carbonio CLI not working!"
+      fi
+    else
+      echo "Failed to check advanced modules status. Carbonio Advanced is not running. Check logs for more information."
     fi
   fi
 }
