chore: remove internal ulimits for docker and general linting (#75)
* chore: remove internal ulimits for docker

* chore: apply shfmt indentations to all shell scripts

* chore: uniform user detection snippet

diff --git a/src/bin/zmamavisdctl b/src/bin/zmamavisdctl
--- a/src/bin/zmamavisdctl
+++ b/src/bin/zmamavisdctl
@@ -5,7 +5,7 @@
 #
 # SPDX-License-Identifier: GPL-2.0-only
 
-if [ x$(whoami) != xzextras ]; then
+if [ "$(whoami)" != zextras ]; then
   echo Error: must be run as zextras user
   exit 1
 fi
@@ -76,143 +76,143 @@ checkrunning-mc() {
 # Main
 #
 case "$1" in
-'start')
-  checkrunning-mc
-  echo -n "Starting amavisd-mc..."
-  if [ $MCRUNNING = 1 ]; then
-    echo "amavisd-mc is already running."
-  else
-    if [ $MCRUNNING = 0 ]; then
-      sudo /opt/zextras/common/sbin/amavis-mc
+  'start')
+    checkrunning-mc
+    echo -n "Starting amavisd-mc..."
+    if [ $MCRUNNING = 1 ]; then
+      echo "amavisd-mc is already running."
+    else
+      if [ $MCRUNNING = 0 ]; then
+        sudo /opt/zextras/common/sbin/amavis-mc
+        for ((i = 0; i < 30; i++)); do
+          checkrunning-mc
+          if [ $MCRUNNING = 1 ]; then
+            break
+          fi
+          sleep 1
+        done
+      fi
+      if [ "x$MCPID" = "x" ]; then
+        echo "failed."
+        exit
+      else
+        echo "done."
+      fi
+    fi
+    checkrunning
+    echo -n "Starting amavisd..."
+    if [ $RUNNING = 1 ]; then
+      echo "amavisd is already running."
+      exit 0
+    else
+      if [ ! -d /opt/zextras/data/amavisd/quarantine ]; then
+        mkdir /opt/zextras/data/amavisd/quarantine
+      fi
+      if [ ! -d /opt/zextras/data/amavisd/tmp ]; then
+        mkdir /opt/zextras/data/amavisd/tmp
+      else
+        find /opt/zextras/data/amavisd/tmp -maxdepth 1 -type d -name 'amavis-*' -exec rm -rf {} \; >/dev/null 2>&1
+      fi
+      if [ ! -d /opt/zextras/data/amavisd/var ]; then
+        mkdir /opt/zextras/data/amavisd/var
+      fi
+      if [ x$2 = "x" ]; then
+        rewriteconfig
+      fi
+      /opt/zextras/common/sbin/amavisd -X no_conf_file_writable_check -c \
+        /opt/zextras/conf/amavisd.conf &
       for ((i = 0; i < 30; i++)); do
-        checkrunning-mc
-        if [ $MCRUNNING = 1 ]; then
+        checkrunning
+        if [ $RUNNING = 1 ]; then
           break
         fi
         sleep 1
       done
-    fi
-    if [ "x$MCPID" = "x" ]; then
-      echo "failed."
-      exit
-    else
-      echo "done."
-    fi
-  fi
-  checkrunning
-  echo -n "Starting amavisd..."
-  if [ $RUNNING = 1 ]; then
-    echo "amavisd is already running."
-    exit 0
-  else
-    if [ ! -d /opt/zextras/data/amavisd/quarantine ]; then
-      mkdir /opt/zextras/data/amavisd/quarantine
-    fi
-    if [ ! -d /opt/zextras/data/amavisd/tmp ]; then
-      mkdir /opt/zextras/data/amavisd/tmp
-    else
-      find /opt/zextras/data/amavisd/tmp -maxdepth 1 -type d -name 'amavis-*' -exec rm -rf {} \; >/dev/null 2>&1
-    fi
-    if [ ! -d /opt/zextras/data/amavisd/var ]; then
-      mkdir /opt/zextras/data/amavisd/var
-    fi
-    if [ x$2 = "x" ]; then
-      rewriteconfig
-    fi
-    /opt/zextras/common/sbin/amavisd -X no_conf_file_writable_check -c \
-      /opt/zextras/conf/amavisd.conf &
-    for ((i = 0; i < 30; i++)); do
-      checkrunning
-      if [ $RUNNING = 1 ]; then
-        break
+      if [ "x$PID" = "x" ]; then
+        echo "failed."
+      else
+        echo "done."
       fi
-      sleep 1
-    done
-    if [ "x$PID" = "x" ]; then
-      echo "failed."
-    else
-      echo "done."
     fi
-  fi
-  ;;
+    ;;
 
-'kill')
-  $0 stop
-  ;;
+  'kill')
+    $0 stop
+    ;;
 
-'stop')
-  checkrunning
-  echo -n "Stopping amavisd..."
-  if [ $RUNNING = 0 ]; then
-    echo "amavisd is not running."
-  else
-    kill $PID 2>/dev/null
-    for ((i = 0; i < 300; i++)); do
-      sleep 5
-      kill -0 $PID 2>/dev/null
+  'stop')
+    checkrunning
+    echo -n "Stopping amavisd..."
+    if [ $RUNNING = 0 ]; then
+      echo "amavisd is not running."
+    else
+      kill $PID 2>/dev/null
+      for ((i = 0; i < 300; i++)); do
+        sleep 5
+        kill -0 $PID 2>/dev/null
+        if [ $? != 0 ]; then
+          break
+        fi
+      done
+      kill $PID 2>/dev/null
       if [ $? != 0 ]; then
-        break
+        echo " done."
+      else
+        echo " failed to stop $PID"
+        exit 1
       fi
-    done
-    kill $PID 2>/dev/null
-    if [ $? != 0 ]; then
-      echo " done."
-    else
-      echo " failed to stop $PID"
-      exit 1
     fi
-  fi
-  checkrunning-mc
-  echo -n "Stopping amavisd-mc..."
-  if [ $MCRUNNING = 0 ]; then
-    echo "amavisd-mc is not running."
-  else
-    kill $MCPID 2>/dev/null
-    for ((i = 0; i < 300; i++)); do
-      sleep 5
-      kill -0 $MCPID 2>/dev/null
+    checkrunning-mc
+    echo -n "Stopping amavisd-mc..."
+    if [ $MCRUNNING = 0 ]; then
+      echo "amavisd-mc is not running."
+    else
+      kill $MCPID 2>/dev/null
+      for ((i = 0; i < 300; i++)); do
+        sleep 5
+        kill -0 $MCPID 2>/dev/null
+        if [ $? != 0 ]; then
+          break
+        fi
+      done
+      kill $MCPID 2>/dev/null
       if [ $? != 0 ]; then
-        break
+        echo " done."
+      else
+        echo " failed to stop $PID"
+        exit 1
       fi
-    done
-    kill $MCPID 2>/dev/null
-    if [ $? != 0 ]; then
-      echo " done."
-    else
-      echo " failed to stop $PID"
-      exit 1
     fi
-  fi
-  exit 0
-  ;;
-
-'restart' | 'reload')
-  $0 stop
-  $0 start $2
-  ;;
-
-'status')
-  checkrunning
-  echo -n "amavisd is "
-  if [ $RUNNING = 0 ]; then
-    echo "not running."
-    exit 1
-  else
-    echo "running."
-  fi
-  checkrunning-mc
-  echo -n "amavisd-mc is "
-  if [ $MCRUNNING = 0 ]; then
-    echo "not running."
-    exit 1
-  else
-    echo "running."
     exit 0
-  fi
-  ;;
+    ;;
 
-*)
-  echo "Usage: $0 start|stop|kill|reload|restart|status"
-  exit 1
-  ;;
+  'restart' | 'reload')
+    $0 stop
+    $0 start $2
+    ;;
+
+  'status')
+    checkrunning
+    echo -n "amavisd is "
+    if [ $RUNNING = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+    fi
+    checkrunning-mc
+    echo -n "amavisd-mc is "
+    if [ $MCRUNNING = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+      exit 0
+    fi
+    ;;
+
+  *)
+    echo "Usage: $0 start|stop|kill|reload|restart|status"
+    exit 1
+    ;;
 esac
diff --git a/src/bin/zmcbpolicydctl b/src/bin/zmcbpolicydctl
--- a/src/bin/zmcbpolicydctl
+++ b/src/bin/zmcbpolicydctl
@@ -5,7 +5,7 @@
 #
 # SPDX-License-Identifier: GPL-2.0-only
 
-if [ x$(whoami) != xzextras ]; then
+if [ "$(whoami)" != zextras ]; then
   echo Error: must be run as zextras user
   exit 1
 fi
@@ -48,98 +48,98 @@ checkrunning() {
 # Main
 #
 case "$1" in
-'start')
-  if [ ! -x /opt/zextras/common/bin/cbpolicyd ]; then
-    echo "cbpolicyd not installed, skipping."
-    exit 0
-  fi
-  checkrunning
-
-  echo -n "Starting policyd..."
-  if [ $RUNNING = 1 ]; then
-    echo "policyd is already running."
-    exit 0
-  else
-    if [ ! -d /opt/zextras/data/cbpolicyd/db ]; then
-      mkdir /opt/zextras/data/cbpolicyd/db
+  'start')
+    if [ ! -x /opt/zextras/common/bin/cbpolicyd ]; then
+      echo "cbpolicyd not installed, skipping."
+      exit 0
     fi
-    if [ ! -f ${dbfile} ]; then
-      /opt/zextras/libexec/zmcbpolicydinit
-      if [ $? != 0 ]; then
-        echo "Unable to initialize cbpolicyd database."
+    checkrunning
+
+    echo -n "Starting policyd..."
+    if [ $RUNNING = 1 ]; then
+      echo "policyd is already running."
+      exit 0
+    else
+      if [ ! -d /opt/zextras/data/cbpolicyd/db ]; then
+        mkdir /opt/zextras/data/cbpolicyd/db
+      fi
+      if [ ! -f ${dbfile} ]; then
+        /opt/zextras/libexec/zmcbpolicydinit
+        if [ $? != 0 ]; then
+          echo "Unable to initialize cbpolicyd database."
+          exit 1
+        fi
+      fi
+      if [ x$2 = "x" ]; then
+        rewriteconfig
+      fi
+      /opt/zextras/common/bin/cbpolicyd --config /opt/zextras/conf/cbpolicyd.conf 2>/dev/null
+      for ((i = 0; i < 30; i++)); do
+        sleep 1
+        checkrunning
+        if [ $RUNNING = 1 ]; then
+          break
+        fi
+      done
+      if [ "x$PID" = "x" ]; then
+        echo "failed."
         exit 1
+      else
+        echo "done."
       fi
     fi
-    if [ x$2 = "x" ]; then
-      rewriteconfig
-    fi
-    /opt/zextras/common/bin/cbpolicyd --config /opt/zextras/conf/cbpolicyd.conf 2>/dev/null
-    for ((i = 0; i < 30; i++)); do
-      sleep 1
-      checkrunning
-      if [ $RUNNING = 1 ]; then
-        break
-      fi
-    done
-    if [ "x$PID" = "x" ]; then
-      echo "failed."
-      exit 1
+    ;;
+
+  'kill')
+    $0 stop
+    ;;
+
+  'stop')
+    checkrunning
+    echo -n "Stopping policyd..."
+    if [ $RUNNING = 0 ]; then
+      echo "policyd is not running."
+      exit 0
     else
-      echo "done."
-    fi
-  fi
-  ;;
-
-'kill')
-  $0 stop
-  ;;
-
-'stop')
-  checkrunning
-  echo -n "Stopping policyd..."
-  if [ $RUNNING = 0 ]; then
-    echo "policyd is not running."
-    exit 0
-  else
-    kill $PID 2>/dev/null
-    for ((i = 0; i < 300; i++)); do
-      sleep 5
-      kill -0 $PID 2>/dev/null
-      if [ $? != 0 ]; then
+      kill $PID 2>/dev/null
+      for ((i = 0; i < 300; i++)); do
+        sleep 5
+        kill -0 $PID 2>/dev/null
+        if [ $? != 0 ]; then
+          echo " done."
+          exit 0
+        fi
+      done
+      kill $PID 2>/dev/null
+      if [ $? = 0 ]; then
+        echo " failed to stop $PID"
+        exit 1
+      else
         echo " done."
-        exit 0
       fi
-    done
-    kill $PID 2>/dev/null
-    if [ $? = 0 ]; then
-      echo " failed to stop $PID"
+    fi
+    exit 0
+    ;;
+
+  'restart' | 'reload')
+    $0 stop
+    $0 start $2
+    ;;
+
+  'status')
+    checkrunning
+    echo -n "policyd is "
+    if [ $RUNNING = 0 ]; then
+      echo "not running."
       exit 1
     else
-      echo " done."
+      echo "running."
+      exit 0
     fi
-  fi
-  exit 0
-  ;;
+    ;;
 
-'restart' | 'reload')
-  $0 stop
-  $0 start $2
-  ;;
-
-'status')
-  checkrunning
-  echo -n "policyd is "
-  if [ $RUNNING = 0 ]; then
-    echo "not running."
+  *)
+    echo "Usage: $0 start|stop|kill|reload|restart|status"
     exit 1
-  else
-    echo "running."
-    exit 0
-  fi
-  ;;
-
-*)
-  echo "Usage: $0 start|stop|kill|reload|restart|status"
-  exit 1
-  ;;
+    ;;
 esac
diff --git a/src/bin/zmclamdctl b/src/bin/zmclamdctl
--- a/src/bin/zmclamdctl
+++ b/src/bin/zmclamdctl
@@ -5,7 +5,7 @@
 #
 # SPDX-License-Identifier: GPL-2.0-only
 
-if [ x$(whoami) != xzextras ]; then
+if [ "$(whoami)" != zextras ]; then
   echo Error: must be run as zextras user
   exit 1
 fi
@@ -63,90 +63,90 @@ pskillall() {
 # Main
 #
 case "$1" in
-'start')
-  if [ x$2 = "x" ]; then
-    rewriteconfig
-  fi
-
-  checkrunning
-  echo -n "Starting clamd..."
-  if [ $running = 1 ]; then
-    echo "clamd is already running."
-  else
-    /opt/zextras/common/sbin/clamd \
-      --config-file=/opt/zextras/conf/clamd.conf \
-      >>${zimbra_log_directory}/clamd.log 2>&1 &
-
-    for ((i = 0; i < 12; i++)); do
-      checkrunning
-      if [ $running = 1 ]; then
-        echo "done."
-        exit 0
-      fi
-      sleep 5
-    done
-    echo "failed."
-    exit 1
-  fi
-  exit 0
-  ;;
-
-'kill')
-  if [ -f /opt/zextras/log/clamd.pid ]; then
-    cpid=$(cat /opt/zextras/log/clamd.pid)
-    kill "$cpid" 2>/dev/null
-  fi
-  pskillall /opt/zextras/common/sbin/clamd
-  exit 0
-  ;;
-
-'stop')
-  checkrunning
-  echo -n "Stopping clamd..."
-  if [ $running = 0 ]; then
-    echo "clamd is not running."
-  else
-    if [ x"$cpid" != "x" ]; then
-      kill "$cpid" 2>/dev/null
+  'start')
+    if [ x$2 = "x" ]; then
+      rewriteconfig
     fi
-    for ((i = 0; i < 30; i++)); do
-      sleep 2
-      kill -0 $cpid 2>/dev/null
-      if [ $? != 0 ]; then
-        rm -f ${pidfile}
-        break
-      fi
-      kill $cpid
-    done
-    if [ -s ${pidfile} ]; then
+
+    checkrunning
+    echo -n "Starting clamd..."
+    if [ $running = 1 ]; then
+      echo "clamd is already running."
+    else
+      /opt/zextras/common/sbin/clamd \
+        --config-file=/opt/zextras/conf/clamd.conf \
+        >>${zimbra_log_directory}/clamd.log 2>&1 &
+
+      for ((i = 0; i < 12; i++)); do
+        checkrunning
+        if [ $running = 1 ]; then
+          echo "done."
+          exit 0
+        fi
+        sleep 5
+      done
       echo "failed."
       exit 1
-    else
-      echo "done."
     fi
-  fi
-  exit 0
-  ;;
-
-'restart' | 'reload')
-  $0 stop
-  $0 start $2
-  ;;
-
-'status')
-  checkrunning
-  echo -n "clamd is "
-  if [ $running = 1 ]; then
-    echo "running."
     exit 0
-  else
-    echo "not runnning."
-    exit 1
-  fi
-  ;;
+    ;;
 
-*)
-  echo "Usage: $0 start|stop|kill|restart|status"
-  exit 1
-  ;;
+  'kill')
+    if [ -f /opt/zextras/log/clamd.pid ]; then
+      cpid=$(cat /opt/zextras/log/clamd.pid)
+      kill "$cpid" 2>/dev/null
+    fi
+    pskillall /opt/zextras/common/sbin/clamd
+    exit 0
+    ;;
+
+  'stop')
+    checkrunning
+    echo -n "Stopping clamd..."
+    if [ $running = 0 ]; then
+      echo "clamd is not running."
+    else
+      if [ x"$cpid" != "x" ]; then
+        kill "$cpid" 2>/dev/null
+      fi
+      for ((i = 0; i < 30; i++)); do
+        sleep 2
+        kill -0 $cpid 2>/dev/null
+        if [ $? != 0 ]; then
+          rm -f ${pidfile}
+          break
+        fi
+        kill $cpid
+      done
+      if [ -s ${pidfile} ]; then
+        echo "failed."
+        exit 1
+      else
+        echo "done."
+      fi
+    fi
+    exit 0
+    ;;
+
+  'restart' | 'reload')
+    $0 stop
+    $0 start $2
+    ;;
+
+  'status')
+    checkrunning
+    echo -n "clamd is "
+    if [ $running = 1 ]; then
+      echo "running."
+      exit 0
+    else
+      echo "not runnning."
+      exit 1
+    fi
+    ;;
+
+  *)
+    echo "Usage: $0 start|stop|kill|restart|status"
+    exit 1
+    ;;
 esac
diff --git a/src/bin/zmmailboxdctl b/src/bin/zmmailboxdctl
--- a/src/bin/zmmailboxdctl
+++ b/src/bin/zmmailboxdctl
@@ -43,100 +43,99 @@ fi
 # Main
 #
 case "$1" in
-'start')
-  if [ "x$2" = "x" ]; then
-    /opt/zextras/bin/zmtlsctl >/dev/null 2>&1
-  fi
-  /opt/zextras/libexec/zmmailboxdmgr status
-  if [ $? = 0 ]; then
-    echo "mailboxd already running."
-    exit 0
-  fi
-
-  mkdir -p ${mailboxd_directory}/work/service/jsp
-
-  mailboxd_thread_stack_size=${mailboxd_thread_stack_size:=256k}
-  if [ -z "$(echo ${mailboxd_java_options} | grep Xss)" ]; then
-    mailboxd_java_options="${mailboxd_java_options} -Xss${mailboxd_thread_stack_size}"
-  fi
-
-  networkaddress_cache_ttl=${networkaddress_cache_ttl:=60}
-  if [ -z "$(echo ${mailboxd_java_options} | grep sun.net.inetaddr.ttl)" ]; then
-    mailboxd_java_options="${mailboxd_java_options} -Dsun.net.inetaddr.ttl=${networkaddress_cache_ttl}"
-  fi
-
-  if [ -z "$(echo ${mailboxd_java_options} | grep log4j)" ]; then
-      mailboxd_java_options="${mailboxd_java_options} -Dlog4j.configurationFile=${zimbra_log4j_properties}"
-  fi
-  echo -n "Starting mailboxd..."
-  /opt/zextras/libexec/zmmailboxdmgr start \
-    -Dfile.encoding=UTF-8 ${mailboxd_java_options} ${spnegoJavaOptions} -Xms${javaXms}m \
-    -Xmx${javaXmx}m </dev/null >/dev/null 2>&1
-  status=$?
-  if [ $status != 0 ]; then
-    echo "failed."
-    exit $status
-  fi
-  status=1
-  MPORT=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMailPort | grep zimbraMailPort: | awk '{print $2}')
-  ncOpt="-z"
-  for ((i = 0; i < 12; i++)); do
-    $NC $ncOpt localhost ${MPORT} >/dev/null 2>&1
-    if [ $? = 0 ]; then
-      status=0
-      break
+  'start')
+    if [ "x$2" = "x" ]; then
+      /opt/zextras/bin/zmtlsctl >/dev/null 2>&1
     fi
-    sleep 5
-  done
-  if [ $status = 0 ]; then
-    echo "done."
-  else
-    echo "failed."
-  fi
-  exit $status
-  ;;
+    /opt/zextras/libexec/zmmailboxdmgr status
+    if [ $? = 0 ]; then
+      echo "mailboxd already running."
+      exit 0
+    fi
 
-'kill' | 'stop')
-  echo -n "Stopping mailboxd..."
-  /opt/zextras/libexec/zmmailboxdmgr status
-  if [ $? != 0 ]; then
-    echo "mailboxd is not running."
+    mkdir -p ${mailboxd_directory}/work/service/jsp
+
+    mailboxd_thread_stack_size=${mailboxd_thread_stack_size:=256k}
+    if [ -z "$(echo ${mailboxd_java_options} | grep Xss)" ]; then
+      mailboxd_java_options="${mailboxd_java_options} -Xss${mailboxd_thread_stack_size}"
+    fi
+
+    networkaddress_cache_ttl=${networkaddress_cache_ttl:=60}
+    if [ -z "$(echo ${mailboxd_java_options} | grep sun.net.inetaddr.ttl)" ]; then
+      mailboxd_java_options="${mailboxd_java_options} -Dsun.net.inetaddr.ttl=${networkaddress_cache_ttl}"
+    fi
+
+    if [ -z "$(echo ${mailboxd_java_options} | grep log4j)" ]; then
+      mailboxd_java_options="${mailboxd_java_options} -Dlog4j.configurationFile=${zimbra_log4j_properties}"
+    fi
+    echo -n "Starting mailboxd..."
+    /opt/zextras/libexec/zmmailboxdmgr start \
+      -Dfile.encoding=UTF-8 ${mailboxd_java_options} ${spnegoJavaOptions} -Xms${javaXms}m \
+      -Xmx${javaXmx}m </dev/null >/dev/null 2>&1
+    status=$?
+    if [ $status != 0 ]; then
+      echo "failed."
+      exit $status
+    fi
+    status=1
+    MPORT=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMailPort | grep zimbraMailPort: | awk '{print $2}')
+    ncOpt="-z"
+    for ((i = 0; i < 12; i++)); do
+      $NC $ncOpt localhost ${MPORT} >/dev/null 2>&1
+      if [ $? = 0 ]; then
+        status=0
+        break
+      fi
+      sleep 5
+    done
+    if [ $status = 0 ]; then
+      echo "done."
+    else
+      echo "failed."
+    fi
+    exit $status
+    ;;
+
+  'kill' | 'stop')
+    echo -n "Stopping mailboxd..."
+    /opt/zextras/libexec/zmmailboxdmgr status
+    if [ $? != 0 ]; then
+      echo "mailboxd is not running."
+      exit 0
+    fi
+    /opt/zextras/bin/zmthrdump -i -o /opt/zextras/log/stacktrace.$$.$(date +%Y%m%d%H%M%S) 2>/dev/null
+    /opt/zextras/libexec/zmmailboxdmgr stop
+    if [ $? = 0 ]; then
+      echo "done."
+    else
+      echo "failed."
+    fi
     exit 0
-  fi
-  /opt/zextras/bin/zmthrdump -i -o /opt/zextras/log/stacktrace.$$.$(date +%Y%m%d%H%M%S) 2>/dev/null
-  /opt/zextras/libexec/zmmailboxdmgr stop
-  if [ $? = 0 ]; then
-    echo "done."
-  else
-    echo "failed."
-  fi
-  exit 0
-  ;;
+    ;;
 
-\
   'restart' | 'reload')
-  $0 stop
-  $0 start $2
-  ;;
+    $0 stop
+    $0 start $2
+    ;;
 
-'status')
-  echo -n "mailboxd is "
-  /opt/zextras/libexec/zmmailboxdmgr status
-  if [ $? = 0 ]; then
-    echo "running."
-    exit 0
-  else
-    echo "not running."
+  'status')
+    echo -n "mailboxd is "
+    /opt/zextras/libexec/zmmailboxdmgr status
+    if [ $? = 0 ]; then
+      echo "running."
+      exit 0
+    else
+      echo "not running."
+      exit 1
+    fi
+    ;;
+
+  'update')
+    mk_download_dir
+    ;;
+
+  *)
+    echo "Usage: $0 start|stop|kill|restart|reload|status|update"
     exit 1
-  fi
-  ;;
-
-'update')
-  mk_download_dir
-  ;;
-
-*)
-  echo "Usage: $0 start|stop|kill|restart|reload|status|update"
-  exit 1
-  ;;
+    ;;
 esac
diff --git a/src/bin/zmmilterctl b/src/bin/zmmilterctl
--- a/src/bin/zmmilterctl
+++ b/src/bin/zmmilterctl
@@ -16,8 +16,8 @@ pid=""
 java="/opt/zextras/bin/zmjava"
 
 case "$(uname)" in
-CYGWIN*) PATHSEP=";" ;;
-*) PATHSEP=":" ;;
+  CYGWIN*) PATHSEP=";" ;;
+  *) PATHSEP=":" ;;
 esac
 
 java_version=$(${java} -version 2>&1 | grep "java version" | sed -e 's/"//g' | awk '{print $NF}' | awk -F_ '{print $1}')
@@ -61,81 +61,81 @@ refresh() {
 }
 
 case "$1" in
-start)
-  checkrunning
-  echo -n "Starting milter server..."
-  if [ $running = 1 ]; then
-    echo "milter server is already running."
-    exit 0
-  fi
+  start)
+    checkrunning
+    echo -n "Starting milter server..."
+    if [ $running = 1 ]; then
+      echo "milter server is already running."
+      exit 0
+    fi
 
-  nohup sh -c "exec ${runcmd} 2>&1" >/opt/zextras/log/milter.out 2>&1 &
+    nohup sh -c "exec ${runcmd} 2>&1" >/opt/zextras/log/milter.out 2>&1 &
 
-  pid=$!
-  if [ "x$pid" != 'x' ]; then
-    echo $pid >$pidfile
-  else
-    echo "failed."
-    exit 1
-  fi
-  checkrunning
-  if [ $running = 1 ]; then
-    echo "done."
+    pid=$!
+    if [ "x$pid" != 'x' ]; then
+      echo $pid >$pidfile
+    else
+      echo "failed."
+      exit 1
+    fi
+    checkrunning
+    if [ $running = 1 ]; then
+      echo "done."
+      exit 0
+    else
+      echo "failed."
+      exit 1
+    fi
+    ;;
+  stop)
+    checkrunning
+    echo -n "Stopping milter server..."
+    if [ $running = 0 ]; then
+      echo "milter server is not running."
+      exit 0
+    else
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2>/dev/null
+        if [ $? != 0 ]; then
+          rm -rf ${pidfile}
+          break
+        fi
+        kill $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      echo "failed."
+      exit 1
+    else
+      echo "done."
+    fi
     exit 0
-  else
-    echo "failed."
+    ;;
+  restart)
+    $0 stop
+    $0 start
+    ;;
+  reload)
+    $0 stop
+    $0 start
+    ;;
+  refresh)
+    refresh
+    ;;
+  status)
+    echo -n "Milter server is "
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+      exit 0
+    fi
+    ;;
+  *)
+    echo "$0 start|stop|restart|reload|refresh|status"
     exit 1
-  fi
-  ;;
-stop)
-  checkrunning
-  echo -n "Stopping milter server..."
-  if [ $running = 0 ]; then
-    echo "milter server is not running."
-    exit 0
-  else
-    for ((i = 0; i < 30; i++)); do
-      kill -0 $pid 2>/dev/null
-      if [ $? != 0 ]; then
-        rm -rf ${pidfile}
-        break
-      fi
-      kill $pid
-      sleep 1
-    done
-  fi
-  if [ -s ${pidfile} ]; then
-    echo "failed."
-    exit 1
-  else
-    echo "done."
-  fi
-  exit 0
-  ;;
-restart)
-  $0 stop
-  $0 start
-  ;;
-reload)
-  $0 stop
-  $0 start
-  ;;
-refresh)
-  refresh
-  ;;
-status)
-  echo -n "Milter server is "
-  checkrunning
-  if [ $running = 0 ]; then
-    echo "not running."
-    exit 1
-  else
-    echo "running."
-    exit 0
-  fi
-  ;;
-*)
-  echo "$0 start|stop|restart|reload|refresh|status"
-  exit 1
-  ;;
+    ;;
 esac
diff --git a/src/bin/zmskindeploy b/src/bin/zmskindeploy
--- a/src/bin/zmskindeploy
+++ b/src/bin/zmskindeploy
@@ -28,25 +28,25 @@ usage() {
 SKIN_SRC=""
 while [ $# -gt 0 ]; do
   case $1 in
-  -h | --help)
-    usage
-    exit
-    ;;
-  -*)
-    echo "ERROR: Unknown option $1"
-    usage
-    exit -1
-    ;;
-  *)
-    if [ "${SKIN_SRC}x" != "x" ]; then
-      echo "ERROR: Invalid number arguments" >&2
+    -h | --help)
+      usage
+      exit
+      ;;
+    -*)
+      echo "ERROR: Unknown option $1"
       usage
       exit -1
-    else
-      SKIN_SRC=$1
-    fi
-    shift
-    ;;
+      ;;
+    *)
+      if [ "${SKIN_SRC}x" != "x" ]; then
+        echo "ERROR: Invalid number arguments" >&2
+        usage
+        exit -1
+      else
+        SKIN_SRC=$1
+      fi
+      shift
+      ;;
   esac
 done
 
