chore: enhance start/stop of ctls scripts

diff --git a/src/bin/zmamavisdctl b/src/bin/zmamavisdctl
--- a/src/bin/zmamavisdctl
+++ b/src/bin/zmamavisdctl
@@ -84,7 +84,7 @@ case "$1" in
     else
       if [ $mcrunning = 0 ]; then
         sudo /opt/zextras/common/sbin/amavis-mc
-        for ((i = 0; i < 30; i++)); do
+        for ((i = 0; i < 10; i++)); do
           checkrunning-mc
           if [ $mcrunning = 1 ]; then
             break
@@ -121,7 +121,7 @@ case "$1" in
       fi
       /opt/zextras/common/sbin/amavisd -X no_conf_file_writable_check -c \
         /opt/zextras/conf/amavisd.conf &
-      for ((i = 0; i < 30; i++)); do
+      for ((i = 0; i < 10; i++)); do
         checkrunning
         if [ $running = 1 ]; then
           break
@@ -136,55 +136,48 @@ case "$1" in
     fi
     ;;
 
-  'kill')
-    $0 stop
-    ;;
-
-  'stop')
+  'kill' | 'stop')
     checkrunning
     echo -n "Stopping amavisd..."
     if [ $running = 0 ]; then
       echo "amavisd is not running."
     else
       kill "$pid" 2>/dev/null
-      for ((i = 0; i < 300; i++)); do
-        sleep 5
-        kill -0 "$pid" 2>/dev/null
-        rc=$?
-        if [ $rc -ne 0 ]; then
+      rc=$?
+      for ((i = 0; i < 10; i++)); do
+        checkrunning
+        if [ $running = 0 ]; then
           break
         fi
+        sleep 1
       done
-      kill "$pid" 2>/dev/null
-      rc=$?
-      if [ $rc -ne 0 ]; then
-        echo " done."
-      else
-        echo " failed to stop $pid"
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
         exit 1
+      else
+        echo "done."
       fi
     fi
+
     checkrunning-mc
     echo -n "Stopping amavisd-mc..."
     if [ $mcrunning = 0 ]; then
       echo "amavisd-mc is not running."
     else
       kill "$mcpid" 2>/dev/null
-      for ((i = 0; i < 300; i++)); do
-        sleep 5
-        kill -0 "$mcpid" 2>/dev/null
-        rc=$?
-        if [ $rc -ne 0 ]; then
+      rc=$?
+      for ((i = 0; i < 10; i++)); do
+        checkrunning-mc
+        if [ $mcrunning = 0 ]; then
           break
         fi
+        sleep 1
       done
-      kill "$mcpid" 2>/dev/null
-      rc=$?
-      if [ $rc -ne 0 ]; then
-        echo " done."
-      else
-        echo " failed to stop $pid"
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
         exit 1
+      else
+        echo "done."
       fi
     fi
     exit 0
diff --git a/src/bin/zmconfigdctl b/src/bin/zmconfigdctl
--- a/src/bin/zmconfigdctl
+++ b/src/bin/zmconfigdctl
@@ -107,18 +107,23 @@ case "$1" in
       echo "zmconfigd is not running."
       exit 0
     else
-      kill "${pid}" 2>/dev/null
+      kill "$pid" 2>/dev/null
+      rc=$?
       for ((i = 0; i < 10; i++)); do
-        if ! kill -0 "${pid}" 2>/dev/null; then
-          echo "done."
-          exit 0
+        checkrunning
+        if [ $running = 0 ]; then
+          break
         fi
-        sleep 3
+        sleep 1
       done
-      kill -9 "${pid}" 2>/dev/null
-      echo "failed to stop gracefully, process killed."
-      exit 1
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
+        exit 1
+      else
+        echo "done."
+      fi
     fi
+    exit 0
     ;;
 
   'restart' | 'reload')
diff --git a/src/bin/zmmailboxdctl b/src/bin/zmmailboxdctl
--- a/src/bin/zmmailboxdctl
+++ b/src/bin/zmmailboxdctl
@@ -115,14 +115,21 @@ case "$1" in
       echo "${servicename} is not running."
       exit 0
     else
-      /opt/zextras/bin/zmthrdump -i -o /opt/zextras/log/stacktrace.$$."$(date +%Y%m%d%H%M%S)" 2>/dev/null
       kill "$pid" 2>/dev/null
       rc=$?
-    fi
-    if [ $rc -eq 0 ]; then
-      echo "done."
-    else
-      echo "failed."
+      for ((i = 0; i < 10; i++)); do
+        checkrunning
+        if [ $running = 0 ]; then
+          break
+        fi
+        sleep 1
+      done
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
+        exit 1
+      else
+        echo "done."
+      fi
     fi
     exit 0
     ;;
diff --git a/src/bin/zmmemcachedctl b/src/bin/zmmemcachedctl
--- a/src/bin/zmmemcachedctl
+++ b/src/bin/zmmemcachedctl
@@ -51,7 +51,7 @@ case "$1" in
     else
       /opt/zextras/common/bin/memcached -d -U 0 -l "${addr}" -p "${port:-11211}"
     fi
-    for ((i = 0; i < 30; i++)); do
+    for ((i = 0; i < 10; i++)); do
       checkrunning
       if [ $running = 1 ]; then
         break
@@ -73,21 +73,21 @@ case "$1" in
       echo "memcached is not running."
       exit 0
     else
-      for ((i = 0; i < 30; i++)); do
-        kill -0 "$pid" 2>/dev/null
-        rc=$?
-        if [ $rc -ne 0 ]; then
+      kill "$pid" 2>/dev/null
+      rc=$?
+      for ((i = 0; i < 10; i++)); do
+        checkrunning
+        if [ $running = 0 ]; then
           break
         fi
-        kill "$pid" 2>/dev/null
+        sleep 1
       done
-    fi
-    rc=$?
-    if [ $rc -ne 0 ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
+        exit 1
+      else
+        echo "done."
+      fi
     fi
     exit 0
     ;;
diff --git a/src/bin/zmsaslauthdctl b/src/bin/zmsaslauthdctl
--- a/src/bin/zmsaslauthdctl
+++ b/src/bin/zmsaslauthdctl
@@ -45,39 +45,44 @@ case "$1" in
       rewriteconfig
     fi
     /opt/zextras/common/sbin/saslauthd -r -a zimbra
-    for ((i = 0; i < 30; i++)); do
+    for ((i = 0; i < 10; i++)); do
       checkrunning
       if [ $running = 1 ]; then
-        echo "done."
-        exit 0
+        break
       fi
       sleep 1
     done
-    echo "failed."
-    exit 1
+    if [ "$pid" != "" ]; then
+      echo "done."
+      exit 0
+    else
+      echo "failed."
+      exit 1
+    fi
     ;;
 
   'kill' | 'stop')
     checkrunning
+    echo -n "Stopping saslauthd..."
     if [ $running = 0 ]; then
       echo "saslauthd is not running."
       exit 0
     else
-      echo -n "Stopping saslauthd..."
-      for ((i = 0; i < 30; i++)); do
-        echo "$pid" | xargs kill 2>/dev/null
-        rc=$?
-        if [ $rc -eq 0 ]; then
+      echo "$pid" | xargs kill 2>/dev/null
+      rc=$?
+      for ((i = 0; i < 10; i++)); do
+        checkrunning
+        if [ $running = 0 ]; then
           break
         fi
         sleep 1
       done
-    fi
-    checkrunning
-    if [[ "${pid}" != "" ]]; then
-      exit 1
-    else
-      echo "done."
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
+        exit 1
+      else
+        echo "done."
+      fi
     fi
     exit 0
     ;;
