feat: carbonio release

diff --git a/src/bin/zmauditswatchctl b/src/bin/zmauditswatchctl
--- a/src/bin/zmauditswatchctl
+++ b/src/bin/zmauditswatchctl
@@ -1,30 +1,19 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2008, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-configfile=/opt/zimbra/conf/auditswatchrc
+configfile=/opt/zextras/conf/auditswatchrc
 pidfile=${zimbra_log_directory}/auditswatch.pid
 logfile=${zimbra_log_directory}/zmauditswatch.out
 pid=""
@@ -34,21 +23,18 @@ zimbra_swatch_ipacct_threshold=${zimbra_swatch_ipacct_threshold:=10}
 zimbra_swatch_total_threshold=${zimbra_swatch_total_threshold:=100}
 zimbra_swatch_threshold_seconds=${zimbra_swatch_threshold_seconds:=60}
 
-
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
   else
-    kill -0 $pid 2> /dev/null
+    kill -0 $pid 2>/dev/null
     if [ $? != 0 ]; then
       pid=""
       running=0
@@ -58,127 +44,127 @@ checkrunning()
   fi
 }
 
-case "$1" in 
-  start)
-    if [ ! -f ${configfile} ]; then
-      echo "${configfile} is missing."
-    fi
+case "$1" in
+start)
+  if [ ! -f ${configfile} ]; then
+    echo "${configfile} is missing."
+  fi
 
-    checkrunning
-    echo -n "Starting auditswatch..."
-    if [ $running = 1 ]; then
-      echo "auditswatch is already running."
-      exit 0
-    fi
-
-    if [ x"${zimbra_swatch_notice_user}" = "x" ]; then
-      echo "Must have a notification email address defined."
-      echo "Set localconfig -e zimbra_swatch_notice_user=admin@example.com"
-      exit 1
-    else 
-      zimbra_swatch_notice_user=$(echo ${zimbra_swatch_notice_user} | sed -e 's/\@/\\\\@/')
-    fi
-
-    if [ -f ${configfile}.custom ]; then
-      sed -e s/@@zimbra_swatch_acct_threshold@@/${zimbra_swatch_acct_threshold}/ \
-        -e s/@@zimbra_swatch_ip_threshold@@/${zimbra_swatch_ip_threshold}/ \
-        -e s/@@zimbra_swatch_ipacct_threshold@@/${zimbra_swatch_ipacct_threshold}/ \
-        -e s/@@zimbra_swatch_total_threshold@@/${zimbra_swatch_total_threshold}/ \
-        -e s/@@zimbra_swatch_threshold_seconds@@/${zimbra_swatch_threshold_seconds}/ \
-        -e s/@@zimbra_swatch_notice_user@@/${zimbra_swatch_notice_user}/ \
-        ${configfile}.in > ${configfile}
-    elif [ -f ${configfile}.in ]; then
-      sed -e s/@@zimbra_swatch_acct_threshold@@/${zimbra_swatch_acct_threshold}/ \
-        -e s/@@zimbra_swatch_ip_threshold@@/${zimbra_swatch_ip_threshold}/ \
-        -e s/@@zimbra_swatch_ipacct_threshold@@/${zimbra_swatch_ipacct_threshold}/ \
-        -e s/@@zimbra_swatch_total_threshold@@/${zimbra_swatch_total_threshold}/ \
-        -e s/@@zimbra_swatch_threshold_seconds@@/${zimbra_swatch_threshold_seconds}/ \
-        -e s/@@zimbra_swatch_notice_user@@/${zimbra_swatch_notice_user}/ \
-        ${configfile}.in > ${configfile}
-    else
-      echo "${configfile} template not found."
-      exit 1
-    fi
-
-    if [ ! -d ${zimbra_tmp_directory} ]; then
-      mkdir -p ${zimbra_tmp_directory} > /dev/null 2>&1
-    fi
-       
-    /opt/zimbra/libexec/auditswatch --config-file=${configfile} \
-      --use-cpan-file-tail \
-      --script-dir=${zimbra_tmp_directory} \
-      --tail-file /opt/zimbra/log/audit.log > $logfile 2>&1 &
-    pid=$!
-    if [ "x$pid" != 'x' ]; then
-      if [ -f $logfile ]; then
-        touch $logfile
-      fi
-      chmod 644 $logfile
-      echo $pid > $pidfile
-    else 
-      echo "failed."
-      exit 1
-    fi
-    checkrunning
-    if [ $running = 1 ]; then
-      echo "done."
-      exit 0
-    else
-      echo "failed."
-      exit 1
-    fi
-  ;;
-  stop)
-    checkrunning
-    echo -n "Stopping auditswatch..."
-    if [ $running = 0 ]; then
-      echo "auditswatch is not running."
-      exit 0
-    else
-      for ((i = 0; i < 30; i++)); do
-        kill -0 $pid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -rf ${pidfile}
-          break
-        fi
-        kill $pid
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
-    fi
+  checkrunning
+  echo -n "Starting auditswatch..."
+  if [ $running = 1 ]; then
+    echo "auditswatch is already running."
     exit 0
-  ;;
-  restart)
-    $0 stop
-    $0 start
-  ;;
-  reload)
-    checkrunning
-    if [ $running = 1 -a "x$pid" != "x" ]; then
-      echo -n "Reloading auditswatch..."
-      kill -HUP $pid
-      echo "done."
-    fi
-    
-  ;;
-  status)
-    echo -n "zmauditswatch is "
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "not running."
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
-  ;;
-  *)
-    echo "$0 start|stop|restart|reload|status"
+  fi
+
+  if [ x"${zimbra_swatch_notice_user}" = "x" ]; then
+    echo "Must have a notification email address defined."
+    echo "Set localconfig -e zimbra_swatch_notice_user=admin@example.com"
     exit 1
+  else
+    zimbra_swatch_notice_user=$(echo ${zimbra_swatch_notice_user} | sed -e 's/\@/\\\\@/')
+  fi
+
+  if [ -f ${configfile}.custom ]; then
+    sed -e s/@@zimbra_swatch_acct_threshold@@/${zimbra_swatch_acct_threshold}/ \
+      -e s/@@zimbra_swatch_ip_threshold@@/${zimbra_swatch_ip_threshold}/ \
+      -e s/@@zimbra_swatch_ipacct_threshold@@/${zimbra_swatch_ipacct_threshold}/ \
+      -e s/@@zimbra_swatch_total_threshold@@/${zimbra_swatch_total_threshold}/ \
+      -e s/@@zimbra_swatch_threshold_seconds@@/${zimbra_swatch_threshold_seconds}/ \
+      -e s/@@zimbra_swatch_notice_user@@/${zimbra_swatch_notice_user}/ \
+      ${configfile}.in >${configfile}
+  elif [ -f ${configfile}.in ]; then
+    sed -e s/@@zimbra_swatch_acct_threshold@@/${zimbra_swatch_acct_threshold}/ \
+      -e s/@@zimbra_swatch_ip_threshold@@/${zimbra_swatch_ip_threshold}/ \
+      -e s/@@zimbra_swatch_ipacct_threshold@@/${zimbra_swatch_ipacct_threshold}/ \
+      -e s/@@zimbra_swatch_total_threshold@@/${zimbra_swatch_total_threshold}/ \
+      -e s/@@zimbra_swatch_threshold_seconds@@/${zimbra_swatch_threshold_seconds}/ \
+      -e s/@@zimbra_swatch_notice_user@@/${zimbra_swatch_notice_user}/ \
+      ${configfile}.in >${configfile}
+  else
+    echo "${configfile} template not found."
+    exit 1
+  fi
+
+  if [ ! -d ${zimbra_tmp_directory} ]; then
+    mkdir -p ${zimbra_tmp_directory} >/dev/null 2>&1
+  fi
+
+  /opt/zextras/libexec/auditswatch --config-file=${configfile} \
+    --use-cpan-file-tail \
+    --script-dir=${zimbra_tmp_directory} \
+    --tail-file /opt/zextras/log/audit.log >$logfile 2>&1 &
+  pid=$!
+  if [ "x$pid" != 'x' ]; then
+    if [ -f $logfile ]; then
+      touch $logfile
+    fi
+    chmod 644 $logfile
+    echo $pid >$pidfile
+  else
+    echo "failed."
+    exit 1
+  fi
+  checkrunning
+  if [ $running = 1 ]; then
+    echo "done."
+    exit 0
+  else
+    echo "failed."
+    exit 1
+  fi
+  ;;
+stop)
+  checkrunning
+  echo -n "Stopping auditswatch..."
+  if [ $running = 0 ]; then
+    echo "auditswatch is not running."
+    exit 0
+  else
+    for ((i = 0; i < 30; i++)); do
+      kill -0 $pid 2>/dev/null
+      if [ $? != 0 ]; then
+        rm -rf ${pidfile}
+        break
+      fi
+      kill $pid
+      sleep 1
+    done
+  fi
+  if [ -s ${pidfile} ]; then
+    echo "failed."
+    exit 1
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
+restart)
+  $0 stop
+  $0 start
+  ;;
+reload)
+  checkrunning
+  if [ $running = 1 -a "x$pid" != "x" ]; then
+    echo -n "Reloading auditswatch..."
+    kill -HUP $pid
+    echo "done."
+  fi
+
+  ;;
+status)
+  echo -n "zmauditswatch is "
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "not running."
+    exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+*)
+  echo "$0 start|stop|restart|reload|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmcbpolicydctl b/src/bin/zmcbpolicydctl
--- a/src/bin/zmcbpolicydctl
+++ b/src/bin/zmcbpolicydctl
@@ -1,40 +1,28 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-  echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 pidfile=${cbpolicyd_pid_file:=${zimbra_log_directory}/cbpolicyd.pid}
-dbfile=${cbpolicyd_db_file:=/opt/zimbra/data/cbpolicyd/db/cbpolicyd.sqlitedb}
-
+dbfile=${cbpolicyd_db_file:=/opt/zextras/data/cbpolicyd/db/cbpolicyd.sqlitedb}
 
 rewriteconfig() {
-  /opt/zimbra/libexec/configrewrite cbpolicyd > /dev/null 2>&1
+  /opt/zextras/libexec/configrewrite cbpolicyd >/dev/null 2>&1
 }
 
 getpid() {
   if [ -f $pidfile ]; then
-    PID=`cat $pidfile`
+    PID=$(cat $pidfile)
   fi
 }
 
@@ -46,7 +34,7 @@ checkrunning() {
       rm -f $pidfile
     fi
   else
-    kill -0 $PID 2> /dev/null
+    kill -0 $PID 2>/dev/null
     if [ $? != 0 ]; then
       PID=""
       RUNNING=0
@@ -56,103 +44,102 @@ checkrunning() {
   fi
 }
 
-
 #
 # Main
 #
 case "$1" in
-  'start')
-    if [ ! -x /opt/zimbra/common/bin/cbpolicyd ]; then
-      echo "cbpolicyd not installed, skipping."
-      exit 0
-    fi
-    checkrunning
-  
-    echo -n "Starting policyd..."
-    if [ $RUNNING = 1 ]; then
-      echo "policyd is already running."
-      exit 0
-    else
-      if [ ! -d /opt/zimbra/data/cbpolicyd/db ]; then
-        mkdir /opt/zimbra/data/cbpolicyd/db
-      fi
-      if [ ! -f ${dbfile} ]; then
-        /opt/zimbra/libexec/zmcbpolicydinit
-        if [ $? != 0 ]; then
-          echo "Unable to initialize cbpolicyd database." 
-          exit 1
-        fi
-      fi
-      if [ x$2 = "x" ]; then
-        rewriteconfig
-      fi
-      /opt/zimbra/common/bin/cbpolicyd --config /opt/zimbra/conf/cbpolicyd.conf 2> /dev/null
-      for ((i=0; i < 30; i++)); do
-        sleep 1
-        checkrunning
-        if [ $RUNNING = 1 ]; then 
-          break
-        fi  
-      done
-      if [ "x$PID" = "x" ]; then
-        echo "failed."
-        exit 1
-      else 
-        echo "done."
-      fi 
-    fi
-  ;;
-
-  'kill')
-    $0 stop
-  ;;
-
-  'stop')
-    checkrunning
-    echo -n "Stopping policyd..."
-    if [ $RUNNING = 0 ]; then
-      echo "policyd is not running."
-      exit 0
-    else 
-      kill -TERM $PID 2> /dev/null
-      for ((i=0; i < 300; i++)); do
-        sleep 5
-        kill -0 $PID 2> /dev/null
-        if [ $? != 0 ]; then
-          echo " done."
-          exit 0
-        fi
-      done
-      kill -TERM $PID 2> /dev/null
-      if [ $? = 0 ]; then
-        echo " failed to stop $PID"
-        exit 1
-      else 
-        echo " done."
-      fi
-    fi
+'start')
+  if [ ! -x /opt/zextras/common/bin/cbpolicyd ]; then
+    echo "cbpolicyd not installed, skipping."
     exit 0
-  ;;
-    
-  'restart'|'reload')
-    $0 stop
-    $0 start $2
-  ;;
-  
-  'status')
-    checkrunning
-    echo -n "policyd is "
-    if [ $RUNNING = 0 ]; then
-      echo "not running."
+  fi
+  checkrunning
+
+  echo -n "Starting policyd..."
+  if [ $RUNNING = 1 ]; then
+    echo "policyd is already running."
+    exit 0
+  else
+    if [ ! -d /opt/zextras/data/cbpolicyd/db ]; then
+      mkdir /opt/zextras/data/cbpolicyd/db
+    fi
+    if [ ! -f ${dbfile} ]; then
+      /opt/zextras/libexec/zmcbpolicydinit
+      if [ $? != 0 ]; then
+        echo "Unable to initialize cbpolicyd database."
+        exit 1
+      fi
+    fi
+    if [ x$2 = "x" ]; then
+      rewriteconfig
+    fi
+    /opt/zextras/common/bin/cbpolicyd --config /opt/zextras/conf/cbpolicyd.conf 2>/dev/null
+    for ((i = 0; i < 30; i++)); do
+      sleep 1
+      checkrunning
+      if [ $RUNNING = 1 ]; then
+        break
+      fi
+    done
+    if [ "x$PID" = "x" ]; then
+      echo "failed."
       exit 1
     else
-      echo "running."
-      exit 0
+      echo "done."
     fi
+  fi
   ;;
-    
-  *)
-    echo "Usage: $0 start|stop|kill|reload|restart|status"
+
+'kill')
+  $0 stop
+  ;;
+
+'stop')
+  checkrunning
+  echo -n "Stopping policyd..."
+  if [ $RUNNING = 0 ]; then
+    echo "policyd is not running."
+    exit 0
+  else
+    kill -TERM $PID 2>/dev/null
+    for ((i = 0; i < 300; i++)); do
+      sleep 5
+      kill -0 $PID 2>/dev/null
+      if [ $? != 0 ]; then
+        echo " done."
+        exit 0
+      fi
+    done
+    kill -TERM $PID 2>/dev/null
+    if [ $? = 0 ]; then
+      echo " failed to stop $PID"
+      exit 1
+    else
+      echo " done."
+    fi
+  fi
+  exit 0
+  ;;
+
+'restart' | 'reload')
+  $0 stop
+  $0 start $2
+  ;;
+
+'status')
+  checkrunning
+  echo -n "policyd is "
+  if [ $RUNNING = 0 ]; then
+    echo "not running."
     exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+
+*)
+  echo "Usage: $0 start|stop|kill|reload|restart|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmclamdctl b/src/bin/zmclamdctl
--- a/src/bin/zmclamdctl
+++ b/src/bin/zmclamdctl
@@ -1,46 +1,35 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-  echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-if [ ! -x "/opt/zimbra/common/sbin/clamd" ]; then
+if [ ! -x "/opt/zextras/common/sbin/clamd" ]; then
   exit 0
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 pidfile=${zimbra_log_directory}/clamd.pid
 
-if [ ! -d "/opt/zimbra/data/clamav/db" ]; then
-    mkdir -p /opt/zimbra/data/clamav/db
+if [ ! -d "/opt/zextras/data/clamav/db" ]; then
+  mkdir -p /opt/zextras/data/clamav/db
 fi
 
 rewriteconfig() {
-  /opt/zimbra/libexec/configrewrite antivirus > /dev/null 2>&1
+  /opt/zextras/libexec/configrewrite antivirus >/dev/null 2>&1
 }
 
 getpid() {
   if [ -f $pidfile ]; then
-    cpid=`cat $pidfile`
+    cpid=$(cat $pidfile)
   fi
 }
 
@@ -63,112 +52,101 @@ checkrunning() {
 pskillall() {
   ps_cmd="/bin/ps ax -o pid,ppid,command"
   killsig="$1"
-  pname=`echo "$2" | sed -e 's%/%\\\/%g'`
-  plist=`${ps_cmd} | awk '{ if ( $3 ~ /'${pname}'/ ) { print $1 " " $2 } }' | sort -nr -k2 -k1 | awk '{ print $1 }'`
-  for p in ${plist}
-  do
+  pname=$(echo "$2" | sed -e 's%/%\\\/%g')
+  plist=$(${ps_cmd} | awk '{ if ( $3 ~ /'${pname}'/ ) { print $1 " " $2 } }' | sort -nr -k2 -k1 | awk '{ print $1 }')
+  for p in ${plist}; do
     kill ${killsig} ${p}
   done
 }
-
 
 #
 # Main
 #
 case "$1" in
-  'start')
-   if [ ! -f /opt/zimbra/data/clamav/db/daily.cvd ]; then
-      # Start with the files we ship.
-      cp -f /opt/zimbra/data/clamav/init/daily.cvd.init \
-        /opt/zimbra/data/clamav/db/daily.cvd
-      cp -f /opt/zimbra/data/clamav/init/main.cvd.init \
-        /opt/zimbra/data/clamav/db/main.cvd
-      cp -f /opt/zimbra/data/clamav/init/bytecode.cvd.init \
-        /opt/zimbra/data/clamav/db/bytecode.cvd
-    fi
-    if [ x$2 = "x" ]; then
-      rewriteconfig
-    fi
+'start')
+  if [ x$2 = "x" ]; then
+    rewriteconfig
+  fi
 
-    checkrunning
-    echo -n "Starting clamd..."
-    if [ $running = 1 ]; then
-      echo "clamd is already running.";
-    else
-      /opt/zimbra/common/sbin/clamd \
-        --config-file=/opt/zimbra/conf/clamd.conf \
-          >> ${zimbra_log_directory}/clamd.log 2>&1 &
+  checkrunning
+  echo -n "Starting clamd..."
+  if [ $running = 1 ]; then
+    echo "clamd is already running."
+  else
+    /opt/zextras/common/sbin/clamd \
+      --config-file=/opt/zextras/conf/clamd.conf \
+      >>${zimbra_log_directory}/clamd.log 2>&1 &
 
-      for ((i = 0; i < 12; i++)); do
-        checkrunning
-        if [ $running = 1 ]; then
-          echo "done."
+    for ((i = 0; i < 12; i++)); do
+      checkrunning
+      if [ $running = 1 ]; then
+        echo "done."
         exit 0
-        fi
-        sleep 5
-      done
+      fi
+      sleep 5
+    done
+    echo "failed."
+    exit 1
+  fi
+  exit 0
+  ;;
+
+'kill')
+  if [ -f /opt/zextras/log/clamd.pid ]; then
+    cpid=$(cat /opt/zextras/log/clamd.pid)
+    kill -9 "$cpid" 2>/dev/null
+  fi
+  pskillall -9 /opt/zextras/common/sbin/clamd
+  exit 0
+  ;;
+
+'stop')
+  checkrunning
+  echo -n "Stopping clamd..."
+  if [ $running = 0 ]; then
+    echo "clamd is not running."
+  else
+    if [ x"$cpid" != "x" ]; then
+      kill -TERM "$cpid" 2>/dev/null
+    fi
+    for ((i = 0; i < 30; i++)); do
+      sleep 2
+      kill -0 $cpid 2>/dev/null
+      if [ $? != 0 ]; then
+        rm -f ${pidfile}
+        break
+      fi
+      kill $cpid
+    done
+    if [ -s ${pidfile} ]; then
       echo "failed."
       exit 1
+    else
+      echo "done."
     fi
-    exit 0
-   ;;
-  
-  'kill')
-    if [ -f /opt/zimbra/log/clamd.pid ]; then
-      cpid=`cat /opt/zimbra/log/clamd.pid`
-      kill -9 "$cpid" 2> /dev/null
-    fi
-    pskillall -9 /opt/zimbra/common/sbin/clamd
-    exit 0
-   ;;
+  fi
+  exit 0
+  ;;
 
-  'stop')
-    checkrunning
-    echo -n "Stopping clamd..."
-    if [ $running = 0 ]; then
-      echo "clamd is not running.";
-    else
-      if [ x"$cpid" != "x" ]; then
-        kill -TERM "$cpid" 2> /dev/null
-      fi
-      for ((i = 0; i < 30; i++)); do
-        sleep 2
-        kill -0 $cpid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -f ${pidfile}
-          break
-        fi
-        kill $cpid
-      done
-      if [ -s ${pidfile} ]; then
-        echo "failed."
-        exit 1
-      else
-        echo "done."
-      fi
-    fi
+'restart' | 'reload')
+  $0 stop
+  $0 start $2
+  ;;
+
+'status')
+  checkrunning
+  echo -n "clamd is "
+  if [ $running = 1 ]; then
+    echo "running."
     exit 0
-  ;;
-  
-  'restart'|'reload')
-    $0 stop
-    $0 start $2
-  ;;
-  
-  'status')
-    checkrunning
-    echo -n "clamd is "
-    if [ $running = 1 ]; then
-      echo "running."
-      exit 0
-    else
-      echo "not runnning."
-      exit 1
-    fi
-  ;;
-  
-  *)
-    echo "Usage: $0 start|stop|kill|restart|status"
+  else
+    echo "not runnning."
     exit 1
+  fi
+  ;;
+
+*)
+  echo "Usage: $0 start|stop|kill|restart|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmconfigdctl b/src/bin/zmconfigdctl
--- a/src/bin/zmconfigdctl
+++ b/src/bin/zmconfigdctl
@@ -1,106 +1,93 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2010, 2011, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-	echo Error: must be run as zimbra user
-  exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+	echo Error: must be run as zextras user
+	exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 # These variables are not set if run via cron.  Make sure they are set prior to execution
 if [ x"$JYTHONPATH" = "x" ]; then
-  JAVA_HOME=/opt/zimbra/common/lib/jvm/java
-  PATH=/opt/zimbra/bin:/opt/zimbra/common/bin:${JAVA_HOME}/bin:/usr/sbin:${PATH}
-  export PATH
+	JAVA_HOME=/opt/zextras/common/lib/jvm/java
+	PATH=/opt/zextras/bin:/opt/zextras/common/bin:${JAVA_HOME}/bin:/usr/sbin:${PATH}
+	export PATH
 
-  JYTHONPATH="/opt/zimbra/common/lib/jylibs"
-  export JYTHONPATH
+	JYTHONPATH="/opt/zextras/common/lib/jylibs"
+	export JYTHONPATH
 fi
- 
+
 pid=""
 pidfile="${zimbra_log_directory}/zmconfigd.pid"
 
-NC=`which nc 2>/dev/null`; NC=${NC:-`which netcat 2>/dev/null`}
+NC=$(which nc 2>/dev/null)
+NC=${NC:-$(which netcat 2>/dev/null)}
 
-getpid()
-{
-  if [ -f ${pidfile} ]; then
-	pid=$(cat ${pidfile})
-  fi
+getpid() {
+	if [ -f ${pidfile} ]; then
+		pid=$(cat ${pidfile})
+	fi
 }
 
-checkrunning()
-{
-  getpid
-  if [ "x$pid" = "x0" ]; then
-    pid=`ps auxwww | grep zmconfigd | grep -v grep | grep -v zmconfigdctl |  awk '{print $2}'`
-  fi
-  if [ "x$pid" = "x" ]; then
-	running=0
-  else
-	status=`echo STATUS | $NC -w 15 localhost ${zmconfigd_listen_port} 2>/dev/null`
-	if [ $? = 0 -a "x$status" = "xSUCCESS ACTIVE" ]; then
-		running=1
-	else
-		running=0
+checkrunning() {
+	getpid
+	if [ "x$pid" = "x0" ]; then
+		pid=$(ps auxwww | grep zmconfigd | grep -v grep | grep -v zmconfigdctl | awk '{print $2}')
 	fi
-  fi
-} 
+	if [ "x$pid" = "x" ]; then
+		running=0
+	else
+		status=$(echo STATUS | $NC -w 15 localhost ${zmconfigd_listen_port} 2>/dev/null)
+		if [ $? = 0 -a "x$status" = "xSUCCESS ACTIVE" ]; then
+			running=1
+		else
+			running=0
+		fi
+	fi
+}
 
-startzmconfigd()
-{
+startzmconfigd() {
 	err=0
 	checkrunning
 	echo -n "Starting zmconfigd..."
 	if [ $running = 1 ]; then
-	  echo "zmconfigd is already running."
-	  return
+		echo "zmconfigd is already running."
+		return
 	fi
 	if [ "x$JYTHONPATH" = "x" ]; then
-	  echo "JYTHONPATH is unset!"
-	  err=1
-	  return
+		echo "JYTHONPATH is unset!"
+		err=1
+		return
 	fi
 	if [ "x${pid}" != "x" ]; then
 		kill -9 ${pid}
 	fi
 	rm -rf ${pidfile}
-	/opt/zimbra/libexec/zmconfigd >/dev/null 2>&1 &
-	for ((i = 0; i < 30; i++)) do
+	/opt/zextras/libexec/zmconfigd >/dev/null 2>&1 &
+	for ((i = 0; i < 30; i++)); do
 		if [ -f ${pidfile} ]; then
 			break
 		fi
 		sleep 1
 	done
-	for ((i = 0; i < ${zmconfigd_startup_pause}; i++)) do
-	  checkrunning
-	  if [ $running = 1 ]; then
-		echo "done."
-		return
-	  fi
-	  if [ $running = -1 ]; then
-		echo "Failed to start"
-		err=1
-		return
-	  fi
-	  sleep 1
+	for ((i = 0; i < ${zmconfigd_startup_pause}; i++)); do
+		checkrunning
+		if [ $running = 1 ]; then
+			echo "done."
+			return
+		fi
+		if [ $running = -1 ]; then
+			echo "Failed to start"
+			err=1
+			return
+		fi
+		sleep 1
 	done
 	echo "failed."
 	err=1
@@ -108,58 +95,58 @@ startzmconfigd()
 }
 
 case "$1" in
-  'start')
+'start')
 	startzmconfigd
 	exit ${err}
-   ;;
+	;;
 
-  'kill'|'stop')
+'kill' | 'stop')
 	checkrunning
 	echo -n "Stopping zmconfigd..."
 	if [ $running -lt 1 ]; then
-	  echo "zmconfigd is not running."
-	  exit 0
-	else 
-	  for ((i = 0; i < 30; i++)); do
-		kill -0 $pid 2> /dev/null
-		if [ $? != 0 ]; then
-		  rm -rf ${pidfile}
-		  break
-		fi
-		kill $pid
-		sleep 1
-	  done
+		echo "zmconfigd is not running."
+		exit 0
+	else
+		for ((i = 0; i < 30; i++)); do
+			kill -0 $pid 2>/dev/null
+			if [ $? != 0 ]; then
+				rm -rf ${pidfile}
+				break
+			fi
+			kill $pid
+			sleep 1
+		done
 	fi
 	if [ -s ${pidfile} ]; then
-	  echo "failed."
-	  exit 1
+		echo "failed."
+		exit 1
 	else
-	  echo "done."
+		echo "done."
 	fi
 	exit 0
-  ;;
+	;;
 
-	
-  'restart'|'reload')
+\
+	'restart' | 'reload')
 	$0 stop
 	$0 start
-  ;;
-  
-  'status')
+	;;
+
+'status')
 	echo -n "zmconfigd is "
 	checkrunning
 	if [ $running -lt 1 ]; then
-	  echo "not running." 
-	  exit 1
+		echo "not running."
+		exit 1
 	else
-	  echo "running."
-	  exit 0
+		echo "running."
+		exit 0
 	fi
-   ;;
-	
-  *)
+	;;
+
+*)
 	echo "Usage: $0 start|stop|kill|restart|reload|status"
 	exit 1
-  ;;
+	;;
 
 esac
diff --git a/src/bin/zmfreshclamctl b/src/bin/zmfreshclamctl
--- a/src/bin/zmfreshclamctl
+++ b/src/bin/zmfreshclamctl
@@ -1,44 +1,31 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2011, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-  echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-if [ ! -x "/opt/zimbra/common/bin/freshclam" ]; then
+if [ ! -x "/opt/zextras/common/bin/freshclam" ]; then
   exit 0
 fi
 
-platform=`/opt/zimbra/libexec/get_plat_tag.sh`
-
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 fpidfile=${zimbra_log_directory}/freshclam.pid
 
 rewriteconfig() {
-  /opt/zimbra/libexec/configrewrite antivirus > /dev/null 2>&1
+  /opt/zextras/libexec/configrewrite antivirus >/dev/null 2>&1
 }
 
 getpid() {
   if [ -f $fpidfile ]; then
-    fpid=`cat $fpidfile`
+    fpid=$(cat $fpidfile)
   fi
 }
 
@@ -48,7 +35,7 @@ checkrunning() {
   if [ "x$fpid" = "x" ]; then
     frunning=0
   else
-    if ps --no-headers -p $fpid -o cmd 2>/dev/null |grep freshclam >/dev/null 2>&1; then
+    if ps --no-headers -p $fpid -o cmd 2>/dev/null | grep freshclam >/dev/null 2>&1; then
       frunning=1
     else
       rm $fpidfile
@@ -61,85 +48,83 @@ checkrunning() {
 pskillall() {
   ps_cmd="/bin/ps ax -o pid,ppid,command"
   killsig="$1"
-  pname=`echo "$2" | sed -e 's%/%\\\/%g'`
-  plist=`${ps_cmd} | awk '{ if ( $3 ~ /'${pname}'/ ) { print $1 " " $2 } }' | sort -nr -k2 -k1 | awk '{ print $1 }'`
-  for p in ${plist}
-  do
+  pname=$(echo "$2" | sed -e 's%/%\\\/%g')
+  plist=$(${ps_cmd} | awk '{ if ( $3 ~ /'${pname}'/ ) { print $1 " " $2 } }' | sort -nr -k2 -k1 | awk '{ print $1 }')
+  for p in ${plist}; do
     kill ${killsig} ${p}
   done
 }
-
 
 #
 # Main
 #
 case "$1" in
-  'start')
+'start')
 
-    if [ x$2 = "x" ]; then
-      rewriteconfig
-    fi
+  if [ x$2 = "x" ]; then
+    rewriteconfig
+  fi
 
-    checkrunning
-    echo -n "Starting freshclam..."
-    if [ $frunning = 1 ]; then
-      echo "freshclam is already running.";
-    else
-      /opt/zimbra/common/bin/freshclam \
-        --config-file=/opt/zimbra/conf/freshclam.conf --quiet --daemon --checks=12 \
-          >> ${zimbra_log_directory}/freshclam.log 2>&1 &
-      echo "done."
-    fi
-    exit 0
-   ;;
+  checkrunning
+  echo -n "Starting freshclam..."
+  if [ $frunning = 1 ]; then
+    echo "freshclam is already running."
+  else
+    /opt/zextras/common/bin/freshclam \
+      --config-file=/opt/zextras/conf/freshclam.conf --quiet --daemon --checks=12 \
+      >>${zimbra_log_directory}/freshclam.log 2>&1 &
+    echo "done."
+  fi
+  exit 0
+  ;;
 
-  'kill')
-    if [ -f /opt/zimbra/log/freshclam.pid ]; then
-      cpid=`cat /opt/zimbra/log/freshclam.pid`
-      kill -9 "$cpid" 2> /dev/null
-    fi
-    pskillall -9 /opt/zimbra/common/bin/freshclam
-    exit 0
-   ;;
+'kill')
+  if [ -f /opt/zextras/log/freshclam.pid ]; then
+    cpid=$(cat /opt/zextras/log/freshclam.pid)
+    kill -9 "$cpid" 2>/dev/null
+  fi
+  pskillall -9 /opt/zextras/common/bin/freshclam
+  exit 0
+  ;;
 
-  'stop')
-    checkrunning
-    echo -n "Stopping freshclam..."
-    if [ $frunning = 0 ]; then
-      echo "freshclam is not running.";
-    else 
-      if [ x"$fpid" != "x" ]; then  
-        kill -9 "$fpid" 2> /dev/null
-        if [ $? = 0 ]; then
-          echo "done."
-        else 
-          echo "failed."
-        fi
+'stop')
+  checkrunning
+  echo -n "Stopping freshclam..."
+  if [ $frunning = 0 ]; then
+    echo "freshclam is not running."
+  else
+    if [ x"$fpid" != "x" ]; then
+      kill -9 "$fpid" 2>/dev/null
+      if [ $? = 0 ]; then
+        echo "done."
+      else
+        echo "failed."
       fi
     fi
+  fi
 
+  exit 0
+  ;;
+
+'restart' | 'reload')
+  $0 stop
+  $0 start $2
+  ;;
+
+'status')
+  checkrunning
+  echo -n "freshclam is "
+  if [ $frunning = 1 ]; then
+    echo "running."
     exit 0
-  ;;
-  
-  'restart'|'reload')
-    $0 stop
-    $0 start $2
-  ;;
-  
-  'status')
-    checkrunning
-    echo -n "freshclam is "
-    if [ $frunning = 1 ]; then
-      echo "running."
-      exit 0
-    else
-      echo "not runnning."
-      exit 1
-    fi
-  ;;
-  
-  *)
-    echo "Usage: $0 start|stop|kill|restart|status"
+  else
+    echo "not runnning."
     exit 1
+  fi
+  ;;
+
+*)
+  echo "Usage: $0 start|stop|kill|restart|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zminnotop b/src/bin/zminnotop
--- a/src/bin/zminnotop
+++ b/src/bin/zminnotop
@@ -1,27 +1,16 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-  echo "Error: must be run as zimbra user"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo "Error: must be run as zextras user"
   exit 1
 fi
 
-if [ ! -x /opt/zimbra/common/bin/mysql ]; then
+if [ ! -x /opt/zextras/common/bin/mysql ]; then
   echo "Error: mariadb not available"
   exit 1
 fi
@@ -43,14 +32,14 @@ if [ x"$1" = "x-h" ]; then
   exit 0
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-if [ -x "/opt/zimbra/common/bin/innotop" ]; then
+if [ -x "/opt/zextras/common/bin/innotop" ]; then
   if [ x"$1" = "x-r" ]; then
     shift
-    /opt/zimbra/common/bin/innotop --socket $mysql_socket --user root --password $mysql_root_password $@
+    /opt/zextras/common/bin/innotop --socket $mysql_socket --user root --password $mysql_root_password $@
   else
-    /opt/zimbra/common/bin/innotop --socket $mysql_socket --user $zimbra_mysql_user --password $zimbra_mysql_password $@
+    /opt/zextras/common/bin/innotop --socket $mysql_socket --user $zimbra_mysql_user --password $zimbra_mysql_password $@
   fi
 fi
diff --git a/src/bin/zmlogswatchctl b/src/bin/zmlogswatchctl
--- a/src/bin/zmlogswatchctl
+++ b/src/bin/zmlogswatchctl
@@ -1,26 +1,14 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-configfile=/opt/zimbra/conf/logswatchrc
+configfile=/opt/zextras/conf/logswatchrc
 pidfile=${zimbra_log_directory}/logswatch.pid
 zmrrdfetchpidfile=${zimbra_log_directory}/zmrrdfetch-server.pid
 zmrrdfetchpid=""
@@ -28,8 +16,7 @@ logfile=${zimbra_log_directory}/zmlogswatch.out
 pid=""
 os=$(uname -s)
 
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
@@ -38,13 +25,12 @@ getpid()
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
   else
-    if ps --no-headers -p $pid -o cmd 2>/dev/null |grep swatchdog >/dev/null 2>&1; then
+    if ps --no-headers -p $pid -o cmd 2>/dev/null | grep swatchdog >/dev/null 2>&1; then
       running=1
     else
       pid=""
@@ -53,123 +39,124 @@ checkrunning()
   fi
 }
 
-case "$1" in 
-  start)
-    if [ ! -f ${configfile} ]; then
-      echo "${configfile} is missing."
-      exit 0
-    fi
+case "$1" in
+start)
+  if [ ! -f ${configfile} ]; then
+    echo "${configfile} is missing."
+    exit 0
+  fi
 
+  checkrunning
+  echo -n "Starting logswatch..."
+  if [ $running = 1 ]; then
+    echo "logswatch is already running."
+    exit 0
+  fi
+
+  /opt/zextras/bin/zmprov -l gs $(/opt/zextras/bin/zmhostname) zimbraServiceEnabled | grep -qw logger
+  if [ $? = 1 ]; then
+    echo "carbonio logger service is not enabled!  failed."
+    exit 1
+  fi
+
+  if [ ! -d ${zimbra_tmp_directory} ]; then
+    mkdir -p ${zimbra_tmp_directory} >/dev/null 2>&1
+  fi
+
+  /opt/zextras/common/bin/swatchdog --config-file=${configfile} \
+    --use-cpan-file-tail --pid-file=${pidfile} --daemon \
+    --script-dir=${zimbra_tmp_directory} \
+    --tail-file /var/log/carbonio-stats.log >$logfile 2>&1
+  for ((i = 0; i < 30; i++)); do
     checkrunning
-    echo -n "Starting logswatch..."
     if [ $running = 1 ]; then
-      echo "logswatch is already running."
-      exit 0
+      break
     fi
-
-    /opt/zimbra/bin/zmprov -l gs `/opt/zimbra/bin/zmhostname` zimbraServiceEnabled | grep -qw logger
-    if [ $? = 1 ]; then
-        echo "zimbra logger service is not enabled!  failed."
-        exit 1
-    fi
-
-    if [ ! -d ${zimbra_tmp_directory} ]; then
-      mkdir -p ${zimbra_tmp_directory} > /dev/null 2>&1
-    fi
-
-    /opt/zimbra/common/bin/swatchdog --config-file=${configfile} \
-      --use-cpan-file-tail --pid-file=${pidfile} --daemon \
-      --script-dir=${zimbra_tmp_directory} \
-      --tail-file /var/log/zimbra-stats.log > $logfile 2>&1
-    for ((i=0; i < 30; i++)); do
-      checkrunning
-      if [ $running = 1 ]; then
+    sleep 1
+  done
+  if [ "x$pid" != "x" ]; then
+    echo "done."
+    exit 0
+  else
+    echo "failed."
+    exit 1
+  fi
+  ;;
+stop)
+  checkrunning
+  echo -n "Stopping logswatch..."
+  if [ $running = 0 ]; then
+    echo "logswatch is not running."
+    exit 0
+  else
+    for ((i = 0; i < 30; i++)); do
+      if [ -z "$zmrrdfetchpid" ]; then
         break
+      fi
+      if ! ps --no-headers -p $zmrrdfetchpid -o cmd 2>/dev/null | grep zmrrdfetch >/dev/null 2>&1; then
+        rm -f ${zmrrdfetchpidfile}
+        break
+      fi
+      kill $zmrrdfetchpid 2>/dev/null
+      sleep 1
+    done
+    if [ -n "$zmrrdfetchpid" ]; then
+      if ps --no-headers -p $zmrrdfetchpid -o cmd 2>/dev/null | grep zmrrdfetch >/dev/null 2>&1; then
+        kill -9 $zmrrdfetchpid
+      fi
+    fi
+    for ((i = 0; i < 30; i++)); do
+      if ! ps --no-headers -p $pid -o cmd 2>/dev/null | grep swatchdog >/dev/null 2>&1; then
+        rm -rf ${pidfile}
+        break
+      fi
+      if [ x"$os" = "xLinux" ]; then
+        index=0
+        quit=0
+        ids[$index]="$pid"
+        while [ $quit -eq 0 ]; do
+          ((index++))
+          ids[$index]=$(ps -o pid --ppid ${ids[$index - 1]} | grep -v PID | tr \\n ' ')
+          if [ ! "${ids[$index]}" ]; then
+            ((quit++))
+          fi
+        done
+        for i in $(seq 0 ${#ids[@]}); do
+          if [ "${ids[$i]}" ]; then
+            kill -9 ${ids[$i]} 2>/dev/null
+          fi
+        done
+      else
+        kill -9 $pid
       fi
       sleep 1
     done
-    if [ "x$pid" != "x" ]; then
-      echo "done."
-      exit 0
-    else
-      echo "failed."
-      exit 1
-    fi
-  ;;
-  stop)
-    checkrunning
-    echo -n "Stopping logswatch..."
-    if [ $running = 0 ]; then
-      echo "logswatch is not running."
-      exit 0
-    else
-      for ((i = 0; i < 30; i++)); do
-          if [ -z "$zmrrdfetchpid" ]; then
-              break;
-          fi
-          if ! ps --no-headers -p $zmrrdfetchpid -o cmd 2>/dev/null |grep zmrrdfetch >/dev/null 2>&1; then
-              rm -f ${zmrrdfetchpidfile}
-              break;
-          fi
-          kill $zmrrdfetchpid 2> /dev/null
-          sleep 1
-      done
-      if [ -n "$zmrrdfetchpid" ]; then
-          if ps --no-headers -p $zmrrdfetchpid -o cmd 2>/dev/null |grep zmrrdfetch >/dev/null 2>&1; then
-              kill -9 $zmrrdfetchpid
-          fi
-      fi
-      for ((i = 0; i < 30; i++)); do
-        if ! ps --no-headers -p $pid -o cmd 2>/dev/null |grep swatchdog >/dev/null 2>&1; then
-          rm -rf ${pidfile}
-          break
-        fi
-        if [ x"$os" = "xLinux" ]; then
-          index=0;quit=0
-          ids[$index]="$pid"
-          while [ $quit -eq 0 ]; do
-            ((index++))
-            ids[$index]=$(ps -o pid --ppid ${ids[$index-1]} | grep -v PID | tr \\n ' ')
-            if [ ! "${ids[$index]}" ]; then
-              ((quit++))
-            fi
-          done
-          for i in $(seq 0 ${#ids[@]}); do
-            if [ "${ids[$i]}" ]; then
-              kill -9 ${ids[$i]} 2> /dev/null
-            fi
-          done
-        else
-          kill -9 $pid
-        fi 
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
-    fi
-    exit 0
-  ;;
-  restart|reload)
-    $0 stop
-    $0 start
-  ;;
-  status)
-    echo -n "zmlogswatch is "
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "not running."
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
-  ;;
-  *)
-    echo "$0 start|stop|restart|reload|status"
+  fi
+  if [ -s ${pidfile} ]; then
+    echo "failed."
     exit 1
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
+restart | reload)
+  $0 stop
+  $0 start
+  ;;
+status)
+  echo -n "zmlogswatch is "
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "not running."
+    exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+*)
+  echo "$0 start|stop|restart|reload|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmmailboxdctl b/src/bin/zmmailboxdctl
--- a/src/bin/zmmailboxdctl
+++ b/src/bin/zmmailboxdctl
@@ -1,29 +1,18 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source `dirname $0`/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 if [ ! -d ${mailboxd_directory} ]; then
   exit 0
 fi
 
-if [ ! -x /opt/zimbra/common/bin/mysql ]; then
+if [ ! -x /opt/zextras/common/bin/mysql ]; then
   exit 0
 fi
 
@@ -31,8 +20,8 @@ if [ ! -d ${zimbra_java_home} ]; then
   exit 0
 fi
 
-NC=`which nc 2>/dev/null`; NC=${NC:-`which netcat 2>/dev/null`}
-platform=`/opt/zimbra/libexec/get_plat_tag.sh`
+NC=$(which nc 2>/dev/null)
+NC=${NC:-$(which netcat 2>/dev/null)}
 #
 # Memory for use by JVM.
 #
@@ -42,127 +31,113 @@ mailboxd_java_heap_new_size_percent=${mailboxd_java_heap_new_size_percent:=25}
 javaXmn=$(expr ${javaXmx} '*' ${mailboxd_java_heap_new_size_percent} / 100)
 
 #
-# Spnego - the spnego_options_file is written by zmconfigd 
+# Spnego - the spnego_options_file is written by zmconfigd
 #          to avoid a zmprov call here.
 #
-spnego_options_file=/opt/zimbra/conf/spnego_java_options
+spnego_options_file=/opt/zextras/conf/spnego_java_options
 if [ -e ${spnego_options_file} ]; then
   spnegoJavaOptions=$(cat $spnego_options_file)
 fi
 
 #
-# Expand war files.
-#
-mk_download_dir() {
-  if [ -d "${mailboxd_directory}/webapps/zimbra/downloads" ]; then
-    /opt/zimbra/libexec/zmupdatedownload
-  fi
-}
-
-#
 # Main
 #
 case "$1" in
-    'start')
-      mk_download_dir
-	  if [ "x$2" = "x" ]; then
-		  /opt/zimbra/bin/zmtlsctl > /dev/null 2>&1
-	  fi
-      sudo /opt/zimbra/libexec/zmmailboxdmgr status
-      if [ $? = 0 ]; then
-        echo "mailboxd already running."
-        exit 0
-      fi
+'start')
+  if [ "x$2" = "x" ]; then
+    /opt/zextras/bin/zmtlsctl >/dev/null 2>&1
+  fi
+  sudo /opt/zextras/libexec/zmmailboxdmgr status
+  if [ $? = 0 ]; then
+    echo "mailboxd already running."
+    exit 0
+  fi
 
-      mkdir -p ${mailboxd_directory}/work/service/jsp
-      mkdir -p ${mailboxd_directory}/work/zimbra/jsp
-      mkdir -p ${mailboxd_directory}/work/zimbraAdmin/jsp
-      if [ ! -d ${mailboxd_directory}/webapps/zimlet/WEB-INF ]; then
-        mkdir -p ${mailboxd_directory}/webapps/zimlet/WEB-INF
-      fi
+  mkdir -p ${mailboxd_directory}/work/service/jsp
+  mkdir -p ${mailboxd_directory}/work/zimbra/jsp
+  mkdir -p ${mailboxd_directory}/work/zimbraAdmin/jsp
+  if [ ! -d ${mailboxd_directory}/webapps/zimlet/WEB-INF ]; then
+    mkdir -p ${mailboxd_directory}/webapps/zimlet/WEB-INF
+  fi
 
-      mailboxd_thread_stack_size=${mailboxd_thread_stack_size:=256k}
-      if [ -z "`echo ${mailboxd_java_options} | grep Xss`" ]; then
-        mailboxd_java_options="${mailboxd_java_options} -Xss${mailboxd_thread_stack_size}"
-      fi
+  mailboxd_thread_stack_size=${mailboxd_thread_stack_size:=256k}
+  if [ -z "$(echo ${mailboxd_java_options} | grep Xss)" ]; then
+    mailboxd_java_options="${mailboxd_java_options} -Xss${mailboxd_thread_stack_size}"
+  fi
 
-      networkaddress_cache_ttl=${networkaddress_cache_ttl:=60}
-      if [ -z "`echo ${mailboxd_java_options} | grep sun.net.inetaddr.ttl`" ]; then
-        mailboxd_java_options="${mailboxd_java_options} -Dsun.net.inetaddr.ttl=${networkaddress_cache_ttl}"
-      fi
-      echo -n "Starting mailboxd..."
-      sudo /opt/zimbra/libexec/zmmailboxdmgr start \
-        -Dfile.encoding=UTF-8 ${mailboxd_java_options} ${spnegoJavaOptions} -Xms${javaXms}m \
-        -Xmx${javaXmx}m < /dev/null > /dev/null 2>&1
-      status=$?
-      if [ $status != 0 ]; then
-        echo "failed."
-        exit $status
-      fi
-      status=1
-      MPORT=`/opt/zimbra/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMailPort | grep zimbraMailPort: | awk '{print $2}'`
-      if [ x$platform = "xRHEL7_64" ]; then
-        ncOpt="--send-only --recv-only"
-      else
-        ncOpt="-z"
-      fi
-      for ((i=0; i < 12; i++)); do
-        $NC $ncOpt localhost ${MPORT} >/dev/null 2>&1
-        if [ $? = 0 ]; then
-          status=0
-          break
-        fi
-        sleep 5
-      done
-      if [ $status = 0 ]; then
-        echo "done."
-      else
-        echo "failed."
-      fi
-      exit $status 
-    ;;
+  networkaddress_cache_ttl=${networkaddress_cache_ttl:=60}
+  if [ -z "$(echo ${mailboxd_java_options} | grep sun.net.inetaddr.ttl)" ]; then
+    mailboxd_java_options="${mailboxd_java_options} -Dsun.net.inetaddr.ttl=${networkaddress_cache_ttl}"
+  fi
+  echo -n "Starting mailboxd..."
+  sudo /opt/zextras/libexec/zmmailboxdmgr start \
+    -Dfile.encoding=UTF-8 ${mailboxd_java_options} ${spnegoJavaOptions} -Xms${javaXms}m \
+    -Xmx${javaXmx}m </dev/null >/dev/null 2>&1
+  status=$?
+  if [ $status != 0 ]; then
+    echo "failed."
+    exit $status
+  fi
+  status=1
+  MPORT=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMailPort | grep zimbraMailPort: | awk '{print $2}')
+  ncOpt="-z"
+  for ((i = 0; i < 12; i++)); do
+    $NC $ncOpt localhost ${MPORT} >/dev/null 2>&1
+    if [ $? = 0 ]; then
+      status=0
+      break
+    fi
+    sleep 5
+  done
+  if [ $status = 0 ]; then
+    echo "done."
+  else
+    echo "failed."
+  fi
+  exit $status
+  ;;
 
-    'kill'|'stop')
-      echo -n "Stopping mailboxd..."
-      sudo /opt/zimbra/libexec/zmmailboxdmgr status
-      if [ $? != 0 ]; then
-        echo "mailboxd is not running."
-        exit 0
-      fi
-      /opt/zimbra/bin/zmthrdump -i -o /opt/zimbra/log/stacktrace.$$.$(date +%Y%m%d%H%M%S) 2> /dev/null
-      sudo /opt/zimbra/libexec/zmmailboxdmgr stop 
-      if [ $? = 0 ]; then
-        echo "done."
-      else 
-        echo "failed."
-      fi 
-      exit 0
-    ;;
+'kill' | 'stop')
+  echo -n "Stopping mailboxd..."
+  sudo /opt/zextras/libexec/zmmailboxdmgr status
+  if [ $? != 0 ]; then
+    echo "mailboxd is not running."
+    exit 0
+  fi
+  /opt/zextras/bin/zmthrdump -i -o /opt/zextras/log/stacktrace.$$.$(date +%Y%m%d%H%M%S) 2>/dev/null
+  sudo /opt/zextras/libexec/zmmailboxdmgr stop
+  if [ $? = 0 ]; then
+    echo "done."
+  else
+    echo "failed."
+  fi
+  exit 0
+  ;;
 
-    
-    'restart'|'reload')
-        $0 stop
-        $0 start $2
-    ;;
-    
-    'status')
-      echo -n "mailboxd is "
-      sudo /opt/zimbra/libexec/zmmailboxdmgr status
-      if [ $? = 0 ]; then
-        echo "running."
-        exit 0
-      else 
-        echo "not running."
-        exit 1
-      fi
-    ;;
+\
+  'restart' | 'reload')
+  $0 stop
+  $0 start $2
+  ;;
 
-	'update')
-		mk_download_dir
-	;;
+'status')
+  echo -n "mailboxd is "
+  sudo /opt/zextras/libexec/zmmailboxdmgr status
+  if [ $? = 0 ]; then
+    echo "running."
+    exit 0
+  else
+    echo "not running."
+    exit 1
+  fi
+  ;;
 
-    *)
-      echo "Usage: $0 start|stop|kill|restart|reload|status|update"
-      exit 1
-    ;;
+'update')
+  mk_download_dir
+  ;;
+
+*)
+  echo "Usage: $0 start|stop|kill|restart|reload|status|update"
+  exit 1
+  ;;
 esac
diff --git a/src/bin/zmmemcachedctl b/src/bin/zmmemcachedctl
--- a/src/bin/zmmemcachedctl
+++ b/src/bin/zmmemcachedctl
@@ -1,48 +1,35 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2008, 2009, 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 servicename=memcached
-configfile=/opt/zimbra/conf/${servicename}.conf
+configfile=/opt/zextras/conf/${servicename}.conf
 pidfile=${zimbra_log_directory}/${servicename}.pid
 pid=""
 
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
   else
-    if ps --no-headers -p $pid -o cmd 2>/dev/null |grep memcached >/dev/null 2>&1; then
+    if ps --no-headers -p $pid -o cmd 2>/dev/null | grep memcached >/dev/null 2>&1; then
       running=1
     else
       pid=""
@@ -51,95 +38,95 @@ checkrunning()
   fi
 }
 
-case "$1" in 
-  start)
+case "$1" in
+start)
 
-    if [ ! -x /opt/zimbra/common/bin/memcached ]; then
-      echo "Error: memcached not installed"
-      exit 1
-    fi
+  if [ ! -x /opt/zextras/common/bin/memcached ]; then
+    echo "Error: memcached not installed"
+    exit 1
+  fi
 
+  checkrunning
+  echo -n "Starting ${servicename}..."
+  if [ $running = 1 ]; then
+    echo "${servicename} is already running."
+    exit 0
+  fi
+
+  addr=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindAddress | awk '/^zimbraMemcachedBindAddress:/{ print $2 }')
+  addr="${addr//$'\n'/,}"
+  port=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindPort | awk '/^zimbraMemcachedBindPort:/{ print $2 }')
+  if [ x"$addr" = "x" ]; then
+    /opt/zextras/common/bin/${servicename} -d -P ${pidfile} -U 0 -l 127.0.1.1,127.0.0.1,::1 -p ${port:-11211}
+  else
+    /opt/zextras/common/bin/${servicename} -d -P ${pidfile} -U 0 -l ${addr} -p ${port:-11211}
+  fi
+  for ((i = 0; i < 30; i++)); do
     checkrunning
-    echo -n "Starting ${servicename}..."
     if [ $running = 1 ]; then
-      echo "${servicename} is already running."
-      exit 0
+      break
     fi
-
-    addr=$(/opt/zimbra/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindAddress | awk '/^zimbraMemcachedBindAddress:/{ print $2 }')
-    addr="${addr//$'\n'/,}"
-    port=$(/opt/zimbra/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindPort | awk '/^zimbraMemcachedBindPort:/{ print $2 }')
-    if [ x"$addr" = "x" ]; then
-      /opt/zimbra/common/bin/${servicename} -d -P ${pidfile} -U 0 -p ${port:-11211}
-    else
-      /opt/zimbra/common/bin/${servicename} -d -P ${pidfile} -U 0 -l ${addr} -p ${port:-11211}
-    fi
-    for ((i=0; i < 30; i++)); do
-      checkrunning
-      if [ $running = 1 ]; then
+    sleep 1
+  done
+  if [ "x$pid" != "x" ]; then
+    echo "done."
+    exit 0
+  else
+    echo "failed."
+    exit 1
+  fi
+  ;;
+stop)
+  checkrunning
+  echo -n "Stopping ${servicename}..."
+  if [ $running = 0 ]; then
+    echo "${servicename} is not running."
+    exit 0
+  else
+    for ((i = 0; i < 30; i++)); do
+      kill -0 $pid 2>/dev/null
+      if [ $? != 0 ]; then
+        rm -rf ${pidfile}
         break
       fi
+      kill -9 $pid
       sleep 1
     done
-    if [ "x$pid" != "x" ]; then
-      echo "done."
-      exit 0
-    else
-      echo "failed."
-      exit 1
-    fi
-  ;;
-  stop)
-    checkrunning
-    echo -n "Stopping ${servicename}..."
-    if [ $running = 0 ]; then
-      echo "${servicename} is not running."
-      exit 0
-    else
-      for ((i = 0; i < 30; i++)); do
-        kill -0 $pid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -rf ${pidfile}
-          break
-        fi
-        kill -9 $pid
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
-    fi
-    exit 0
-  ;;
-  restart)
-    $0 stop
-    $0 start
-  ;;
-  reload)
-    checkrunning
-    if [ $running = 1 -a "x$pid" != "x" ]; then
-      echo -n "Reloading ${servicename}..."
-      kill -HUP $pid
-      echo "done."
-    fi
-    
-  ;;
-  status)
-    echo -n "${servicename} is "
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "not running."
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
-  ;;
-  *)
-    echo "$0 start|stop|restart|reload|status"
+  fi
+  if [ -s ${pidfile} ]; then
+    echo "failed."
     exit 1
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
+restart)
+  $0 stop
+  $0 start
+  ;;
+reload)
+  checkrunning
+  if [ $running = 1 -a "x$pid" != "x" ]; then
+    echo -n "Reloading ${servicename}..."
+    kill -HUP $pid
+    echo "done."
+  fi
+
+  ;;
+status)
+  echo -n "${servicename} is "
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "not running."
+    exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+*)
+  echo "$0 start|stop|restart|reload|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmmilterctl b/src/bin/zmmilterctl
--- a/src/bin/zmmilterctl
+++ b/src/bin/zmmilterctl
@@ -1,34 +1,23 @@
 #!/bin/bash
-#
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2010, 2011, 2013, 2014, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-#
 
-source `dirname $0`/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-libjars=/opt/zimbra/lib/jars
-configfile=/opt/zimbra/conf/localconfig.xml
-log4jfile=/opt/zimbra/conf/milter.log4j.properties
+libjars=/opt/zextras/lib/jars
+configfile=/opt/zextras/conf/localconfig.xml
+log4jfile=/opt/zextras/conf/milter.log4j.properties
 pidfile=${zimbra_log_directory}/milter.pid
 pid=""
-java="/opt/zimbra/bin/zmjava"
+java="/opt/zextras/bin/zmjava"
 
-case "`uname`" in
-CYGWIN*) PATHSEP=";";;
-*) PATHSEP=":";;
+case "$(uname)" in
+CYGWIN*) PATHSEP=";" ;;
+*) PATHSEP=":" ;;
 esac
 
 java_version=$(${java} -version 2>&1 | grep "java version" | sed -e 's/"//g' | awk '{print $NF}' | awk -F_ '{print $1}')
@@ -38,23 +27,21 @@ else
   java_options=""
 fi
 
-runcmd="${java} ${java_options} -Dlog4j.configuration=file:${log4jfile} -Dzimbra.home=\"/opt/zimbra\" -Dzimbra.config=\"${configfile}\" \
+runcmd="${java} ${java_options} -Dlog4j.configuration=file:${log4jfile} -Dzimbra.home=\"/opt/zextras\" -Dzimbra.config=\"${configfile}\" \
    com.zimbra.cs.milter.MilterServer"
 
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
   else
-    kill -0 $pid 2> /dev/null
+    kill -0 $pid 2>/dev/null
     if [ $? != 0 ]; then
       pid=""
       running=0
@@ -64,92 +51,91 @@ checkrunning()
   fi
 }
 
-refresh()
-{
-    getpid
+refresh() {
+  getpid
   if [ "x$pid" = "x" ]; then
     echo "milter server is not currently running"
   else
-    kill -CONT $pid 2> /dev/null
+    kill -CONT $pid 2>/dev/null
   fi
 }
 
 case "$1" in
-  start)
-    checkrunning
-    echo -n "Starting milter server..."
-    if [ $running = 1 ]; then
-      echo "milter server is already running."
-      exit 0
-    fi
-
-    nohup sh -c "exec ${runcmd} 2>&1" > /opt/zimbra/log/milter.out 2>&1 &
-
-    pid=$!
-    if [ "x$pid" != 'x' ]; then
-      echo $pid > $pidfile
-    else
-      echo "failed."
-      exit 1
-    fi
-    checkrunning
-    if [ $running = 1 ]; then
-      echo "done."
-      exit 0
-    else
-      echo "failed."
-      exit 1
-    fi
-  ;;
-  stop)
-    checkrunning
-    echo -n "Stopping milter server..."
-    if [ $running = 0 ]; then
-      echo "milter server is not running."
-      exit 0
-    else
-      for ((i = 0; i < 30; i++)); do
-        kill -0 $pid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -rf ${pidfile}
-          break
-        fi
-        kill $pid
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
-    fi
+start)
+  checkrunning
+  echo -n "Starting milter server..."
+  if [ $running = 1 ]; then
+    echo "milter server is already running."
     exit 0
-  ;;
-  restart)
-    $0 stop
-    $0 start
-  ;;
-  reload)
-    $0 stop
-    $0 start
-  ;;
-  refresh)
-    refresh
-  ;;
-  status)
-    echo -n "Milter server is "
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "not running."
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
-  ;;
-  *)
-    echo "$0 start|stop|restart|reload|refresh|status"
+  fi
+
+  nohup sh -c "exec ${runcmd} 2>&1" >/opt/zextras/log/milter.out 2>&1 &
+
+  pid=$!
+  if [ "x$pid" != 'x' ]; then
+    echo $pid >$pidfile
+  else
+    echo "failed."
     exit 1
+  fi
+  checkrunning
+  if [ $running = 1 ]; then
+    echo "done."
+    exit 0
+  else
+    echo "failed."
+    exit 1
+  fi
+  ;;
+stop)
+  checkrunning
+  echo -n "Stopping milter server..."
+  if [ $running = 0 ]; then
+    echo "milter server is not running."
+    exit 0
+  else
+    for ((i = 0; i < 30; i++)); do
+      kill -0 $pid 2>/dev/null
+      if [ $? != 0 ]; then
+        rm -rf ${pidfile}
+        break
+      fi
+      kill $pid
+      sleep 1
+    done
+  fi
+  if [ -s ${pidfile} ]; then
+    echo "failed."
+    exit 1
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
+restart)
+  $0 stop
+  $0 start
+  ;;
+reload)
+  $0 stop
+  $0 start
+  ;;
+refresh)
+  refresh
+  ;;
+status)
+  echo -n "Milter server is "
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "not running."
+    exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+*)
+  echo "$0 start|stop|restart|reload|refresh|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmmtactl b/src/bin/zmmtactl
--- a/src/bin/zmmtactl
+++ b/src/bin/zmmtactl
@@ -1,104 +1,94 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
+
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 #
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
-source `dirname $0`/zmshutil || exit 1
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-BASE=/opt/zimbra
+BASE=/opt/zextras
 
-if [ ! -x /opt/zimbra/common/sbin/postfix ]; then
-  echo "Error: postfix not installed"
-  exit 1
+if [ ! -x /opt/zextras/common/sbin/postfix ]; then
+	echo "Error: postfix not installed"
+	exit 1
 fi
 
-if [ -f "/opt/zimbra/conf/mta_milter_options" ]; then
-  source /opt/zimbra/conf/mta_milter_options
+if [ -f "/opt/zextras/conf/mta_milter_options" ]; then
+	source /opt/zextras/conf/mta_milter_options
 fi
 zimbraMilterServerEnabled=${zimbraMilterServerEnabled:=FALSE}
 
 if [ x"$zimbraMilterServerEnabled" = "xTRUE" ]; then
-  START_SCRIPTS="zmmilterctl zmsaslauthdctl postfix"
-  STOP_SCRIPTS="postfix zmsaslauthdctl zmmilterctl"
-else 
-  START_SCRIPTS="zmsaslauthdctl postfix"
-  STOP_SCRIPTS="postfix zmsaslauthdctl"
+	START_SCRIPTS="zmmilterctl zmsaslauthdctl postfix"
+	STOP_SCRIPTS="postfix zmsaslauthdctl zmmilterctl"
+else
+	START_SCRIPTS="zmsaslauthdctl postfix"
+	STOP_SCRIPTS="postfix zmsaslauthdctl"
 fi
 
 rewriteconfig() {
-  echo -n "Rewriting configuration files..."
-  if [ ! -f /opt/zimbra/common/conf/main.cf ]; then
-    touch /opt/zimbra/common/conf/main.cf
-    /opt/zimbra/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
-  fi
-  /opt/zimbra/libexec/configrewrite antispam antivirus opendkim mta sasl  > /dev/null 2>&1
-  if [ $? = 0 ]; then
-    echo "done."
-  else
-    echo "failed."
-  fi
+	echo -n "Rewriting configuration files..."
+	if [ ! -f /opt/zextras/common/conf/main.cf ]; then
+		touch /opt/zextras/common/conf/main.cf
+		/opt/zextras/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
+	fi
+	/opt/zextras/libexec/configrewrite antispam antivirus opendkim mta sasl >/dev/null 2>&1
+	if [ $? = 0 ]; then
+		echo "done."
+	else
+		echo "failed."
+	fi
 }
 
-case "$1" in 
-	start)
-		if [ x$2 = "x" ]; then
-			rewriteconfig
+case "$1" in
+start)
+	if [ x$2 = "x" ]; then
+		rewriteconfig
+	fi
+	STATUS=0
+	for i in $START_SCRIPTS; do
+		/opt/zextras/bin/$i start norewrite
+		R=$?
+		if [ $R -ne "0" ]; then
+			echo "$i failed to start"
+			STATUS=$R
 		fi
-		STATUS=0
-		for i in $START_SCRIPTS; do
-			/opt/zimbra/bin/$i start norewrite
-			R=$?
-			if [ $R -ne "0" ]; then
-				echo "$i failed to start"
-				STATUS=$R
-			fi
-		done
-		exit $STATUS
+	done
+	exit $STATUS
 	;;
-	stop)
-		for i in $STOP_SCRIPTS; do
-			/opt/zimbra/bin/$i stop
-		done
+stop)
+	for i in $STOP_SCRIPTS; do
+		/opt/zextras/bin/$i stop
+	done
 	;;
-	reload|restart)
+reload | restart)
+	if [ x$2 = "x" ]; then
+		rewriteconfig
+	fi
+	for i in $START_SCRIPTS; do
 		if [ x$2 = "x" ]; then
-			rewriteconfig
+			/opt/zextras/bin/$i reload
+		else
+			/opt/zextras/bin/$i reload $2
 		fi
-		for i in $START_SCRIPTS; do
-			if [ x$2 = "x" ]; then
-				/opt/zimbra/bin/$i reload
-			else
-				/opt/zimbra/bin/$i reload $2
-			fi
-		done
+	done
 	;;
-	status)
-		STATUS=0
-		for i in $START_SCRIPTS; do
-			/opt/zimbra/bin/$i status > /dev/null 2>&1
-			R=$?
-			if [ $R -ne "0" ]; then
-				echo "$i is not running"
-				STATUS=$R
-			fi
-		done
-		exit $STATUS
+status)
+	STATUS=0
+	for i in $START_SCRIPTS; do
+		/opt/zextras/bin/$i status >/dev/null 2>&1
+		R=$?
+		if [ $R -ne "0" ]; then
+			echo "$i is not running"
+			STATUS=$R
+		fi
+	done
+	exit $STATUS
 	;;
-	*)
-		echo "$0 start|stop|restart|reload|status"
-		exit 1
+*)
+	echo "$0 start|stop|restart|reload|status"
+	exit 1
 	;;
 esac
diff --git a/src/bin/zmmypasswd b/src/bin/zmmypasswd
--- a/src/bin/zmmypasswd
+++ b/src/bin/zmmypasswd
@@ -1,33 +1,18 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
+
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 #
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
-#
-# Change password for zimbra_mysql_password, and optionally for
-# mysql_root_password.  Updates both the Zimbra local config file and
-# MySQL.
-#
-source `dirname $0`/zmshutil || exit 1
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 #
 # Usage.
 #
 usage() {
-    cat<<EOF
+  cat <<EOF
 Usage: $ zmmypasswd [ --root ] newpassword
 
 By default, this script changes zimbra_myql_password.  If the --root
@@ -45,71 +30,71 @@ EOF
 # Parse command line
 #
 if [ "x$1" = "x-h" -o "x$1" = "x--help" ]; then
-	usage
-	exit 0
+  usage
+  exit 0
 fi
 
 if [ "x$1" = "x--root" ]; then
-    password_key="mysql_root_password"
-    shift # lose --root option
+  password_key="mysql_root_password"
+  shift # lose --root option
 else
-    password_key="zimbra_mysql_password"
+  password_key="zimbra_mysql_password"
 fi
 
 if [ $# -ne 1 ]; then
-    usage
-    exit 1
+  usage
+  exit 1
 fi
 newpassword="$1"
 
 #
 # For zimbra_mysql_password
 #
-if [ ${password_key} = zimbra_mysql_password ]; then 
-    # Change the password in mysql.
-    cat <<EOF | /opt/zimbra/bin/mysql -u root --password="${mysql_root_password}"
+if [ ${password_key} = zimbra_mysql_password ]; then
+  # Change the password in mysql.
+  cat <<EOF | /opt/zextras/bin/mysql -u root --password="${mysql_root_password}"
 SET PASSWORD FOR '${zimbra_mysql_user}' = PASSWORD('${newpassword}');
 SET PASSWORD FOR '${zimbra_mysql_user}'@'localhost' = PASSWORD('${newpassword}');
 SET PASSWORD FOR '${zimbra_mysql_user}'@'localhost.localdomain' = PASSWORD('${newpassword}');
 EOF
-    if [ $? = 0 ]; then
-        echo '*' Changed zimbra mysql user password
-    else
-        echo '****' PASSWORD CHANGE FAILED
-        exit 1
-    fi
+  if [ $? = 0 ]; then
+    echo '*' Changed zextras mysql user password
+  else
+    echo '****' PASSWORD CHANGE FAILED
+    exit 1
+  fi
 fi
 
 #
 # For mysql_root_password
 #
 if [ ${password_key} = mysql_root_password ]; then
-    echo /opt/zimbra/bin/mysqladmin -u root --password="${mysql_root_password}" password "${newpassword}"
-    /opt/zimbra/bin/mysqladmin -u root --password="${mysql_root_password}" password "${newpassword}"
-    if [ $? = 0 ]; then
-        echo '*' Changed mysql root user password
-    else
-        echo '****' PASSWORD CHANGE FAILED
-        exit 1
-    fi
-    # Change for localhost socket clients also - useful for dev.
-    cat <<EOF | /opt/zimbra/bin/mysql -u root --password="${newpassword}"
+  echo /opt/zextras/bin/mysqladmin -u root --password="${mysql_root_password}" password "${newpassword}"
+  /opt/zextras/bin/mysqladmin -u root --password="${mysql_root_password}" password "${newpassword}"
+  if [ $? = 0 ]; then
+    echo '*' Changed mysql root user password
+  else
+    echo '****' PASSWORD CHANGE FAILED
+    exit 1
+  fi
+  # Change for localhost socket clients also - useful for dev.
+  cat <<EOF | /opt/zextras/bin/mysql -u root --password="${newpassword}"
 SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${newpassword}');
 SET PASSWORD FOR 'root'@'localhost.localdomain' = PASSWORD('${newpassword}');
 EOF
-    if [ $? = 0 ]; then
-        echo '*' Changed mysql root user password root@localhost
-    else
-        echo '****' PASSWORD CHANGE FAILED FOR root@localhost
-        exit 1
-    fi
+  if [ $? = 0 ]; then
+    echo '*' Changed mysql root user password root@localhost
+  else
+    echo '****' PASSWORD CHANGE FAILED FOR root@localhost
+    exit 1
+  fi
 fi
 
 #
 # Change the password in local config.  TODO: notify app server that
 # the password has changed, for now you will have to restart mailboxd
 #
-if ! /opt/zimbra/bin/zmlocalconfig -f -e "${password_key}=${newpassword}"; then
-    echo Error: command failed: /opt/zimbra/bin/zmlocalconfig -f -e ${password_key}='#'
-    exit 1
+if ! /opt/zextras/bin/zmlocalconfig -f -e "${password_key}=${newpassword}"; then
+  echo Error: command failed: /opt/zextras/bin/zmlocalconfig -f -e ${password_key}='#'
+  exit 1
 fi
diff --git a/src/bin/zmopendkimctl b/src/bin/zmopendkimctl
--- a/src/bin/zmopendkimctl
+++ b/src/bin/zmopendkimctl
@@ -1,52 +1,38 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-  echo Error: must be run as zimbra user
-  exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+        echo Error: must be run as zextras user
+        exit 1
 fi
 
-if [ ! -x "/opt/zimbra/common/sbin/opendkim" ]; then
-  exit 0
+if [ ! -x "/opt/zextras/common/sbin/opendkim" ]; then
+        exit 0
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 PID=""
 PIDFILE=${zimbra_log_directory}/opendkim.pid
-odk=/opt/zimbra/common/sbin/opendkim
-config=/opt/zimbra/conf/opendkim.conf
+odk=/opt/zextras/common/sbin/opendkim
+config=/opt/zextras/conf/opendkim.conf
 
 rewriteconfig() {
-    /opt/zimbra/libexec/configrewrite opendkim > /dev/null 2>&1
+        /opt/zextras/libexec/configrewrite opendkim >/dev/null 2>&1
 }
 
-getpid()
-{
+getpid() {
         if [ -f $PIDFILE ]; then
-                PID=`cat $PIDFILE`
+                PID=$(cat $PIDFILE)
         fi
 }
 
-
-checkrunning()
-{
+checkrunning() {
         getpid
         if [ "x$PID" = "x" ]; then
                 RUNNING=0
@@ -60,57 +46,54 @@ checkrunning()
         fi
 }
 
-start()
-{
+start() {
         checkrunning
         if [ $RUNNING = 0 ]; then
-          if [ x$1 = "x" ]; then
-            rewriteconfig
-          fi
-          $odk -x $config -u zimbra
-          if [ $? != 0 ]; then
-            echo "Failed to start opendkim: $?"
-            exit 1
-          fi
-          sleep 2
-          getpid
-          echo "Started opendkim: pid $PID"
+                if [ x$1 = "x" ]; then
+                        rewriteconfig
+                fi
+                $odk -x $config -u zextras
+                if [ $? != 0 ]; then
+                        echo "Failed to start opendkim: $?"
+                        exit 1
+                fi
+                sleep 2
+                getpid
+                echo "Started opendkim: pid $PID"
         else
-          echo "zmopendkimctl already running: pid $PID"
-          exit 0
+                echo "zmopendkimctl already running: pid $PID"
+                exit 0
         fi
 }
 
-stop()
-{
+stop() {
         checkrunning
         if [ $RUNNING = 0 ]; then
-          echo "zmopendkimctl not running"
-          exit 0
+                echo "zmopendkimctl not running"
+                exit 0
         else
-          echo -n "Stopping opendkim..."
-          kill -TERM $PID 2> /dev/null
-          for ((i=0; i < 300; i++)); do
-            sleep 5
-            kill -0 $PID 2> /dev/null
-            if [ $? != 0 ]; then
-              echo " done."
-              exit 0
-            fi
-          done
-          kill -TERM $PID 2> /dev/null
-          if [ $? = 0 ]; then
-            echo " failed to stop $PID"
-            exit 1
-          else
-            echo " done."
-          fi
+                echo -n "Stopping opendkim..."
+                kill -TERM $PID 2>/dev/null
+                for ((i = 0; i < 300; i++)); do
+                        sleep 5
+                        kill -0 $PID 2>/dev/null
+                        if [ $? != 0 ]; then
+                                echo " done."
+                                exit 0
+                        fi
+                done
+                kill -TERM $PID 2>/dev/null
+                if [ $? = 0 ]; then
+                        echo " failed to stop $PID"
+                        exit 1
+                else
+                        echo " done."
+                fi
         fi
         exit 0
 }
 
-status()
-{
+status() {
         checkrunning
         echo -n "zmopendkimctl is "
         if [ $RUNNING = 0 ]; then
@@ -123,21 +106,21 @@ status()
 }
 
 case "$1" in
-        reload|restart)
-                $0 stop
-                $0 start $2
-                ;;
-        start)
-                start $2
-                ;;
-        stop)
-                stop
-                ;;
-        status)
-                status
-                ;;
-        *)
-                echo "Usage: $0 start|stop|restart|reload|status"
-                exit 1
-                ;;
+reload | restart)
+        $0 stop
+        $0 start $2
+        ;;
+start)
+        start $2
+        ;;
+stop)
+        stop
+        ;;
+status)
+        status
+        ;;
+*)
+        echo "Usage: $0 start|stop|restart|reload|status"
+        exit 1
+        ;;
 esac
diff --git a/src/bin/zmplayredo b/src/bin/zmplayredo
--- a/src/bin/zmplayredo
+++ b/src/bin/zmplayredo
@@ -1,110 +1,99 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2008, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source `dirname $0`/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-u=`id -un`
+u=$(id -un)
 if [ $u != ${zimbra_user} ]; then
-    echo "Error: must be run as ${zimbra_user} user"
-    exit 1
+  echo "Error: must be run as ${zimbra_user} user"
+  exit 1
 fi
 
 isrunning() {
-    zmmailboxdctl status 2> /dev/null
-    return
+  zmmailboxdctl status 2>/dev/null
+  return
 }
 
 opth=0
-for opt in $@; do 
-    if [ $opt = "-h" -o $opt = "--help" ]; then
-        opth=1
-        break
-    fi
+for opt in $@; do
+  if [ $opt = "-h" -o $opt = "--help" ]; then
+    opth=1
+    break
+  fi
 done
 
 ropid=${zimbra_log_directory}/zmplayredo.pid
 
 if [ $opth -eq 0 ]; then
-    if isrunning; then
-        echo "Error: mailboxd still running.  Stop mailboxd before running zmplayredo."
-        exit 1
-    fi
-    if [ -s $ropid ]; then
-        echo "Error: another instance of zmplayredo (pid=`cat $ropid`) is already running"
-        echo "       remove $ropid if this is not the case"
-        exit 1
-    fi
+  if isrunning; then
+    echo "Error: mailboxd still running.  Stop mailboxd before running zmplayredo."
+    exit 1
+  fi
+  if [ -s $ropid ]; then
+    echo "Error: another instance of zmplayredo (pid=$(cat $ropid)) is already running"
+    echo "       remove $ropid if this is not the case"
+    exit 1
+  fi
 fi
 
 if [ -d ${zimbra_java_home}/jre ]; then
-    JRE_EXT_DIR=${zimbra_java_home}/jre/lib/ext
+  JRE_EXT_DIR=${zimbra_java_home}/jre/lib/ext
 else
-    JRE_EXT_DIR=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/lib/ext
-    #JRE_EXT_DIR=${zimbra_java_home}/lib/ext
+  JRE_EXT_DIR=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/lib/ext
+  #JRE_EXT_DIR=${zimbra_java_home}/lib/ext
 fi
 
-jardirs=${JRE_EXT_DIR}:/opt/zimbra/mailboxd/lib/*:/opt/zimbra/mailboxd/common/lib/*:/opt/zimbra/lib/jars/*
-if [ -e /opt/zimbra/lib/ext-common ]; then
-    jardirs=${jardirs}:/opt/zimbra/lib/ext-common/*
+jardirs=${JRE_EXT_DIR}:/opt/zextras/mailboxd/lib/*:/opt/zextras/mailboxd/common/lib/*:/opt/zextras/lib/jars/*
+if [ -e /opt/zextras/lib/ext-common ]; then
+  jardirs=${jardirs}:/opt/zextras/lib/ext-common/*
 fi
-for jd in `find /opt/zimbra/lib/ext -type d` ; do
-    if [ ${jd} != /opt/zimbra/lib/ext ]; then
-        jardirs="${jardirs}:${jd}/*"
-    fi
+for jd in $(find /opt/zextras/lib/ext -type d); do
+  if [ ${jd} != /opt/zextras/lib/ext ]; then
+    jardirs="${jardirs}:${jd}/*"
+  fi
 done
 
-jardirs="${jardirs}:/opt/zimbra/jetty/common/lib/*:/opt/zimbra/jetty/webapps/service/WEB-INF/lib/*"
+jardirs="${jardirs}:/opt/zextras/jetty/common/lib/*:/opt/zextras/jetty/webapps/service/WEB-INF/lib/*"
 #
 # Memory for use by JVM
 #
 jm=${mailboxd_java_heap_size}
-if [ -n "$jm" ] ; then
-    xms_xmx_options="-Xms${jm}m -Xmx${jm}m"
+if [ -n "$jm" ]; then
+  xms_xmx_options="-Xms${jm}m -Xmx${jm}m"
 fi
 
 java_version=$(${zimbra_java_home}/bin/java -version 2>&1 | grep "java version" | sed -e 's/"//g' | awk '{print $NF}' | awk -F_ '{print $1}')
 if [ x"$java_version" = "x1.6.0" ]; then
-  java_options="-XX:ErrorFile=/opt/zimbra/log"
+  java_options="-XX:ErrorFile=/opt/zextras/log"
 else
   java_options=""
 fi
 
 # Remove "-verbose:gc" and all options that start with "-XX:+PrintGC".  These pollute stdout/stderr.
-for opt in $mailboxd_java_options ; do
-    if [ "$opt" = "-verbose:gc" ] || [[ "$opt" == "-XX:+PrintGC"* ]] ; then
-        continue
-    fi
-    if [ -z "$sanitized_options" ] ; then
-      sanitized_options="$opt"
-    else
-      sanitized_options="$sanitized_options $opt"
-    fi
+for opt in $mailboxd_java_options; do
+  if [ "$opt" = "-verbose:gc" ] || [[ "$opt" == "-XX:+PrintGC"* ]]; then
+    continue
+  fi
+  if [ -z "$sanitized_options" ]; then
+    sanitized_options="$opt"
+  else
+    sanitized_options="$sanitized_options $opt"
+  fi
 done
 
-echo $$ > $ropid
+echo $$ >$ropid
 ${zimbra_java_home}/bin/java \
-    ${java_options} \
-    ${xms_xmx_options} ${sanitized_options} \
-    -Dzimbra.config=/opt/zimbra/conf/localconfig.xml \
-    -Djava.library.path=/opt/zimbra/lib \
-    -classpath ${jardirs} \
-    com.zimbra.cs.redolog.util.PlaybackUtil "$@"
+  ${java_options} \
+  ${xms_xmx_options} ${sanitized_options} \
+  -Dzimbra.config=/opt/zextras/conf/localconfig.xml \
+  -Djava.library.path=/opt/zextras/lib \
+  -classpath ${jardirs} \
+  com.zimbra.cs.redolog.util.PlaybackUtil "$@"
 rc=$?
 rm -f $ropid
 exit $rc
diff --git a/src/bin/zmproxyctl b/src/bin/zmproxyctl
--- a/src/bin/zmproxyctl
+++ b/src/bin/zmproxyctl
@@ -1,43 +1,30 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2007, 2008, 2009, 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-    echo "Error: must be run as zimbra user"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo "Error: must be run as zextras user"
   exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 servicename=proxy
-configfile=/opt/zimbra/conf/nginx.conf
+configfile=/opt/zextras/conf/nginx.conf
 pidfile=${zimbra_log_directory}/nginx.pid
 pid=""
 
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
@@ -51,107 +38,107 @@ checkrunning()
   fi
 }
 
-case "$1" in 
-  start)
-    if [ ! -x /opt/zimbra/common/sbin/nginx ]; then
-      echo "Error: nginx not installed"
-      exit 1
-    fi
+case "$1" in
+start)
+  if [ ! -x /opt/zextras/common/sbin/nginx ]; then
+    echo "Error: nginx not installed"
+    exit 1
+  fi
 
+  checkrunning
+  echo -n "Starting ${servicename}..."
+  if [ $running = 1 ]; then
+    echo "${servicename} is already running."
+    exit 0
+  fi
+  if [ "x$2" = "x" ]; then
+    /opt/zextras/libexec/configrewrite proxy >/dev/null 2>&1
+  fi
+
+  if [ ! -f ${configfile} ]; then
+    echo "failed.  ${configfile} is missing."
+    exit 1
+  fi
+
+  # read the last line of nginx.conf which indicates the conf gen result
+  res=$(tail -n 1 ${configfile})
+  warn=''
+
+  if ! [[ $res =~ __SUCCESS__ ]]; then
+    msg=$(echo $res | awk -F ':' '{print $2}')
+    if [ x"$msg" = "x" ]; then msg="unknown"; fi
+    if ! [[ $res =~ "No available nginx lookup handlers could be contacted" ]]; then
+      echo "failed."
+      echo "nginx start failed. reason: $msg"
+      exit 1
+    else
+      warn=$msg
+    fi
+  fi
+
+  sudo /opt/zextras/common/sbin/nginx -c ${configfile}
+  for ((i = 0; i < 30; i++)); do
     checkrunning
-    echo -n "Starting ${servicename}..."
     if [ $running = 1 ]; then
-      echo "${servicename} is already running."
-      exit 0
+      break
     fi
-    if [ "x$2" = "x" ]; then
-      /opt/zimbra/libexec/configrewrite proxy > /dev/null 2>&1
-    fi
-
-    if [ ! -f ${configfile} ]; then
-      echo "failed.  ${configfile} is missing."
-      exit 1
-    fi
-
-    # read the last line of nginx.conf which indicates the conf gen result
-    res=`tail -n 1 ${configfile}`
-    warn=''
-
-    if ! [[ $res =~ __SUCCESS__ ]]; then
-      msg=`echo $res | awk -F ':' '{print $2}'`
-      if [ x"$msg" = "x" ]; then msg="unknown"; fi
-      if ! [[ $res =~ "No available nginx lookup handlers could be contacted" ]]; then
-        echo "failed."
-        echo "nginx start failed. reason: $msg"
-        exit 1
-      else
-        warn=$msg
-      fi
-    fi
-
-    sudo /opt/zimbra/common/sbin/nginx -c ${configfile}
-    for ((i=0; i < 30; i++)); do
-      checkrunning
-      if [ $running = 1 ]; then
-        break
-      fi
-      sleep 1
-    done
-    if [ "x$pid" != "x" ]; then
-      echo "done."
-      if [ x"$warn" != "x" ]; then
-        echo "Warning: $warn"
-      fi
-      exit 0
-    else
-      echo "failed."
-      exit 1
-    fi
-  ;;
-  stop)
-    checkrunning
-    echo -n "Stopping ${servicename}..."
-    if [ $running = 0 ]; then
-      echo "${servicename} is not running."
-      exit 0
-    else
-      sudo /opt/zimbra/common/sbin/nginx -c /opt/zimbra/conf/nginx.conf -s stop
-      sleep 1
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
+    sleep 1
+  done
+  if [ "x$pid" != "x" ]; then
+    echo "done."
+    if [ x"$warn" != "x" ]; then
+      echo "Warning: $warn"
     fi
     exit 0
-  ;;
-  restart)
-    $0 stop
-    $0 start $2
-  ;;
-  reload)
-    checkrunning
-    if [ $running = 1 -a "x$pid" != "x" ]; then
-      echo -n "Reloading ${servicename}..."
-      sudo /opt/zimbra/common/sbin/nginx -c /opt/zimbra/conf/nginx.conf -s reload
-      echo "done."
-    fi
-    
-  ;;
-  status)
-    echo -n "${servicename} is "
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "not running."
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
-  ;;
-  *)
-    echo "$0 start|stop|restart|reload|status"
+  else
+    echo "failed."
     exit 1
+  fi
+  ;;
+stop)
+  checkrunning
+  echo -n "Stopping ${servicename}..."
+  if [ $running = 0 ]; then
+    echo "${servicename} is not running."
+    exit 0
+  else
+    sudo /opt/zextras/common/sbin/nginx -c /opt/zextras/conf/nginx.conf -s stop
+    sleep 1
+  fi
+  if [ -s ${pidfile} ]; then
+    echo "failed."
+    exit 1
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
+restart)
+  $0 stop
+  $0 start $2
+  ;;
+reload)
+  checkrunning
+  if [ $running = 1 -a "x$pid" != "x" ]; then
+    echo -n "Reloading ${servicename}..."
+    sudo /opt/zextras/common/sbin/nginx -c /opt/zextras/conf/nginx.conf -s reload
+    echo "done."
+  fi
+
+  ;;
+status)
+  echo -n "${servicename} is "
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "not running."
+    exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+*)
+  echo "$0 start|stop|restart|reload|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmsaslauthdctl b/src/bin/zmsaslauthdctl
--- a/src/bin/zmsaslauthdctl
+++ b/src/bin/zmsaslauthdctl
@@ -1,46 +1,32 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
 pid=""
-pidfile="/opt/zimbra/data/sasl2/state/saslauthd.pid"
+pidfile="/opt/zextras/data/sasl2/state/saslauthd.pid"
 
 rewriteconfig() {
-  /opt/zimbra/libexec/configrewrite sasl > /dev/null 2>&1
+  /opt/zextras/libexec/configrewrite sasl >/dev/null 2>&1
 }
 
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
@@ -58,73 +44,73 @@ checkrunning()
 # Main
 #
 case "$1" in
-  'start')
+'start')
+  checkrunning
+  echo -n "Starting saslauthd..."
+  if [ $running = 1 ]; then
+    echo "already running."
+    exit 0
+  fi
+  mkdir -p /opt/zextras/data/sasl2/state
+  if [ x$2 = "x" ]; then
+    rewriteconfig
+  fi
+  /opt/zextras/common/sbin/saslauthd -r -a zimbra
+  for ((i = 0; i < 30; i++)); do
     checkrunning
-    echo -n "Starting saslauthd..."
     if [ $running = 1 ]; then
-      echo "already running."
+      echo "done."
       exit 0
     fi
-    mkdir -p /opt/zimbra/data/sasl2/state
-    if [ x$2 = "x" ]; then
-      rewriteconfig
-    fi
-    /opt/zimbra/common/sbin/saslauthd -r -a zimbra 
-    for ((i = 0; i < 30; i++)) do
-      checkrunning
-      if [ $running = 1 ]; then
-        echo "done."
-        exit 0
+    sleep 1
+  done
+  echo "failed."
+  exit 1
+  ;;
+
+'kill' | 'stop')
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "saslauthd is not running."
+    exit 0
+  else
+    echo -n "Stopping saslauthd..."
+    for ((i = 0; i < 30; i++)); do
+      kill -0 $pid 2>/dev/null
+      if [ $? != 0 ]; then
+        rm -rf ${pidfile}
+        break
       fi
+      kill $pid
       sleep 1
     done
-    echo "failed."
+  fi
+  if [ -s ${pidfile} ]; then
     exit 1
-    ;;
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
 
-  'kill'|'stop')
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "saslauthd is not running."
-      exit 0
-    else
-      echo -n "Stopping saslauthd..."
-      for ((i = 0; i < 30; i++)); do
-        kill -0 $pid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -rf ${pidfile}
-          break
-        fi
-        kill $pid
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      exit 1
-    else
-      echo "done."
-    fi
+'restart' | 'reload')
+  $0 stop
+  $0 start $2
+  ;;
+
+'status')
+  checkrunning
+  if [ $running = 1 ]; then
+    echo "saslauthd is running."
     exit 0
-    ;;
+  else
+    echo "saslauthd is not running."
+    exit 1
+  fi
+  ;;
 
-  'restart'|'reload')
-    $0 stop
-    $0 start $2
-    ;;
-  
-  'status')
-    checkrunning
-    if [ $running = 1 ]; then
-      echo "saslauthd is running."
-      exit 0
-    else 
-      echo "saslauthd is not running."
-      exit 1
-    fi
-    ;;
-    
-    *)
-        echo "Usage: $0 start|stop|kill|restart|reload|status"
-        exit 1
-        ;;
+*)
+  echo "Usage: $0 start|stop|kill|restart|reload|status"
+  exit 1
+  ;;
 esac
diff --git a/src/bin/zmshutil b/src/bin/zmshutil
--- a/src/bin/zmshutil
+++ b/src/bin/zmshutil
@@ -1,72 +1,55 @@
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2013, 2014, 2016 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 #
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
-#
-# zmshutil is meant to be sourced by other scripts.  If run
-# it will do nothing.  It will complain if it can't find
-# local config program.
-#
+# SPDX-License-Identifier: GPL-2.0-only
 
 #
 # Find and set local config variables.
 #
 zmsetvars() {
-    if [ "x$1" = "x-f" ]; then
-        shift;
-    else
-        if [ x${zmsetvars} = "xtrue" ]; then
-            return
-        fi
+  if [ "x$1" = "x-f" ]; then
+    shift
+  else
+    if [ x${zmsetvars} = "xtrue" ]; then
+      return
     fi
-    
-    zmlocalconfig="/opt/zimbra/bin/zmlocalconfig"
-    if [ ! -x "${zmlocalconfig}" ]; then 
-        echo Error: can not find zmlocalconfig program
-        exit 1
-    fi
-    
-    if ! eval `${zmlocalconfig} -q -m export`; then
-        echo Error: executing: ${zmlocalconfig} -q -m export
-        exit 1
-    fi
-    
-    export zmsetvars='true'
+  fi
+
+  zmlocalconfig="/opt/zextras/bin/zmlocalconfig"
+  if [ ! -x "${zmlocalconfig}" ]; then
+    echo Error: can not find zmlocalconfig program
+    exit 1
+  fi
+
+  if ! eval $(${zmlocalconfig} -q -m export); then
+    echo Error: executing: ${zmlocalconfig} -q -m export
+    exit 1
+  fi
+
+  export zmsetvars='true'
 }
 
 #
 # Check if a conditional expression is true.
 #
-zmassert() { 
-    if [ $@ ]; then
-    	return;
-    fi
-    echo Error: assertion "'$@'" failed && exit 1
+zmassert() {
+  if [ $@ ]; then
+    return
+  fi
+  echo Error: assertion "'$@'" failed && exit 1
 }
 
 #
 # Get available system memory in KB.
 #
 zmsysmemkb() {
-    if [ -f /proc/meminfo ]; then
-        memkb=`awk '/^MemTotal.*kB$/ { print $2; }' /proc/meminfo`
-    else
-        memkb=$(/usr/sbin/sysctl hw.memsize 2>/dev/null | awk -F: '{ print $2 / 1024; }');
-    fi
-    if ! echo $memkb | grep '^[0-9]*$' > /dev/null; then
-        memkb=524288
-    fi
-    echo $memkb
+  if [ -f /proc/meminfo ]; then
+    memkb=$(awk '/^MemTotal.*kB$/ { print $2; }' /proc/meminfo)
+  else
+    memkb=$(/usr/sbin/sysctl hw.memsize 2>/dev/null | awk -F: '{ print $2 / 1024; }')
+  fi
+  if ! echo $memkb | grep '^[0-9]*$' >/dev/null; then
+    memkb=524288
+  fi
+  echo $memkb
 }
diff --git a/src/bin/zmsshkeygen b/src/bin/zmsshkeygen
--- a/src/bin/zmsshkeygen
+++ b/src/bin/zmsshkeygen
@@ -1,58 +1,47 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source `dirname $0`/../bin/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/../bin/zmshutil || exit 1
 zmsetvars
 
 keyattr="zimbraSshPublicKey"
 
-zmprov="/opt/zimbra/bin/zmprov -m -l"
+zmprov="/opt/zextras/bin/zmprov -m -l"
 
-keyfile="/opt/zimbra/.ssh/zimbra_identity"
+keyfile="/opt/zextras/.ssh/zimbra_identity"
 
-mkdir -p /opt/zimbra/.ssh
+mkdir -p /opt/zextras/.ssh
 
-if [ ! -d "/opt/zimbra/.ssh" ]; then
-  echo "Unable to create /opt/zimbra/.ssh."
+if [ ! -d "/opt/zextras/.ssh" ]; then
+  echo "Unable to create /opt/zextras/.ssh."
   exit 1
 fi
 
-chmod 700 /opt/zimbra/.ssh
+chmod 700 /opt/zextras/.ssh
 
 rm -f ${keyfile}
 
 keytype=${1:-rsa}
 
 if [ $keytype != "rsa" ]; then
-	echo "Bad keytype: $keytype"
-	echo ""
-	exit 1
+  echo "Bad keytype: $keytype"
+  echo ""
+  exit 1
 fi
 
 ssh-keygen -f ${keyfile} -b 2048 -N '' \
-	-t ${keytype} -C ${zimbra_server_hostname}
+  -t ${keytype} -C ${zimbra_server_hostname}
 
 # Starting with OpenSSH 7.8 by default, the key is created with the OpenSSH private key format instead of the OpenSSL PEM format.
 # Check the format of KEY and convert to OpenSSL PEM format.
-grep "BEGIN OPENSSH PRIVATE KEY" ${keyfile} > /dev/null 2>&1
-  if [ $? = 0 ]; then
-     ssh-keygen -p -m PEM -f ${keyfile}  -b 2048 -N '' -t ${keytype} -C ${zimbra_server_hostname}
-  fi
-pubkey=`cat ${keyfile}.pub`
+grep "BEGIN OPENSSH PRIVATE KEY" ${keyfile} >/dev/null 2>&1
+if [ $? = 0 ]; then
+  ssh-keygen -p -m PEM -f ${keyfile} -b 2048 -N '' -t ${keytype} -C ${zimbra_server_hostname}
+fi
+pubkey=$(cat ${keyfile}.pub)
 
 ${zmprov} ms ${zimbra_server_hostname} ${keyattr} "${pubkey}"
diff --git a/src/bin/zmstat-chart b/src/bin/zmstat-chart
--- a/src/bin/zmstat-chart
+++ b/src/bin/zmstat-chart
@@ -1,62 +1,51 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2007, 2008, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source `dirname $0`/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-u=`id -un`
+u=$(id -un)
 if [ $u != ${zimbra_user} ]; then
-    echo "Error: must be run as ${zimbra_user} user"
-    exit 1
+  echo "Error: must be run as ${zimbra_user} user"
+  exit 1
 fi
 
 optConf=0
-for opt in $@; do 
-    if [ $opt = "-c" -o $opt = "--conf" ]; then
-        optConf=1
-        break
-    fi
+for opt in $@; do
+  if [ $opt = "-c" -o $opt = "--conf" ]; then
+    optConf=1
+    break
+  fi
 done
 
 if [ $optConf -eq 1 ]; then
-    # If --conf option was given, use it.
-    exec zmjava -Djava.awt.headless=true com.zimbra.perf.chart.ChartUtil "$@"
+  # If --conf option was given, use it.
+  exec zmjava -Djava.awt.headless=true com.zimbra.perf.chart.ChartUtil "$@"
 else
-    # If no --conf option, look for /opt/zimbra/conf/zmstat-chart.xml and
-    # generated one if necessary.
-    conf=/opt/zimbra/conf/zmstat-chart.xml
-    confTmp=$conf.$$.tmp
-    CONF_TIME=0
-    CONFGEN_TIME=`stat -c %Z /opt/zimbra/bin/zmstat-chart-config`
-    if [ -f $conf ]; then
-        CONF_TIME=`stat -c %Z $conf`
+  # If no --conf option, look for /opt/zextras/conf/zmstat-chart.xml and
+  # generated one if necessary.
+  conf=/opt/zextras/conf/zmstat-chart.xml
+  confTmp=$conf.$$.tmp
+  CONF_TIME=0
+  CONFGEN_TIME=$(stat -c %Z /opt/zextras/bin/zmstat-chart-config)
+  if [ -f $conf ]; then
+    CONF_TIME=$(stat -c %Z $conf)
+  fi
+  if [ $CONFGEN_TIME -gt $CONF_TIME ]; then
+    zmstat-chart-config >$confTmp
+    rc=$?
+    if [ $rc -ne 0 ]; then
+      echo "Unable to generate chart configuration file $conf"
+      if [ -e $confTmp ]; then
+        rm -f $confTmp
+      fi
+      exit $rc
     fi
-    if [ $CONFGEN_TIME -gt $CONF_TIME ]; then
-        zmstat-chart-config > $confTmp
-        rc=$?
-        if [ $rc -ne 0 ]; then
-            echo "Unable to generate chart configuration file $conf"
-            if [ -e $confTmp ]; then
-                rm -f $confTmp
-            fi
-            exit $rc
-        fi
-        mv -f $confTmp $conf
-    fi
-    exec zmjava -Djava.awt.headless=true com.zimbra.perf.chart.ChartUtil --conf $conf "$@"
+    mv -f $confTmp $conf
+  fi
+  exec zmjava -Djava.awt.headless=true com.zimbra.perf.chart.ChartUtil --conf $conf "$@"
 fi
diff --git a/src/bin/zmswatchctl b/src/bin/zmswatchctl
--- a/src/bin/zmswatchctl
+++ b/src/bin/zmswatchctl
@@ -1,43 +1,30 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-configfile=/opt/zimbra/conf/swatchrc
+configfile=/opt/zextras/conf/swatchrc
 pidfile=${zimbra_log_directory}/swatch.pid
 logfile=${zimbra_log_directory}/zmswatch.out
 pid=""
 
-getpid()
-{
+getpid() {
   if [ -f ${pidfile} ]; then
     pid=$(cat ${pidfile})
   fi
 }
 
-checkrunning()
-{
+checkrunning() {
   getpid
   if [ "x$pid" = "x" ]; then
     running=0
@@ -51,93 +38,93 @@ checkrunning()
   fi
 }
 
-case "$1" in 
-  start)
-    /opt/zimbra/libexec/zmsnmpinit
-    checkrunning
-    echo -n "Starting swatch..."
-    if [ $running = 1 ]; then
-      echo "swatch is already running."
-      exit 0
-    fi
-
-    if [ ! -d ${zimbra_tmp_directory} ]; then
-      mkdir -p ${zimbra_tmp_directory} > /dev/null 2>&1
-    fi
-
-    /opt/zimbra/common/bin/swatchdog --config-file=${configfile} \
-      --use-cpan-file-tail \
-      --script-dir=${zimbra_tmp_directory} --tail-file /var/log/zimbra.log > $logfile 2>&1 &
-    pid=$!
-    if [ "x$pid" != 'x' ]; then
-      if [ -f $logfile ]; then
-        touch $logfile
-      fi
-      chmod 644 $logfile
-      echo $pid > $pidfile
-    else
-      echo "failed."
-      exit 1
-    fi
-    checkrunning
-    if [ $running = 1 ]; then
-      echo "done."
-      exit 0
-    else
-      echo "failed."
-      exit 1
-    fi
-  ;;
-  stop)
-    checkrunning
-    echo -n "Stopping swatch..."
-    if [ $running = 0 ]; then
-      echo "swatch is not running."
-      exit 0
-    else
-      for ((i = 0; i < 30; i++)); do
-        kill -0 $pid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -rf ${pidfile}
-          break
-        fi
-        kill $pid
-        sleep 1
-      done
-    fi
-    if [ -s ${pidfile} ]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
-    fi
+case "$1" in
+start)
+  /opt/zextras/libexec/zmsnmpinit
+  checkrunning
+  echo -n "Starting swatch..."
+  if [ $running = 1 ]; then
+    echo "swatch is already running."
     exit 0
-  ;;
-  restart)
-    $0 stop
-    $0 start
-  ;;
-  reload)
-    checkrunning
-    if [ $running = 1 -a "x$pid" != "x" ]; then
-      echo -n "Reloading swatch..."
-      kill -HUP $pid
-      echo "done."
+  fi
+
+  if [ ! -d ${zimbra_tmp_directory} ]; then
+    mkdir -p ${zimbra_tmp_directory} >/dev/null 2>&1
+  fi
+
+  /opt/zextras/common/bin/swatchdog --config-file=${configfile} \
+    --use-cpan-file-tail \
+    --script-dir=${zimbra_tmp_directory} --tail-file /var/log/carbonio.log >$logfile 2>&1 &
+  pid=$!
+  if [ "x$pid" != 'x' ]; then
+    if [ -f $logfile ]; then
+      touch $logfile
     fi
-  ;;
-  status)
-    echo -n "zmswatch is "
-    checkrunning
-    if [ $running = 0 ]; then
-      echo "not running."
-      exit 1
-    else
-      echo "running."
-      exit 0
-    fi
-  ;;
-  *)
-    echo "$0 start|stop|restart|reload|status"
+    chmod 644 $logfile
+    echo $pid >$pidfile
+  else
+    echo "failed."
     exit 1
+  fi
+  checkrunning
+  if [ $running = 1 ]; then
+    echo "done."
+    exit 0
+  else
+    echo "failed."
+    exit 1
+  fi
+  ;;
+stop)
+  checkrunning
+  echo -n "Stopping swatch..."
+  if [ $running = 0 ]; then
+    echo "swatch is not running."
+    exit 0
+  else
+    for ((i = 0; i < 30; i++)); do
+      kill -0 $pid 2>/dev/null
+      if [ $? != 0 ]; then
+        rm -rf ${pidfile}
+        break
+      fi
+      kill $pid
+      sleep 1
+    done
+  fi
+  if [ -s ${pidfile} ]; then
+    echo "failed."
+    exit 1
+  else
+    echo "done."
+  fi
+  exit 0
+  ;;
+restart)
+  $0 stop
+  $0 start
+  ;;
+reload)
+  checkrunning
+  if [ $running = 1 -a "x$pid" != "x" ]; then
+    echo -n "Reloading swatch..."
+    kill -HUP $pid
+    echo "done."
+  fi
+  ;;
+status)
+  echo -n "zmswatch is "
+  checkrunning
+  if [ $running = 0 ]; then
+    echo "not running."
+    exit 1
+  else
+    echo "running."
+    exit 0
+  fi
+  ;;
+*)
+  echo "$0 start|stop|restart|reload|status"
+  exit 1
   ;;
 esac
diff --git a/src/bin/zmtlsctl b/src/bin/zmtlsctl
--- a/src/bin/zmtlsctl
+++ b/src/bin/zmtlsctl
@@ -1,39 +1,28 @@
 #!/bin/bash
-#
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-#
 
-if [ x$(whoami) != "xzimbra" ]; then
-    echo "Error: $0 must be run as user zimbra"
-    exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != "xzextras" ]; then
+  echo "Error: $0 must be run as user zextras"
+  exit 1
 fi
 
-function chk_command () {
-    for cmd in "$@"; do
-        if [ ! -x "$cmd" ]; then
-            echo "error: unable to find the command '${cmd##*/}'";
-            exit 1;
-        fi
-    done
+function chk_command() {
+  for cmd in "$@"; do
+    if [ ! -x "$cmd" ]; then
+      echo "error: unable to find the command '${cmd##*/}'"
+      exit 1
+    fi
+  done
 }
 
-ldapsearch="/opt/zimbra/common/bin/ldapsearch"
-zmhostname="/opt/zimbra/bin/zmhostname"
-zmlocalconfig="/opt/zimbra/bin/zmlocalconfig"
-zmprov="/opt/zimbra/bin/zmprov"
+ldapsearch="/opt/zextras/common/bin/ldapsearch"
+zmhostname="/opt/zextras/bin/zmhostname"
+zmlocalconfig="/opt/zextras/bin/zmlocalconfig"
+zmprov="/opt/zextras/bin/zmprov"
 
 chk_command $ldapsearch $zmhostname $zmlocalconfig $zmprov
 
@@ -41,198 +30,199 @@ hostname=$($zmhostname)
 
 # NOTE: ldap_url may be multi-valued
 if ! eval $(${zmlocalconfig} -q -m export ldap_url zimbra_ldap_userdn zimbra_ldap_password); then
-    echo "Error: executing: ${zmlocalconfig} -q -m export"
-    exit 1
+  echo "Error: executing: ${zmlocalconfig} -q -m export"
+  exit 1
 fi
 
 zmgetallproxies_cache="unknown"
 zmgetallproxies() {
-    if [ $zmgetallproxies_cache = "unknown" ]; then
-        ldap_urls=($ldap_url)
-        search=$(${ldapsearch} -LL -H "$ldap_urls" -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" \
-            -b 'cn=servers,cn=zimbra' '(&(objectClass=zimbraServer)(zimbraServiceEnabled=proxy))' cn 2>/dev/null)
-        if [ $? -eq 0 ]; then
-            zmgetallproxies_cache=$(echo "$search" | awk '/cn:/ {print $2}')
-        else
-            zmgetallproxies_cache=""
-        fi
+  if [ $zmgetallproxies_cache = "unknown" ]; then
+    ldap_urls=($ldap_url)
+    search=$(${ldapsearch} -LL -H "$ldap_urls" -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" \
+      -b 'cn=servers,cn=zimbra' '(&(objectClass=zimbraServer)(zimbraServiceEnabled=proxy))' cn 2>/dev/null)
+    if [ $? -eq 0 ]; then
+      zmgetallproxies_cache=$(echo "$search" | awk '/cn:/ {print $2}')
+    else
+      zmgetallproxies_cache=""
     fi
-    echo "$zmgetallproxies_cache"
+  fi
+  echo "$zmgetallproxies_cache"
 }
 
 zmgetproxyforhost() {
-    host=$1
-    ldap_urls=($ldap_url)
-    found_rp_avail_lookups=
-    # First, see if there is a proxy (or proxies) sepcifically designated for this host
-    proxies=
-    search=$(${ldapsearch} -LL -H "$ldap_urls" -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" \
-        -b 'cn=servers,cn=zimbra' "(&(objectClass=zimbraServer)(zimbraReverseProxyAvailableLookupTargets=*$host*))" \
-        cn 2>/dev/null)
-    if [ $? -eq 0 ]; then
-        proxies=$(echo "$search" | awk '/cn:/ {print $2}')
-        if [ "x${proxies}" != "x" ]; then
-            echo "$proxies"
-            return
-        fi
+  host=$1
+  ldap_urls=($ldap_url)
+  found_rp_avail_lookups=
+  # First, see if there is a proxy (or proxies) sepcifically designated for this host
+  proxies=
+  search=$(${ldapsearch} -LL -H "$ldap_urls" -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" \
+    -b 'cn=servers,cn=zimbra' "(&(objectClass=zimbraServer)(zimbraReverseProxyAvailableLookupTargets=*$host*))" \
+    cn 2>/dev/null)
+  if [ $? -eq 0 ]; then
+    proxies=$(echo "$search" | awk '/cn:/ {print $2}')
+    if [ "x${proxies}" != "x" ]; then
+      echo "$proxies"
+      return
     fi
-    # If not, just return the list of all proxies and we will use the first one that works
-    zmgetallproxies
+  fi
+  # If not, just return the list of all proxies and we will use the first one that works
+  zmgetallproxies
 }
 
 validate_setting=1
 zmvalidatehost() {
-    foundhost=0
-    hosts=$(${zmprov} garpb | awk '/server/ {split($2,parts,":"); print parts[1]}')
-    for h in ${hosts[@]}; do
-        if [ "$hostname" = "$h" ]; then
-            foundhost=1
-            break
-        fi
-    done
-    if [ $foundhost -eq 1 ]; then
-        allproxies=$(zmgetallproxies)
-        if [ x"$allproxies" != "x" ]; then
-            return
-        else
-            echo "Warning: No proxy servers were detected. No validation will be performed."
-        fi
-    else
-        echo "Warning: $hostname is not in the list of reverse proxy backends. No validation will be performed."
+  foundhost=0
+  hosts=$(${zmprov} garpb | awk '/server/ {split($2,parts,":"); print parts[1]}')
+  for h in ${hosts[@]}; do
+    if [ "$hostname" = "$h" ]; then
+      foundhost=1
+      break
     fi
-    validate_setting=0
+  done
+  if [ $foundhost -eq 1 ]; then
+    allproxies=$(zmgetallproxies)
+    if [ x"$allproxies" != "x" ]; then
+      return
+    else
+      echo "Warning: No proxy servers were detected. No validation will be performed."
+    fi
+  else
+    echo "Warning: $hostname is not in the list of reverse proxy backends. No validation will be performed."
+  fi
+  validate_setting=0
 }
 zmvalidatehost
 
-sasl_conf_directory=/opt/zimbra/common/etc
+sasl_conf_directory=/opt/zextras/common/etc
 mailboxd_server=jetty
 mailboxd_conf_directory=${mailboxd_directory}/etc
-jetty_web_xml=/opt/zimbra/jetty/etc
+jetty_web_xml=/opt/zextras/jetty/etc
 
 usage() {
-    exitcode=$1
-    if [ $validate_setting -eq 1 ]; then
-        echo "Usage: $0 [both|http|https|help]"
-    else
-        echo "Usage: $0 [both|http|https|redirect|mixed|help]"
-    fi
-    exit $exitcode
+  exitcode=$1
+  if [ $validate_setting -eq 1 ]; then
+    echo "Usage: $0 [both|http|https|help]"
+  else
+    echo "Usage: $0 [both|http|https|redirect|mixed|help]"
+  fi
+  exit $exitcode
 }
 
-
 if [ $# -gt 1 ]; then
-    usage 1
+  usage 1
 fi
 
 case "$1" in
-    both|http|https|mixed|redirect)
-        MODE=$1
-        UPDATE_MAIL_MODE=1
-    ;;
-    help|--help|-help)
-        usage 0
-    ;;
-    '')
-    ;;
-    *)
-        usage 1
-    ;;
+both | http | https | mixed | redirect)
+  MODE=$1
+  UPDATE_MAIL_MODE=1
+  ;;
+help | --help | -help)
+  usage 0
+  ;;
+'') ;;
+
+*)
+  usage 1
+  ;;
 esac
 
 export JAVA_HOME=${zimbra_java_home}
 
 if [ "x${zimbra_tmp_directory}" = "x" ]; then
-    zimbra_tmp_directory=/opt/zimbra/data/tmp
+  zimbra_tmp_directory=/opt/zextras/data/tmp
 fi
 if [ ! -d ${zimbra_tmp_directory} ]; then
-    mkdir -p ${zimbra_tmp_directory}
+  mkdir -p ${zimbra_tmp_directory}
 fi
 
-
 rewriteConfigs() {
-    echo -n "Rewriting config files for cyrus-sasl, webxml, mailboxd, service, zimbraUI, and zimbraAdmin..."
-    /opt/zimbra/libexec/configrewrite sasl webxml mailbox service zimbra zimbraAdmin zimlet> /dev/null 2>&1
-    if [ $? = 0 ]; then
-        echo "done."
-    else
-        echo "failed."
-        exit 1
-    fi
+  echo -n "Rewriting config files for cyrus-sasl, webxml, mailboxd, service, zimbraUI, and zimbraAdmin..."
+  /opt/zextras/libexec/configrewrite sasl webxml mailbox service zextras zextrasAdmin zimlet >/dev/null 2>&1
+  if [ $? = 0 ]; then
+    echo "done."
+  else
+    echo "failed."
+    exit 1
+  fi
 }
 
 updateLdap() {
-    proxies=$(zmgetproxyforhost $hostname)
-    if [ $validate_setting -eq 1 -a x"$proxies" != "x" ]; then
-        # check the value of zimbraReverseProxySSLToUpstreamEnabled and zimbraReverseProxyMailMode
-        # on a suitable proxy server
-        sslup=
-        rpmm=
-        for proxy in "${proxies[@]}"; do
-            echo "Attempting to query proxy ($proxy) settings for zimbraReverseProxyMailMode and zimbraReverseProxySSLToUpstreamEnabled."
-            setting=$(/opt/zimbra/bin/zmprov -l gs ${proxy} zimbraReverseProxySSLToUpstreamEnabled zimbraReverseProxyMailMode)
-            if [ $? -eq 0 ]; then
-                sslup=$(echo "$setting" | awk '/zimbraReverseProxySSLToUpstreamEnabled:/ {print $2}')
-                rpmm=$(echo "$setting" | awk '/zimbraReverseProxyMailMode:/ {print $2}')
-                break
-            fi
-        done
-        if [ "x$sslup" = "x" ]; then
-            echo "Error: Unable to determine the proxy's value of zimbraReverseProxySSLToUpstreamEnabled"
-            exit 1
-        fi
-        if [ "x$rpmm" = "x" ]; then
-            echo "Error: Unable to determine the proxy's value of zimbraReverseProxyMailMode"
-            exit 1
-        fi
-        # validate setting of zimbraReverseProxyMailMode based on the setting of zimbraReverseProxySSLToUpstreamEnabled
-        echo "On proxy ($proxy): zimbraReverseProxyMailMode='$rpmm', zimbraReverseProxySSLToUpstreamEnabled='$sslup'"
-        if [ "$sslup" = "TRUE" -a "$rpmm" != "both" -a "$rpmm" != "https" -a "$rpmm" != "mixed" -a "$rpmm" != "redirect" ]; then
-            echo "Error: When zimbraReverseProxySSLToUpstreamEnabled (on the proxy server) is TRUE, zimbraReverseProxyMailMode must be one of the following: both, https, mixed, or redirect. Please correct this on the proxy server then retry this command."
-            exit 1
-        fi
-        if [ "$sslup" = "FALSE" -a "$rpmm" != "both" -a "$rpmm" != "http" ]; then
-            echo "Error: When zimbraReverseProxySSLToUpstreamEnabled (on the proxy server) is FALSE, zimbraReverseProxyMailMode must be one of the following: both or http. Please correct this on the proxy server then retry this command."
-            exit 1
-        fi
-        # Validate the new setting of zimbraMailMode based on the setting of zimbraReverseProxyMailMode
-        if [ "$rpmm" = "both" -a "$MODE" != "both" ]; then
-            echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is both, the only valid setting for zimbraMailMode is both."
-            exit 1
-        fi
-        if [ "$rpmm" = "http" -a "$MODE" != "both" -a "$MODE" != "http" ]; then
-            echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is http, the only valid settings for zimbraMailMode are both or http."
-            exit 1
-        fi
-        if [ "$rpmm" = "https" -a "$MODE" != "both" -a "$MODE" != "https" ]; then
-            echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is https, the only valid settings for zimbraMailMode are both or https."
-            exit 1
-        fi
-        if [ "$rpmm" = "mixed" -a "$MODE" != "both" ]; then
-            echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is mixed, the only valid setting for zimbraMailMode is both."
-            exit 1
-        fi
-        if [ "$rpmm" = "redirect" -a "$MODE" != "both" -a "$MODE" != "https" ]; then
-            echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is redirect, the only valid settings for zimbraMailMode are both or https."
-            exit 1
-        fi
+  proxies=$(zmgetproxyforhost $hostname)
+  if [ $validate_setting -eq 1 -a x"$proxies" != "x" ]; then
+    # check the value of zimbraReverseProxySSLToUpstreamEnabled and zimbraReverseProxyMailMode
+    # on a suitable proxy server
+    sslup=
+    rpmm=
+    for proxy in "${proxies[@]}"; do
+      echo "Attempting to query proxy ($proxy) settings for zimbraReverseProxyMailMode and zimbraReverseProxySSLToUpstreamEnabled."
+      setting=$(/opt/zextras/bin/zmprov -l gs ${proxy} zimbraReverseProxySSLToUpstreamEnabled zimbraReverseProxyMailMode)
+      if [ $? -eq 0 ]; then
+        sslup=$(echo "$setting" | awk '/zimbraReverseProxySSLToUpstreamEnabled:/ {print $2}')
+        rpmm=$(echo "$setting" | awk '/zimbraReverseProxyMailMode:/ {print $2}')
+        break
+      fi
+    done
+    if [ "x$sslup" = "x" ]; then
+      echo "Error: Unable to determine the proxy's value of zimbraReverseProxySSLToUpstreamEnabled"
+      exit 1
     fi
+    if [ "x$rpmm" = "x" ]; then
+      echo "Error: Unable to determine the proxy's value of zimbraReverseProxyMailMode"
+      exit 1
+    fi
+    # validate setting of zimbraReverseProxyMailMode based on the setting of zimbraReverseProxySSLToUpstreamEnabled
+    echo "On proxy ($proxy): zimbraReverseProxyMailMode='$rpmm', zimbraReverseProxySSLToUpstreamEnabled='$sslup'"
+    if [ "$sslup" = "TRUE" -a "$rpmm" != "both" -a "$rpmm" != "https" -a "$rpmm" != "mixed" -a "$rpmm" != "redirect" ]; then
+      echo "Error: When zimbraReverseProxySSLToUpstreamEnabled (on the proxy server) is TRUE, zimbraReverseProxyMailMode must be one of the following: both, https, mixed, or redirect. Please correct this on the proxy server then retry this command."
+      exit 1
+    fi
+    if [ "$sslup" = "FALSE" -a "$rpmm" != "both" -a "$rpmm" != "http" ]; then
+      echo "Error: When zimbraReverseProxySSLToUpstreamEnabled (on the proxy server) is FALSE, zimbraReverseProxyMailMode must be one of the following: both or http. Please correct this on the proxy server then retry this command."
+      exit 1
+    fi
+    # Validate the new setting of zimbraMailMode based on the setting of zimbraReverseProxyMailMode
+    if [ "$rpmm" = "both" -a "$MODE" != "both" ]; then
+      echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is both, the only valid setting for zimbraMailMode is both."
+      exit 1
+    fi
+    if [ "$rpmm" = "http" -a "$MODE" != "both" -a "$MODE" != "http" ]; then
+      echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is http, the only valid settings for zimbraMailMode are both or http."
+      exit 1
+    fi
+    if [ "$rpmm" = "https" -a "$MODE" != "both" -a "$MODE" != "https" ]; then
+      echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is https, the only valid settings for zimbraMailMode are both or https."
+      exit 1
+    fi
+    if [ "$rpmm" = "mixed" -a "$MODE" != "both" ]; then
+      echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is mixed, the only valid setting for zimbraMailMode is both."
+      exit 1
+    fi
+    if [ "$rpmm" = "redirect" -a "$MODE" != "both" -a "$MODE" != "https" ]; then
+      echo "Error: When zimbraReverseProxyMailMode (on the proxy server) is redirect, the only valid settings for zimbraMailMode are both or https."
+      exit 1
+    fi
+  fi
 
-    tmpfile=$(mktemp ${zimbra_tmp_directory}/zmprov.XXX 2> /dev/null) || { echo "Failed to create tmpfile"; exit 1; }
-    echo -n "Attempting to set ldap config zimbraMailMode $MODE on host ${hostname}..."
-    /opt/zimbra/bin/zmprov -l ms ${hostname} zimbraMailMode $MODE > /dev/null 2>$tmpfile
-    if [ $? -eq 0 ]; then
-        echo "done."
-        rm $tmpfile
-        return
-    fi
-    echo "failed."
-    cat $tmpfile
-    rm $tmpfile
+  tmpfile=$(mktemp ${zimbra_tmp_directory}/zmprov.XXX 2>/dev/null) || {
+    echo "Failed to create tmpfile"
     exit 1
+  }
+  echo -n "Attempting to set ldap config zimbraMailMode $MODE on host ${hostname}..."
+  /opt/zextras/bin/zmprov -l ms ${hostname} zimbraMailMode $MODE >/dev/null 2>$tmpfile
+  if [ $? -eq 0 ]; then
+    echo "done."
+    rm $tmpfile
+    return
+  fi
+  echo "failed."
+  cat $tmpfile
+  rm $tmpfile
+  exit 1
 }
 
 if [ x"$UPDATE_MAIL_MODE" = "x1" ]; then
-    updateLdap
+  updateLdap
 fi
 
 rewriteConfigs
diff --git a/src/bin/zmtrainsa b/src/bin/zmtrainsa
--- a/src/bin/zmtrainsa
+++ b/src/bin/zmtrainsa
@@ -1,55 +1,36 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
 
 autoTrainSystem() {
 
   timestampit "Starting spam/ham extraction from system accounts."
-  spamdir=`mktmpdir spam`
-  hamdir=`mktmpdir ham`
-  /opt/zimbra/libexec/zmspamextract ${spam_account} -o ${spamdir}
-  /opt/zimbra/libexec/zmspamextract ${ham_account} -o ${hamdir}
+  spamdir=$(mktmpdir spam)
+  hamdir=$(mktmpdir ham)
+  /opt/zextras/libexec/zmspamextract ${spam_account} -o ${spamdir}
+  /opt/zextras/libexec/zmspamextract ${ham_account} -o ${hamdir}
   timestampit "Finished extracting spam/ham from system accounts."
 
   timestampit "Starting spamassassin training."
-  /opt/zimbra/common/bin/sa-learn \
+  /opt/zextras/common/bin/sa-learn \
     --dbpath=${db_path} -L --no-sync \
     --spam ${spamdir}
 
-  /opt/zimbra/common/bin/sa-learn \
+  /opt/zextras/common/bin/sa-learn \
     --dbpath=${db_path} -L --no-sync \
     --ham ${hamdir}
 
-  /opt/zimbra/common/bin/sa-learn \
+  /opt/zextras/common/bin/sa-learn \
     --dbpath=${db_path} --sync
   timestampit "Finished spamassassin training."
 
   if [ x"$amavis_dspam_enabled" = "xtrue" ]; then
     timestampit "Starting dspam training"
-    /opt/zimbra/dspam/bin/dspam_train zimbra ${spamdir} ${hamdir}
-    #for f in ${spamdir}/*; do
-      #test -f ${f} && /opt/zimbra/dspam/bin/dspam_corpus --addspam zimbra ${f}
-    #done
-    #for f in ${hamdir}/*; do
-      #test -f ${f} && /opt/zimbra/dspam/bin/dspam_corpus zimbra ${f}
-    #done
-
-    /opt/zimbra/dspam/bin/dspam_clean -p0 $USER
+    /opt/zextras/dspam/bin/dspam_train zimbra ${spamdir} ${hamdir}
+    /opt/zextras/dspam/bin/dspam_clean -p0 $USER
     timestampit "Finished dspam training"
   fi
 
@@ -58,35 +39,35 @@ autoTrainSystem() {
 
 trainAccountFolder() {
 
-  tempdir=`mktmpdir ${MODE}`
+  tempdir=$(mktmpdir ${MODE})
   if [ "x${MODE}" = "xspam" ]; then
     FOLDER=${FOLDER:=junk}
   elif [ "x${MODE}" = "xham" ]; then
     FOLDER=${FOLDER:=inbox}
   fi
 
-  timestampit  "Starting spamassassin $MODE training for $USER using folder $FOLDER"
-  /opt/zimbra/libexec/zmspamextract -r -m $USER -o ${tempdir} -q in:${FOLDER}
+  timestampit "Starting spamassassin $MODE training for $USER using folder $FOLDER"
+  /opt/zextras/libexec/zmspamextract -r -m $USER -o ${tempdir} -q in:${FOLDER}
 
-  /opt/zimbra/common/bin/sa-learn \
+  /opt/zextras/common/bin/sa-learn \
     --dbpath=${db_path} -L --no-sync \
     --${MODE} ${tempdir}
 
-  /opt/zimbra/common/bin/sa-learn \
+  /opt/zextras/common/bin/sa-learn \
     --dbpath=${db_path} --sync
-  timestampit  "Finished spamassassin $MODE training for $USER using folder $FOLDER"
+  timestampit "Finished spamassassin $MODE training for $USER using folder $FOLDER"
 
   if [ x"$amavis_dspam_enabled" = "xtrue" ]; then
-    timestampit  "Starting dspam $MODE training for $USER using folder $FOLDER"
+    timestampit "Starting dspam $MODE training for $USER using folder $FOLDER"
     if [ $MODE == "ham" ]; then
       MODE="innocent"
     fi
 
-    /opt/zimbra/dspam/bin/dspam --user zimbra --class=${MODE} --source=corpus --mode=teft \
+    /opt/zextras/dspam/bin/dspam --user zextras --class=${MODE} --source=corpus --mode=teft \
       --feature=noise --stdout
 
-    /opt/zimbra/dspam/bin/dspam_clean -p0 $USER
-    timestampit  "Finished dspam $MODE training for $USER using folder $FOLDER"
+    /opt/zextras/dspam/bin/dspam_clean -p0 $USER
+    timestampit "Finished dspam $MODE training for $USER using folder $FOLDER"
   fi
 
   /bin/rm -rf ${tempdir}
@@ -98,7 +79,7 @@ mktmpdir() {
 }
 
 timestampit() {
-  SIMPLE_DATE=`date +%Y%m%d%H%M%S`
+  SIMPLE_DATE=$(date +%Y%m%d%H%M%S)
   echo "$SIMPLE_DATE $1"
 }
 
@@ -107,43 +88,42 @@ usage() {
   exit 1
 }
 
-if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+if [ x$(whoami) != xzextras ]; then
+  echo Error: must be run as zextras user
   exit 1
 fi
 
-if [ ! -x "/opt/zimbra/common/sbin/amavisd" ]; then
-    echo "Error: SpamAssassin not installed"
-    exit 1
+if [ ! -x "/opt/zextras/common/sbin/amavisd" ]; then
+  echo "Error: SpamAssassin not installed"
+  exit 1
 fi
 
-source `dirname $0`/zmshutil || exit 1
+source $(dirname $0)/zmshutil || exit 1
 zmsetvars
 
-amavis_dspam_enabled=`/opt/zimbra/bin/zmprov -l gs ${zimbra_server_hostname} zimbraAmavisDSPAMEnabled | grep zimbraAmavisDSPAMEnabled: | awk '{print $2}'`
+amavis_dspam_enabled=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraAmavisDSPAMEnabled | grep zimbraAmavisDSPAMEnabled: | awk '{print $2}')
 amavis_dspam_enabled=$(echo $amavis_dspam_enabled | tr A-Z a-z)
 antispam_mysql_enabled=$(echo $antispam_mysql_enabled | tr A-Z a-z)
 zmtrainsa_cleanup_host=$(echo $zmtrainsa_cleanup_host | tr A-Z a-z)
 
 if [ "x${zimbra_spam_externalIsSpamAccount}" = "x" ]; then
   spam_account="-s"
-else 
+else
   spam_account="-m ${zimbra_spam_externalIsSpamAccount}"
 fi
 
 if [ "x${zimbra_spam_externalIsNotSpamAccount}" = "x" ]; then
   ham_account="-n"
-else 
+else
   ham_account="-m ${zimbra_spam_externalIsNotSpamAccount}"
 fi
 
 # Set db_path
 if [ x"$antispam_mysql_enabled" = "xtrue" ]; then
-  db_path='/opt/zimbra/data/amavisd/mysql/data'
+  db_path='/opt/zextras/data/amavisd/mysql/data'
 else
-  db_path='/opt/zimbra/data/amavisd/.spamassassin'
+  db_path='/opt/zextras/data/amavisd/.spamassassin'
 fi
-
 
 # No argument mode uses zmspamextract for auto-training.
 if [ x$1 = "x" ]; then
@@ -154,20 +134,19 @@ fi
 if [ x$1 = "x--cleanup" ]; then
   if [ x${zmtrainsa_cleanup_host} = "xtrue" ]; then
     timestampit "Starting spam/ham cleanup"
-    mydir=`mktmpdir cleanup`
-    /opt/zimbra/libexec/zmspamextract ${spam_account} -o ${mydir} -d
-    /opt/zimbra/libexec/zmspamextract ${ham_account} -o ${mydir} -d
+    mydir=$(mktmpdir cleanup)
+    /opt/zextras/libexec/zmspamextract ${spam_account} -o ${mydir} -d
+    /opt/zextras/libexec/zmspamextract ${ham_account} -o ${mydir} -d
     /bin/rm -rf ${mydir}
     timestampit "Finished spam/ham cleanup"
-  else 
+  else
     timestampit "Cleanup skipped: $zimbra_server_hostname is not a spam/ham cleanup host."
   fi
   exit
 fi
 
-
 USER=$1
-MODE=`echo $2 | tr A-Z a-z`
+MODE=$(echo $2 | tr A-Z a-z)
 FOLDER=$3
 
 if [ "x${MODE}" != "xspam" -a "x${MODE}" != "xham" ]; then
@@ -181,4 +160,3 @@ fi
 trainAccountFolder
 
 exit 0
-
diff --git a/src/bin/zmupdateauthkeys b/src/bin/zmupdateauthkeys
--- a/src/bin/zmupdateauthkeys
+++ b/src/bin/zmupdateauthkeys
@@ -1,104 +1,95 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2009, 2010, 2011, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source `dirname $0`/../bin/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source $(dirname $0)/../bin/zmshutil || exit 1
 
 zmsetvars
 
 getPubKey() {
-	server=$1
-	echo "Fetching key for ${s}"
-	pubkey=`${zmprov} gs ${server} 2> /dev/null \
-		| grep $keyattr | sed -e "s/^${keyattr}: //"`
+  server=$1
+  echo "Fetching key for ${s}"
+  pubkey=$(${zmprov} gs ${server} 2>/dev/null |
+    grep $keyattr | sed -e "s/^${keyattr}: //")
 }
 
 replacePubKey() {
-	server=$1
-	key=$2
-	echo "Updating keys for $server"
-	keyhost=`echo ${key} | awk '{print $3}'`
+  server=$1
+  key=$2
+  echo "Updating keys for $server"
+  keyhost=$(echo ${key} | awk '{print $3}')
 
-	echo "${authkeys}" > ${tempkeysfile}
-	cat /dev/null > ${tempkeysfile}.new
+  echo "${authkeys}" >${tempkeysfile}
+  cat /dev/null >${tempkeysfile}.new
 
-	while read keyline; do
-		linehost=`echo ${keyline} | awk '{print $4}'`
-		if [ x$linehost != x$keyhost ]; then
-			echo "${keyline}" >> ${tempkeysfile}.new
-		fi
-	done < ${tempkeysfile}
+  while read keyline; do
+    linehost=$(echo ${keyline} | awk '{print $4}')
+    if [ x$linehost != x$keyhost ]; then
+      echo "${keyline}" >>${tempkeysfile}.new
+    fi
+  done <${tempkeysfile}
 
-	#Don't change the indentation on these lines
+  #Don't change the indentation on these lines
 
-	authkeys=`cat ${tempkeysfile}.new`
+  authkeys=$(cat ${tempkeysfile}.new)
 
-	authkeys="${authkeys}
-command=\"/opt/zimbra/libexec/zmrcd\" ${key}"
-	
-	/bin/rm -f ${tempkeysfile} ${tempkeysfile}.new
+  authkeys="${authkeys}
+command=\"/opt/zextras/libexec/zmrcd\" ${key}"
+
+  /bin/rm -f ${tempkeysfile} ${tempkeysfile}.new
 }
 
 updateAllServers() {
   for s in ${servers}; do
     echo "Updating authkeys on remote server $s"
-    echo "HOST:$s zmupdateauthkeys" | /opt/zimbra/libexec/zmrc $s
+    echo "HOST:$s zmupdateauthkeys" | /opt/zextras/libexec/zmrc $s
   done
 }
 
-# Get all the public keys from ldap, and replace them in 
-# /opt/zimbra/.ssh/authorized_keys
+# Get all the public keys from ldap, and replace them in
+# /opt/zextras/.ssh/authorized_keys
 
 keyattr="zimbraSshPublicKey"
 
-zmprov="/opt/zimbra/bin/zmprov -m -l"
+zmprov="/opt/zextras/bin/zmprov -m -l"
 
-authkeysfile="/opt/zimbra/.ssh/authorized_keys"
+authkeysfile="/opt/zextras/.ssh/authorized_keys"
 
 if [ ! -d ${zimbra_tmp_directory} ]; then
-  mkdir -p ${zimbra_tmp_directory} > /dev/null 2>&1
+  mkdir -p ${zimbra_tmp_directory} >/dev/null 2>&1
 fi
 
-tempkeysfile=`mktemp -t auth_keys.XXXXXX 2> /dev/null` || { echo "Failed to create tmpfile"; exit 1; }
+tempkeysfile=$(mktemp -t auth_keys.XXXXXX 2>/dev/null) || {
+  echo "Failed to create tmpfile"
+  exit 1
+}
 
 if [ -f $authkeysfile ]; then
-	authkeys=`cat ${authkeysfile}`
+  authkeys=$(cat ${authkeysfile})
 fi
 
 #echo "Authorized keys: ${authkeys}"
 
-servers=`${zmprov} gas`
+servers=$(${zmprov} gas)
 
 #
 if [ x$1 == "x-a" ]; then
- updateAllServers
+  updateAllServers
 fi
 
 for s in ${servers}; do
-	echo "Updating keys for ${s}"
-	getPubKey ${s}
-	if [ "x$pubkey" != "x" ]; then
-		replacePubKey ${s} "${pubkey}"
-	else
-		echo "Key for ${s} NOT FOUND"
-	fi
+  echo "Updating keys for ${s}"
+  getPubKey ${s}
+  if [ "x$pubkey" != "x" ]; then
+    replacePubKey ${s} "${pubkey}"
+  else
+    echo "Key for ${s} NOT FOUND"
+  fi
 done
 
 echo "Updating ${authkeysfile}"
-echo "${authkeys}" > ${tempkeysfile} && mv ${tempkeysfile} ${authkeysfile}
+echo "${authkeys}" >${tempkeysfile} && mv ${tempkeysfile} ${authkeysfile}
 chmod 644 ${authkeysfile}
-
diff --git a/src/libexec/zmantispamdbinit b/src/libexec/zmantispamdbinit
--- a/src/libexec/zmantispamdbinit
+++ b/src/libexec/zmantispamdbinit
@@ -1,22 +1,11 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2010, 2011, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source /opt/zimbra/bin/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars
 
 sql_root_pw=$1
@@ -24,110 +13,107 @@ sql_root_pw=$1
 #
 # Sanity checks
 #
-zmassert -x /opt/zimbra/bin/antispam-mysqladmin
-zmassert -x /opt/zimbra/bin/antispam-mysql
-zmassert -x /opt/zimbra/bin/zmlocalconfig
-zmassert -x /opt/zimbra/bin/zmantispamdbpasswd
-zmassert -x /opt/zimbra/common/share/mysql/scripts/mysql_install_db
-zmassert -r /opt/zimbra/data/amavisd/mysql/antispamdb.sql
+zmassert -x /opt/zextras/bin/antispam-mysqladmin
+zmassert -x /opt/zextras/bin/antispam-mysql
+zmassert -x /opt/zextras/bin/zmlocalconfig
+zmassert -x /opt/zextras/bin/zmantispamdbpasswd
+zmassert -x /opt/zextras/common/share/mysql/scripts/mysql_install_db
+zmassert -r /opt/zextras/data/amavisd/mysql/antispamdb.sql
 
 # Check if log directory exists.  If not, create.
 if [ ! -d ${zimbra_log_directory} ]; then
-	mkdir -p ${zimbra_log_directory}
+  mkdir -p ${zimbra_log_directory}
 fi
 
 #
 # Create antispam-my.cnf file if it does not exist
 #
-if [ ! -s ${antispam_mysql_mycnf} ]; then 
-    /opt/zimbra/libexec/zmantispammycnf > ${antispam_mysql_mycnf}
+if [ ! -s ${antispam_mysql_mycnf} ]; then
+  /opt/zextras/libexec/zmantispammycnf >${antispam_mysql_mycnf}
 fi
 
 #
 # Create database
 #
 echo '*' Creating database in ${antispam_mysql_data_directory}
-(/opt/zimbra/common/share/mysql/scripts/mysql_install_db \
-    --basedir=/opt/zimbra/common \
-    --datadir=${antispam_mysql_data_directory} \
-    --defaults-file=${antispam_mysql_mycnf} ) \
-    >> ${zimbra_log_directory}/zmantispamdbinit.log 2>&1
+(/opt/zextras/common/share/mysql/scripts/mysql_install_db \
+  --basedir=/opt/zextras/common \
+  --datadir=${antispam_mysql_data_directory} \
+  --defaults-file=${antispam_mysql_mycnf}) \
+  >>${zimbra_log_directory}/zmantispamdbinit.log 2>&1
 
 #
 # Start mysql server for antispam db
 #
-zmassert -d `dirname ${antispam_mysql_pidfile}`
+zmassert -d $(dirname ${antispam_mysql_pidfile})
 if [ -f ${antispam_mysql_pidfile} ]; then
-    pid=`cat ${antispam_mysql_pidfile}`
+  pid=$(cat ${antispam_mysql_pidfile})
 fi
 if [ "x$pid" != "x" ]; then
-    kill -0 $pid 2> /dev/null
-    if [ $? = 0 ]; then
-        # What the heck happened here.  mysqld_safe for anti-spam should not already be running!
-        echo "mysqld_safe for anti-spam already running with pid $pid"
-        exit 1
-    fi
+  kill -0 $pid 2>/dev/null
+  if [ $? = 0 ]; then
+    # What the heck happened here.  mysqld_safe for anti-spam should not already be running!
+    echo "mysqld_safe for anti-spam already running with pid $pid"
+    exit 1
+  fi
 fi
 # --defaults-file must be first argument
 echo -n '*' Starting antispam mysql server ...
-/opt/zimbra/common/bin/mysqld_safe \
-    --defaults-file=${antispam_mysql_mycnf} \
-    --basedir=/opt/zimbra/common \
-    --datadir=${antispam_mysql_data_directory} \
-    --external-locking \
-    --log-error=${antispam_mysql_errlogfile} \
-    --ledir=/opt/zimbra/common/sbin < /dev/null > /dev/null 2>&1 &
+/opt/zextras/common/bin/mysqld_safe \
+  --defaults-file=${antispam_mysql_mycnf} \
+  --basedir=/opt/zextras/common \
+  --datadir=${antispam_mysql_data_directory} \
+  --external-locking \
+  --log-error=${antispam_mysql_errlogfile} \
+  --ledir=/opt/zextras/common/sbin </dev/null >/dev/null 2>&1 &
 SQLSTARTED=0
-for ((i = 0; i < 60; i++))
-do
-    /opt/zimbra/bin/antispam-mysqladmin -s ping 2>&1 > /dev/null
-    if [ $? = 0 ]; then
-        SQLSTARTED=1
-        break
-    fi
-    sleep 2
+for ((i = 0; i < 60; i++)); do
+  /opt/zextras/bin/antispam-mysqladmin -s ping 2>&1 >/dev/null
+  if [ $? = 0 ]; then
+    SQLSTARTED=1
+    break
+  fi
+  sleep 2
 done
 if [ ${SQLSTARTED} -ne 1 ]; then
-    echo "failed."
-	exit 1
+  echo "failed."
+  exit 1
 else
-    echo "done."
+  echo "done."
 fi
-
 
 #
 # Load zimbra sql files
 #
-echo '*' Loading schema /opt/zimbra/data/amavisd/mysql/antispamdb.sql 
-/opt/zimbra/bin/antispam-mysql -u root --password= < \
-    /opt/zimbra/data/amavisd/mysql/antispamdb.sql
-
+echo '*' Loading schema /opt/zextras/data/amavisd/mysql/antispamdb.sql
+/opt/zextras/bin/antispam-mysql -u root --password= < \
+  /opt/zextras/data/amavisd/mysql/antispamdb.sql
 
 #
 # Generate passwords for mysql into local config
 #
 if [ x$sql_root_pw = "x" ]; then
-    echo '*' Setting random password for antispam mysql root user in zimbra local config
-    /opt/zimbra/bin/zmlocalconfig -r -f -e antispam_mysql_root_password
+  echo '*' Setting random password for antispam mysql root user in zimbra local config
+  /opt/zextras/bin/zmlocalconfig -r -f -e antispam_mysql_root_password
 
-    echo '*' Setting random password for antispam mysql zimbra user in zimbra local config
-    /opt/zimbra/bin/zmlocalconfig -r -f -e antispam_mysql_password
+  echo '*' Setting random password for antispam mysql zextras user in zimbra local config
+  /opt/zextras/bin/zmlocalconfig -r -f -e antispam_mysql_password
 else
-    echo '*' Setting password for antispam mysql root user in zimbra local config
-    /opt/zimbra/bin/zmlocalconfig -f -e antispam_mysql_root_password=$sql_root_pw
-    echo '*' Setting password for antispam mysql zimbra user in zimbra local config
-    /opt/zimbra/bin/zmlocalconfig -f -e antispam_mysql_password=$sql_root_pw
+  echo '*' Setting password for antispam mysql root user in zimbra local config
+  /opt/zextras/bin/zmlocalconfig -f -e antispam_mysql_root_password=$sql_root_pw
+  echo '*' Setting password for antispam mysql zextras user in zimbra local config
+  /opt/zextras/bin/zmlocalconfig -f -e antispam_mysql_password=$sql_root_pw
 fi
 
 #
-# Change mysql root user password, but first read back the passwords 
+# Change mysql root user password, but first read back the passwords
 # zimbra local config - they was generated above.  Note that we can not
 # use 'zmmypasswd --root' here because of bootstrapping problems - at
 # this stage we know that the root password is empty.
 #
 zmsetvars -f
 echo '*' Changing antispam mysql root user password
-/opt/zimbra/bin/antispam-mysqladmin -u root --password= password ${antispam_mysql_root_password}
+/opt/zextras/bin/antispam-mysqladmin -u root --password= password ${antispam_mysql_root_password}
 
 echo '*' Changing antispam mysql user password
-/opt/zimbra/bin/zmantispamdbpasswd ${antispam_mysql_password}
+/opt/zextras/bin/zmantispamdbpasswd ${antispam_mysql_password}
diff --git a/src/libexec/zmcbpolicydinit b/src/libexec/zmcbpolicydinit
--- a/src/libexec/zmcbpolicydinit
+++ b/src/libexec/zmcbpolicydinit
@@ -1,37 +1,26 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2009, 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != xzimbra ]; then
-  echo "Error: must be run as zimbra user"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != xzextras ]; then
+  echo "Error: must be run as zextras user"
   exit 1
 fi
 
-if [ ! -x /opt/zimbra/common/bin/cbpolicyd ]; then
+if [ ! -x /opt/zextras/common/bin/cbpolicyd ]; then
   echo "Error: cluebringer not installed"
   exit 1
 fi
-source /opt/zimbra/bin/zmshutil || exit 1
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars
 
 pidfile=${cbpolicyd_pid_file:=${zimbra_log_directory}/cbpolicyd.pid}
-dbfile=${cbpolicyd_db_file:=/opt/zimbra/data/cbpolicyd/db/cbpolicyd.sqlitedb}
+dbfile=${cbpolicyd_db_file:=/opt/zextras/data/cbpolicyd/db/cbpolicyd.sqlitedb}
 dbdir=$(dirname $dbfile)
-cbpolicyDir=/opt/zimbra/common
+cbpolicyDir=/opt/zextras/common
 sqlite3=$(which sqlite3)
 
 if [ x${sqlite3} = "x" ]; then
@@ -43,14 +32,14 @@ if [ ! -d $dbdir ]; then
   mkdir -p $dbdir
   if [ $? = 0 ]; then
     exit 1
-  fi 
+  fi
 fi
 
 initCBPolicyd() {
   if [ -f ${dbfile} ]; then
     if [ x"$force" = "x" ]; then
       echo "Must use -force to overwrite existing database."
-      exit 1;
+      exit 1
     else
       rm -f $dbfile
     fi
@@ -58,25 +47,7 @@ initCBPolicyd() {
   echo -n "Converting policyd database templates to sqlite..."
   for i in core.tsql access_control.tsql accounting.tsql amavis.tsql quotas.tsql checkhelo.tsql checkspf.tsql greylisting.tsql; do
     ${cbpolicyDir}/share/database/convert-tsql sqlite ${cbpolicyDir}/share/database/$i | sed -e '/^#/d'
-  done > ${dbfile}.sq3
-  if [ $? != 0 ]; then
-    echo "failed."
-    exit 1
-  else 
-    echo "done."
-  fi
- 
-  echo -n "Creating sqlite database..."  
-  ${sqlite3} ${dbfile} < ${dbfile}.sq3
-  if [ $? != 0 ]; then
-    echo "failed."
-    exit 1
-  else
-    echo "done."
-  fi
-  
-  echo -n "Adding Domains..."
-    for dom in `zmprov gad`; do sqlite3 /opt/zimbra/data/cbpolicyd/db/cbpolicyd.sqlitedb "INSERT INTO policy_group_members (PolicyGroupID,Member) VALUES ('2','@$dom');"; done
+  done >${dbfile}.sq3
   if [ $? != 0 ]; then
     echo "failed."
     exit 1
@@ -84,9 +55,27 @@ initCBPolicyd() {
     echo "done."
   fi
 
- echo -n "Adding subnets from Mynetworks global..."
+  echo -n "Creating sqlite database..."
+  ${sqlite3} ${dbfile} <${dbfile}.sq3
+  if [ $? != 0 ]; then
+    echo "failed."
+    exit 1
+  else
+    echo "done."
+  fi
+
+  echo -n "Adding Domains..."
+  for dom in $(zmprov gad); do sqlite3 /opt/zextras/data/cbpolicyd/db/cbpolicyd.sqlitedb "INSERT INTO policy_group_members (PolicyGroupID,Member) VALUES ('2','@$dom');"; done
+  if [ $? != 0 ]; then
+    echo "failed."
+    exit 1
+  else
+    echo "done."
+  fi
+
+  echo -n "Adding subnets from Mynetworks global..."
   globalSubnet=$(zmprov gacf | grep zimbraMtaMyNetworks | sed 's/127.0.0.0\/8 //g' | awk '{ print $NF }')
-  sqlite3 /opt/zimbra/data/cbpolicyd/db/cbpolicyd.sqlitedb "INSERT INTO policy_group_members (PolicyGroupID,Member) VALUES (1,'$globalSubnet');"
+  sqlite3 /opt/zextras/data/cbpolicyd/db/cbpolicyd.sqlitedb "INSERT INTO policy_group_members (PolicyGroupID,Member) VALUES (1,'$globalSubnet');"
   if [ $? != 0 ]; then
     echo "failed."
     exit 1
@@ -95,8 +84,8 @@ initCBPolicyd() {
   fi
 
   echo -n "Adding subnets from Mynetworks server..."
-  serverSubnet=$(zmprov gs `zmhostname` | grep zimbraMtaMyNetworks | sed 's/127.0.0.0\/8 //g' | awk '{ print $NF }')
-  sqlite3 /opt/zimbra/data/cbpolicyd/db/cbpolicyd.sqlitedb "INSERT INTO policy_group_members (PolicyGroupID,Member) VALUES (1,'$serverSubnet');"
+  serverSubnet=$(zmprov gs $(zmhostname) | grep zimbraMtaMyNetworks | sed 's/127.0.0.0\/8 //g' | awk '{ print $NF }')
+  sqlite3 /opt/zextras/data/cbpolicyd/db/cbpolicyd.sqlitedb "INSERT INTO policy_group_members (PolicyGroupID,Member) VALUES (1,'$serverSubnet');"
   if [ $? != 0 ]; then
     echo "failed."
     exit 1
@@ -107,24 +96,22 @@ initCBPolicyd() {
 
 while [ $# -gt 0 ]; do
   case "$1" in
-    -f|--force|-force)
-      force=1
-      shift
-      ;;
-    -h|-help|--help|help)
-      echo "$0 initializes the sqlite database for cbpolicyd"
-      echo "Usage: $0 [-force]"
-      exit
-      ;;
-    *)
-      echo "Unknown option $1"
-      echo "Usage: $0 [-force]"
-      exit 1
-      ;;
+  -f | --force | -force)
+    force=1
+    shift
+    ;;
+  -h | -help | --help | help)
+    echo "$0 initializes the sqlite database for cbpolicyd"
+    echo "Usage: $0 [-force]"
+    exit
+    ;;
+  *)
+    echo "Unknown option $1"
+    echo "Usage: $0 [-force]"
+    exit 1
+    ;;
   esac
 done
 
 initCBPolicyd
 exit 0
-  
-
diff --git a/src/libexec/zmclientcertmgr b/src/libexec/zmclientcertmgr
--- a/src/libexec/zmclientcertmgr
+++ b/src/libexec/zmclientcertmgr
@@ -1,34 +1,23 @@
 #!/bin/bash
-#
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2011, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-#
 
-if [ "$(whoami)" != "zimbra" ]; then
-  echo "$0 must be run as user zimbra"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ "$(whoami)" != "zextras" ]; then
+  echo "$0 must be run as user zextras"
   exit 1
 fi
 umask 027
 
-source /opt/zimbra/bin/zmshutil || exit 1
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars -f
 
 exp_thres_days=${zimbra_zmcertmgr_expiration_threshold:=30}
-exp_thres_secs=$(($exp_thres_days*24*60*60))
+exp_thres_secs=$(($exp_thres_days * 24 * 60 * 60))
 
-zimbra_domain_cert_directory=/opt/zimbra/conf/domaincerts
+zimbra_domain_cert_directory=/opt/zextras/conf/domaincerts
 
 ERROR_PREFIX="ERROR:"
 
@@ -50,7 +39,7 @@ saveConfigKey() {
   fi
 
   echo -n "** Saving $location config key $key..."
-  /opt/zimbra/bin/zmprov -m -l ${zmprov_opts} "$key" "$content" 2> /dev/null
+  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "$key" "$content" 2>/dev/null
   if [ $? = 0 ]; then
     echo "done."
   else
@@ -74,7 +63,7 @@ cleanConfigKey() {
   fi
 
   echo -n "** Clean $location config key $key..."
-  /opt/zimbra/bin/zmprov -m -l ${zmprov_opts} "$key" "" 2> /dev/null
+  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "$key" "" 2>/dev/null
   if [ $? = 0 ]; then
     echo "done."
   else
@@ -102,36 +91,39 @@ loadConfigKey() {
     return
   fi
   TMPDIR="${zimbra_tmp_directory}"
-  local tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || { echo "Failed to create tmpfile"; exit 1; }
+  local tmpfile=$(mktemp -t zmcertmgr.XXXXXX 2>/dev/null) || {
+    echo "Failed to create tmpfile"
+    exit 1
+  }
   if [ ! -s "$file" ]; then
     echo -n "** Retrieving $location config key $key..."
-    /opt/zimbra/bin/zmprov -m -l ${zmprov_opts} "${key}" | sed  -e 's/^${key}: //' > "$tmpfile" 2> /dev/null && mv -f "$tmpfile" "$file" 2> /dev/null
+    /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "${key}" | sed -e 's/^${key}: //' >"$tmpfile" 2>/dev/null && mv -f "$tmpfile" "$file" 2>/dev/null
     if [ $? = 0 -a -s "$file" ]; then
-      chmod 400 "$file" 2> /dev/null
+      chmod 400 "$file" 2>/dev/null
       echo "done."
     else
       echo "failed."
     fi
   fi
-  rm -f "$tmpfile" 2> /dev/null
+  rm -f "$tmpfile" 2>/dev/null
 }
 
 deployCerts() {
   if [ "$1" = "-force" ]; then
     if [ -d "$zimbra_domain_cert_directory" ]; then
-      rm -rf "$zimbra_domain_cert_directory" > /dev/null 2>&1
+      rm -rf "$zimbra_domain_cert_directory" >/dev/null 2>&1
     fi
   fi
 
-  DOMAINS=$(/opt/zimbra/bin/zmprov -m -l garpd | awk '{print $1}')
+  DOMAINS=$(/opt/zextras/bin/zmprov -m -l garpd | awk '{print $1}')
   if [ $? != 0 ]; then
-    echo "Unable to retrieve list of domains with SSL certificates";
+    echo "Unable to retrieve list of domains with SSL certificates"
     exit 1
   fi
 
   for i in ${DOMAINS}; do
     echo -n "** Deploying cert for $i..."
-    getClientCertFromLdap "$i" > /dev/null 2>&1
+    getClientCertFromLdap "$i" >/dev/null 2>&1
     if [ $? = 0 ]; then
       echo "done."
     else
@@ -189,7 +181,6 @@ cleanClientCertFromLdap() {
   cleanConfigKey "zimbraReverseProxyClientCertCA" "domain" "$domain"
 }
 
-
 getClientCertFromLdap() {
   domain=$1
   if [ "$domain" = "" ]; then
@@ -198,13 +189,13 @@ getClientCertFromLdap() {
   if [ ! -d "$zimbra_domain_cert_directory" ]; then
     mkdir -p "$zimbra_domain_cert_directory"
   fi
-  chmod 755 "$zimbra_domain_cert_directory" 2> /dev/null
+  chmod 755 "$zimbra_domain_cert_directory" 2>/dev/null
   current_crt="${zimbra_domain_cert_directory}/${domain}.client.crt"
 
   loadConfigKey "zimbraReverseProxyClientCertCA" "$current_crt" "domain" "$domain"
 }
 
-usage () {
+usage() {
   rc=${1:-1}
   echo "Usage:
   $0 -h | --help
@@ -215,7 +206,7 @@ usage () {
   $0 cleancrt server
   $0 cleancrt global
 "
-  exit $rc;
+  exit $rc
 }
 
 ###Main Execution###
diff --git a/src/libexec/zmdomaincertmgr b/src/libexec/zmdomaincertmgr
--- a/src/libexec/zmdomaincertmgr
+++ b/src/libexec/zmdomaincertmgr
@@ -1,47 +1,35 @@
 #!/bin/bash
-#
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2010, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-#
 
-if [ x`whoami` != "xzimbra" ]; then
-  echo "$0 must be run as user zimbra"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != "xzextras" ]; then
+  echo "$0 must be run as user zextras"
   exit 1
 fi
 umask 027
 
-platform=$(/opt/zimbra/libexec/get_plat_tag.sh 2> /dev/null := UNKNOWN)
-source /opt/zimbra/bin/zmshutil || exit 1
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars -f
 
 export JAVA_HOME=${zimbra_java_home}
 
-zimbra_conf_directory=/opt/zimbra/conf
+zimbra_conf_directory=/opt/zextras/conf
 exp_thres_days=${zimbra_zmcertmgr_expiration_threshold:=30}
-exp_thres_secs=$(($exp_thres_days*24*60*60))
+exp_thres_secs=$(($exp_thres_days * 24 * 60 * 60))
 
 zimbra_domain_cert_directory="${zimbra_conf_directory}/domaincerts"
 
-if [ -x "/opt/zimbra/common/bin/openssl" ]; then
-  openssl=/opt/zimbra/common/bin/openssl
+if [ -x "/opt/zextras/common/bin/openssl" ]; then
+  openssl=/opt/zextras/common/bin/openssl
 else
   openssl=openssl
 fi
 
 # this avoid "unable to write 'random state' errors from openssl
-export RANDFILE=/opt/zimbra/ssl/.rnd
+export RANDFILE=/opt/zextras/ssl/.rnd
 
 ERROR_PREFIX="ERROR:"
 
@@ -52,7 +40,7 @@ else
 fi
 
 isLdapRunning() {
-  /opt/zimbra/bin/ldap status > /dev/null 2>&1
+  /opt/zextras/bin/ldap status >/dev/null 2>&1
   LDAP_IS_RUNNING=$?
 }
 
@@ -60,7 +48,7 @@ saveConfigKey() {
   local key=$1
   local file=$2
   local location=$3
-  local content=`cat ${file}`
+  local content=$(cat ${file})
   if [ $location = "global" ]; then
     local zmprov_opts="mcf"
   elif [ $location = "server" ]; then
@@ -74,7 +62,7 @@ saveConfigKey() {
   fi
 
   echo -n "** Saving $location config key $key..."
-  /opt/zimbra/bin/zmprov -m -l ${zmprov_opts} "${key}" "$content" 2> /dev/null
+  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "${key}" "$content" 2>/dev/null
   if [ $? = 0 ]; then
     echo "done."
   else
@@ -102,12 +90,15 @@ loadConfigKey() {
     return
   fi
   TMPDIR=${zimbra_tmp_directory}
-  local tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || { echo "Failed to create tmpfile"; exit 1; }
+  local tmpfile=$(mktemp -t zmcertmgr.XXXXXX 2>/dev/null) || {
+    echo "Failed to create tmpfile"
+    exit 1
+  }
   if [ -s ${file} ]; then
     cp -a ${file} ${file}.$(date +%Y%m%d)
   fi
   echo -n "** Retrieving $location config key $key..."
-  /opt/zimbra/bin/zmprov -m -l ${zmprov_opts} "${key}" | sed  -e "s/^${key}: //" > ${tmpfile} 2> /dev/null
+  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "${key}" | sed -e "s/^${key}: //" >${tmpfile} 2>/dev/null
   if [ $? = 0 -a -s "${tmpfile}" ]; then
     chmod 400 ${tmpfile}
     mv -f ${tmpfile} ${file}
@@ -115,15 +106,15 @@ loadConfigKey() {
   else
     echo "failed."
   fi
-  rm -f ${tmpfile} 2> /dev/null
+  rm -f ${tmpfile} 2>/dev/null
 }
 
 deployCerts() {
   if [ "x$1" = "x-force" ] && [ -d "${zimbra_domain_cert_directory}" ]; then
-    rm -rf "${zimbra_domain_cert_directory}" > /dev/null 2>&1
+    rm -rf "${zimbra_domain_cert_directory}" >/dev/null 2>&1
   fi
 
-  DOMAINS=$(/opt/zimbra/bin/zmprov -m -l garpd | awk '{print $1}')
+  DOMAINS=$(/opt/zextras/bin/zmprov -m -l garpd | awk '{print $1}')
   if [ $? != 0 ]; then
     echo "$ERROR_PREFIX zmprov -m -l getAllReverseProxyDomains failed (rc=$?)."
     exit 1
@@ -137,7 +128,7 @@ deployCerts() {
 
   for i in $DOMAINS; do
     echo -n "** Deploying cert for ${i}..."
-    getDomainCertFromLdap $i > /dev/null 2>&1
+    getDomainCertFromLdap $i >/dev/null 2>&1
     if [ $? = 0 ]; then
       echo "done."
     else
@@ -191,7 +182,7 @@ viewstagedcrt() {
     else
       usage
     fi
-  elif [  x"${1}" != "xself" -a x"${1}" != "xcomm" ]; then
+  elif [ x"${1}" != "xself" -a x"${1}" != "xcomm" ]; then
     usage
   else
     type=$1
@@ -210,7 +201,7 @@ viewstagedcrt() {
     echo "$ERROR_PREFIX Certificate file ${current_crt} does not exist."
     usage
   fi
-  ${openssl} x509  -in ${current_crt} -dates -subject -issuer -noout
+  ${openssl} x509 -in ${current_crt} -dates -subject -issuer -noout
   getsubjectaltnames ${current_crt} crt
 }
 
@@ -220,17 +211,18 @@ getsubjectaltnames() {
     return
   fi
   case "${2}" in
-    "crt")
-      req=x509
-      ;;
-    "csr")
-      req="req"
-      ;;
-    *)
-      return
+  "crt")
+    req=x509
+    ;;
+  "csr")
+    req="req"
+    ;;
+  *)
+    return
+    ;;
   esac
 
-  names=`${openssl} $req -in ${cert} -text | sed -n '/Subject Alternative Name/{n;p;}' | sed 's/^[ \t]*//' | sed 's/DNS://g'`
+  names=$(${openssl} $req -in ${cert} -text | sed -n '/Subject Alternative Name/{n;p;}' | sed 's/^[ \t]*//' | sed 's/DNS://g')
   echo "SubjectAltName= $names"
 }
 
@@ -240,7 +232,7 @@ checkCertExpiration() {
     shift
     exp_thres_days=$1
     shift
-    exp_thres_secs=$((exp_thres_days*24*60*60))
+    exp_thres_secs=$((exp_thres_days * 24 * 60 * 60))
   fi
 
   if [ "x$1" = "x" ]; then
@@ -253,14 +245,14 @@ checkCertExpiration() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "mta" ]; then
-    service_crt=/opt/zimbra/conf/smtpd.crt
+    service_crt=/opt/zextras/conf/smtpd.crt
     #echo "::service mta::"
     if [ -f "${service_crt}" ]; then
-      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
       if [ $? != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
-        ${openssl} x509  -in ${service_crt} -enddate -noout
+        ${openssl} x509 -in ${service_crt} -enddate -noout
       fi
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -268,14 +260,14 @@ checkCertExpiration() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "proxy" ]; then
-    service_crt=/opt/zimbra/conf/nginx.crt
+    service_crt=/opt/zextras/conf/nginx.crt
     #echo "::service proxy::"
     if [ -f "${service_crt}" ]; then
-      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
       if [ $? != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
-        ${openssl} x509  -in ${service_crt} -enddate -noout
+        ${openssl} x509 -in ${service_crt} -enddate -noout
       fi
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -283,12 +275,15 @@ checkCertExpiration() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "mailboxd" ]; then
-    service_der=/opt/zimbra/mailboxd/etc/mailboxd.der
-    service_crt=/opt/zimbra/mailboxd/etc/mailboxd.pem
+    service_der=/opt/zextras/mailboxd/etc/mailboxd.der
+    service_crt=/opt/zextras/mailboxd/etc/mailboxd.pem
     #echo "::service mailboxd::"
-    tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || { echo "${ERROR_PREFIX} Failed to create tmpfile"; exit 1; }
+    tmpfile=$(mktemp -t zmcertmgr.XXXXXX 2>/dev/null) || {
+      echo "${ERROR_PREFIX} Failed to create tmpfile"
+      exit 1
+    }
     ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
-      -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} > ${tmpfile} 2>&1
+      -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} >${tmpfile} 2>&1
     if [ $? != 0 ]; then
       echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
       echo
@@ -297,12 +292,12 @@ checkCertExpiration() {
     fi
     rm -f $tmpfile 2>/dev/null
     if [ -f "${service_der}" ]; then
-      ${openssl} x509  -inform DER -outform PEM -in ${service_der} -out ${service_crt}
-      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      ${openssl} x509 -inform DER -outform PEM -in ${service_der} -out ${service_crt}
+      ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
       if [ $? != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
-        ${openssl} x509  -in ${service_crt} -enddate -noout
+        ${openssl} x509 -in ${service_crt} -enddate -noout
       fi
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -310,14 +305,14 @@ checkCertExpiration() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "ldap" ]; then
-    service_crt=/opt/zimbra/conf/slapd.crt
+    service_crt=/opt/zextras/conf/slapd.crt
     #echo "::service ldap::"
     if [ -f "${service_crt}" ]; then
-      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
       if [ $? != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
-        ${openssl} x509  -in ${service_crt} -enddate -noout
+        ${openssl} x509 -in ${service_crt} -enddate -noout
       fi
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -338,10 +333,10 @@ viewdeployedcrt() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "mta" ]; then
-    service_crt=/opt/zimbra/conf/smtpd.crt
+    service_crt=/opt/zextras/conf/smtpd.crt
     echo "::service mta::"
     if [ -f "${service_crt}" ]; then
-      ${openssl} x509  -in ${service_crt} -dates -subject -issuer -noout
+      ${openssl} x509 -in ${service_crt} -dates -subject -issuer -noout
       getsubjectaltnames $service_crt crt
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -349,10 +344,10 @@ viewdeployedcrt() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "proxy" ]; then
-    service_crt=/opt/zimbra/conf/nginx.crt
+    service_crt=/opt/zextras/conf/nginx.crt
     echo "::service proxy::"
     if [ -f "${service_crt}" ]; then
-      ${openssl} x509  -in ${service_crt} -dates -subject -issuer -noout
+      ${openssl} x509 -in ${service_crt} -dates -subject -issuer -noout
       getsubjectaltnames $service_crt crt
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -360,12 +355,15 @@ viewdeployedcrt() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "mailboxd" ]; then
-    service_der=/opt/zimbra/mailboxd/etc/mailboxd.der
-    service_crt=/opt/zimbra/mailboxd/etc/mailboxd.pem
+    service_der=/opt/zextras/mailboxd/etc/mailboxd.der
+    service_crt=/opt/zextras/mailboxd/etc/mailboxd.pem
     echo "::service mailboxd::"
-    tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || { echo "${ERROR_PREFIX} Failed to create tmpfile"; exit 1; }
+    tmpfile=$(mktemp -t zmcertmgr.XXXXXX 2>/dev/null) || {
+      echo "${ERROR_PREFIX} Failed to create tmpfile"
+      exit 1
+    }
     ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
-      -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} > ${tmpfile} 2>&1
+      -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} >${tmpfile} 2>&1
     if [ $? != 0 ]; then
       echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
       echo
@@ -374,8 +372,8 @@ viewdeployedcrt() {
     fi
     rm -f $tmpfile 2>/dev/null
     if [ -f "${service_der}" ]; then
-      ${openssl} x509  -inform DER -outform PEM -in ${service_der} -out ${service_crt}
-      ${openssl} x509  -in ${service_crt} -dates -subject -issuer -noout
+      ${openssl} x509 -inform DER -outform PEM -in ${service_der} -out ${service_crt}
+      ${openssl} x509 -in ${service_crt} -dates -subject -issuer -noout
       getsubjectaltnames $service_crt crt
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -383,10 +381,10 @@ viewdeployedcrt() {
   fi
 
   if [ $VIEW = "all" -o $VIEW = "ldap" ]; then
-    service_crt=/opt/zimbra/conf/slapd.crt
+    service_crt=/opt/zextras/conf/slapd.crt
     echo "::service ldap::"
     if [ -f "${service_crt}" ]; then
-      ${openssl} x509  -in ${service_crt} -dates -subject -issuer -noout
+      ${openssl} x509 -in ${service_crt} -dates -subject -issuer -noout
       getsubjectaltnames $service_crt crt
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
@@ -394,28 +392,27 @@ viewdeployedcrt() {
   fi
 }
 
-
 verifycrtkey() {
-  if [ x"${1}" = "x" ] || [  x"${1}" != "xself" -a x"${1}" != "xcomm" ]; then
+  if [ x"${1}" = "x" ] || [ x"${1}" != "xself" -a x"${1}" != "xcomm" ]; then
     usage
   else
     type=$1
     shift
     key=$1
     crt=$2
-    if [ x"${key}" = "x" ] ; then
+    if [ x"${key}" = "x" ]; then
       if [ "$type" = "self" ]; then
-          key=${server_key}
+        key=${server_key}
       elif [ "$type" = "comm" ]; then
-          key=${commercial_key}
+        key=${commercial_key}
       fi
     fi
 
-   if [ x"${crt}" = "x" ] ; then
+    if [ x"${crt}" = "x" ]; then
       if [ "$type" = "self" ]; then
-          crt=${server_crt}
+        crt=${server_crt}
       elif [ "$type" = "comm" ]; then
-          crt=${commercial_crt}
+        crt=${commercial_crt}
       fi
     fi
 
@@ -430,14 +427,14 @@ verifycrtkey() {
     echo "${ERROR_PREFIX} Can't find certificate ${crt} "
     exit 1
   else
-    key_md5=`${openssl} rsa -noout -modulus -in ${key} | ${openssl} md5`
-    crt_md5=`${openssl} x509 -noout -modulus -in ${crt} | ${openssl} md5`
+    key_md5=$(${openssl} rsa -noout -modulus -in ${key} | ${openssl} md5)
+    crt_md5=$(${openssl} x509 -noout -modulus -in ${crt} | ${openssl} md5)
 
     #echo "key_md5=${key_md5}"
     #echo "crt_md5=${crt_md5}"
   fi
 
-  if [ x"${key_md5}" != "x"  -a  x"${key_md5}" = x"${crt_md5}" ] ; then
+  if [ x"${key_md5}" != "x" -a x"${key_md5}" = x"${crt_md5}" ]; then
     echo "Certificate (${crt}) and private key (${key}) match."
   else
     echo "${ERROR_PREFIX} Unmatching certificate (${crt}) and private key (${key}) pair."
@@ -445,24 +442,23 @@ verifycrtkey() {
   fi
 }
 
-verifycrtchain () {
-    cafile=$1
-    crt=$2
+verifycrtchain() {
+  cafile=$1
+  crt=$2
 
-    result=`${openssl} verify -purpose sslserver -CAfile $cafile $crt`
+  result=$(${openssl} verify -purpose sslserver -CAfile $cafile $crt)
 
-    if [ x"${result}" = x"${crt}: OK" ]; then
-        echo "Valid Certificate Chain: $result"
-    else
-      echo "${ERROR_PREFIX} Invalid Certificate Chain: $result"
-      exit 1
-    fi
+  if [ x"${result}" = x"${crt}: OK" ]; then
+    echo "Valid Certificate Chain: $result"
+  else
+    echo "${ERROR_PREFIX} Invalid Certificate Chain: $result"
+    exit 1
+  fi
 }
-
 
 ###Main Execution###
 
-usage () {
+usage() {
   echo "Usage: "
   echo "  $0 -help"
   echo "  $0 deploycrts"
@@ -475,7 +471,6 @@ usage () {
 
   exit 1
 }
-
 
 if [ $# = 0 ]; then
   usage
diff --git a/src/libexec/zmloggerinit b/src/libexec/zmloggerinit
--- a/src/libexec/zmloggerinit
+++ b/src/libexec/zmloggerinit
@@ -1,35 +1,24 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
+
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 #
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
+# SPDX-License-Identifier: GPL-2.0-only
 
 #
-if [ x`whoami` != "xzimbra" ]; then
-  echo "Error: must be run as user zimbra"
+if [ x$(whoami) != "xzextras" ]; then
+  echo "Error: must be run as user zextras"
   exit 1
 fi
 
 umask 027
-source /opt/zimbra/bin/zmshutil || exit 1
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars
 
 # Get the root directory for the logger db data and construct directory name to move old data to
-logger_data_dir_base="`dirname ${logger_data_directory}`"
-backup_logger_dir="`dirname ${logger_data_dir_base}`/`basename ${logger_data_dir_base}`-`date +%Y%m%d.%H%M`"
-tmp_logger_dir="`dirname ${logger_data_dir_base}`/`basename ${logger_data_dir_base}`-tmp"
+logger_data_dir_base="$(dirname ${logger_data_directory})"
+backup_logger_dir="$(dirname ${logger_data_dir_base})/$(basename ${logger_data_dir_base})-$(date +%Y%m%d.%H%M)"
+tmp_logger_dir="$(dirname ${logger_data_dir_base})/$(basename ${logger_data_dir_base})-tmp"
 
 # Make the switchout action as atomic as possible.  So, prep new dir structures in "tmp" root logger data dir first.
 mkdir -p ${tmp_logger_dir}/data/rrds ${tmp_logger_dir}/work
diff --git a/src/libexec/zmmyinit b/src/libexec/zmmyinit
--- a/src/libexec/zmmyinit
+++ b/src/libexec/zmmyinit
@@ -1,23 +1,12 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != "xzimbra" ]; then
-  echo "Error: must be run as user zimbra"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x$(whoami) != "xzextras" ]; then
+  echo "Error: must be run as user zextras"
   exit 1
 fi
 
@@ -27,48 +16,48 @@ usage() {
   echo "  --mysql_memory_percent defaults to 30 percent if not specified."
 }
 
-source /opt/zimbra/bin/zmshutil || exit 1
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars -f
 
 #
 # Sanity checks
 #
-zmassert -x /opt/zimbra/libexec/zmmycnf
-zmassert -x /opt/zimbra/bin/mysqladmin
-zmassert -x /opt/zimbra/bin/mysql
-zmassert -x /opt/zimbra/bin/zmlocalconfig
-zmassert -x /opt/zimbra/bin/zmmypasswd
-zmassert -x /opt/zimbra/common/share/mysql/scripts/mysql_install_db
+zmassert -x /opt/zextras/libexec/zmmycnf
+zmassert -x /opt/zextras/bin/mysqladmin
+zmassert -x /opt/zextras/bin/mysql
+zmassert -x /opt/zextras/bin/zmlocalconfig
+zmassert -x /opt/zextras/bin/zmmypasswd
+zmassert -x /opt/zextras/common/share/mysql/scripts/mysql_install_db
 zmassert -r ${zimbra_db_directory}/db.sql
 zmassert -r ${zimbra_db_directory}/versions-init.sql
 
 for opt in "$@"; do
   case "$opt" in
-    -help|--help|-h|--help)
-      usage
-      exit 0
-      shift
-      ;;
-    -verbose|--verbose|-v|--v)
-      verbose=yes
-      shift
-      ;;
-    --sql_root_pw)
-      shift
-      sql_root_pw=$1
-      shift
-      ;;
-    --mysql_memory_percent)
-      shift
-      mysql_memory_percent=$1
-      shift
-      ;;
-    --*|-*)
-      echo "Unknown option $opt"
-      usage
-      exit 1
-      shift
-      ;;
+  -help | --help | -h | --help)
+    usage
+    exit 0
+    shift
+    ;;
+  -verbose | --verbose | -v | --v)
+    verbose=yes
+    shift
+    ;;
+  --sql_root_pw)
+    shift
+    sql_root_pw=$1
+    shift
+    ;;
+  --mysql_memory_percent)
+    shift
+    mysql_memory_percent=$1
+    shift
+    ;;
+  --* | -*)
+    echo "Unknown option $opt"
+    usage
+    exit 1
+    shift
+    ;;
   esac
 done
 
@@ -91,33 +80,33 @@ mkdir -p ${zimbra_log_directory}
 #
 echo '*' Generating mysql config ${mysql_mycnf}
 rm -f ${mysql_mycnf}
-/opt/zimbra/libexec/zmmycnf --innodb-buffer-pool-memory-percent \
-  $mysql_memory_percent > ${mysql_mycnf}
+/opt/zextras/libexec/zmmycnf --innodb-buffer-pool-memory-percent \
+  $mysql_memory_percent >${mysql_mycnf}
 
 #
 # Create database
 #
 echo '*' Creating database in ${mysql_data_directory}
-(/opt/zimbra/common/share/mysql/scripts/mysql_install_db \
-    --basedir=/opt/zimbra/common \
-    --defaults-file=${mysql_mycnf}) \
-    >> ${zimbra_log_directory}/zmmyinit.log 2>&1
+(/opt/zextras/common/share/mysql/scripts/mysql_install_db \
+  --basedir=/opt/zextras/common \
+  --defaults-file=${mysql_mycnf}) \
+  >>${zimbra_log_directory}/zmmyinit.log 2>&1
 
 #
 # Start mysql server
 #
 echo '*' Starting mysql server
-/opt/zimbra/bin/mysql.server start \
-    >> ${zimbra_log_directory}/zmmyinit.log 2>&1
+/opt/zextras/bin/mysql.server start \
+  >>${zimbra_log_directory}/zmmyinit.log 2>&1
 
-# make sure we can connect before continuing 
-until `echo "show processlist" | /opt/zimbra/bin/mysql -u root --password= > /dev/null 2>&1`; do
+# make sure we can connect before continuing
+until $(echo "show processlist" | /opt/zextras/bin/mysql -u root --password= >/dev/null 2>&1); do
   let i++
   sleep 5
   if [ $i -gt 25 ]; then
     echo '*' Failed to connect to mysql...giving up!
     exit -1
-  else 
+  else
     echo '*' Failed to connect to mysql...retrying
   fi
 done
@@ -125,62 +114,62 @@ done
 #
 # Load zimbra sql files
 #
-echo '*' Loading schema ${zimbra_db_directory}/db.sql 
-/opt/zimbra/bin/mysql -u root --password= < \
-    ${zimbra_db_directory}/db.sql
+echo '*' Loading schema ${zimbra_db_directory}/db.sql
+/opt/zextras/bin/mysql -u root --password= < \
+  ${zimbra_db_directory}/db.sql
 
-if [ -f "${zimbra_db_directory}/create_sharing_database.sql" ];then
-  echo '*' Loading schema ${zimbra_db_directory}/create_sharing_database.sql 
-  /opt/zimbra/bin/mysql -u root --password= < \
-      ${zimbra_db_directory}/create_sharing_database.sql
+if [ -f "${zimbra_db_directory}/create_sharing_database.sql" ]; then
+  echo '*' Loading schema ${zimbra_db_directory}/create_sharing_database.sql
+  /opt/zextras/bin/mysql -u root --password= < \
+    ${zimbra_db_directory}/create_sharing_database.sql
 fi
 
 echo '*' Loading version from ${zimbra_db_directory}/versions-init.sql
-/opt/zimbra/bin/mysql -u root --password= < \
-    ${zimbra_db_directory}/versions-init.sql
+/opt/zextras/bin/mysql -u root --password= < \
+  ${zimbra_db_directory}/versions-init.sql
 
 if [ -f "${zimbra_db_directory}/backup-version-init.sql" ]; then
   echo '*' Loading version from ${zimbra_db_directory}/backup-version-init.sql
-  /opt/zimbra/bin/mysql -u root --password= < \
+  /opt/zextras/bin/mysql -u root --password= < \
     ${zimbra_db_directory}/backup-version-init.sql
 fi
 
 #
 # Delete wildcard user login entries
 #
-/opt/zimbra/bin/mysql -u root --password= -e "DROP USER ''@'localhost'; DROP USER ''@'`hostname`';"
+/opt/zextras/bin/mysql -u root --password= -e "DROP USER ''@'localhost'; DROP USER ''@'$(hostname)';"
 
 #
 # Generate passwords for mysql into local config
 #
 if [ x$sql_root_pw = "x" ]; then
-    echo '*' Setting random passwd for mysql root user in zimbra localconfig
-    /opt/zimbra/bin/zmlocalconfig -r -f -e mysql_root_password
-    
-    echo '*' Setting random passwd for mysql zimbra user in zimbra localconfig
-    /opt/zimbra/bin/zmlocalconfig -r -f -e zimbra_mysql_password
+  echo '*' Setting random passwd for mysql root user in zimbra localconfig
+  /opt/zextras/bin/zmlocalconfig -r -f -e mysql_root_password
+
+  echo '*' Setting random passwd for mysql zextras user in zimbra localconfig
+  /opt/zextras/bin/zmlocalconfig -r -f -e zimbra_mysql_password
 else
-    echo '*' Setting passwd for mysql root user in zimbra localconfig
-    /opt/zimbra/bin/zmlocalconfig -f -e mysql_root_password=$sql_root_pw
-    echo '*' Setting passwd for mysql zimbra user in zimbra localconfig
-    /opt/zimbra/bin/zmlocalconfig -f -e zimbra_mysql_password=$sql_root_pw
+  echo '*' Setting passwd for mysql root user in zimbra localconfig
+  /opt/zextras/bin/zmlocalconfig -f -e mysql_root_password=$sql_root_pw
+  echo '*' Setting passwd for mysql zextras user in zimbra localconfig
+  /opt/zextras/bin/zmlocalconfig -f -e zimbra_mysql_password=$sql_root_pw
 fi
 
 #
-# Change mysql root user password, but first read back the passwords 
+# Change mysql root user password, but first read back the passwords
 # zimbra local config - they was generated above.  Note that we can not
 # use 'zmmypasswd --root' here because of bootstrapping problems - at
 # this stage we know that the root password is empty.
 #
 zmsetvars -f
 echo '*' Changing mysql root user password
-cat <<EOF | /opt/zimbra/bin/mysql -u root --password=
+cat <<EOF | /opt/zextras/bin/mysql -u root --password=
     SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${mysql_root_password}');
-    SET PASSWORD FOR 'root'@'`hostname`' = PASSWORD('${mysql_root_password}');
+    SET PASSWORD FOR 'root'@'$(hostname)' = PASSWORD('${mysql_root_password}');
     SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('${mysql_root_password}');
     SET PASSWORD FOR 'root'@'::1' = PASSWORD('${mysql_root_password}');
     SET PASSWORD FOR 'root'@'localhost.localdomain' = PASSWORD('${mysql_root_password}');
 EOF
 
-echo '*' Changing mysql zimbra user password
-/opt/zimbra/bin/zmmypasswd ${zimbra_mysql_password}
+echo '*' Changing mysql zextras user password
+/opt/zextras/bin/zmmypasswd ${zimbra_mysql_password}
diff --git a/src/libexec/zmresetmysqlpassword b/src/libexec/zmresetmysqlpassword
--- a/src/libexec/zmresetmysqlpassword
+++ b/src/libexec/zmresetmysqlpassword
@@ -1,38 +1,27 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2010, 2011, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-if [ x`whoami` != "xzimbra" ]; then
-  echo "Error: must be run as user zimbra"
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+if [ x`whoami` != "xzextras" ]; then
+  echo "Error: must be run as user zextras"
   exit 1
 fi
 
-source /opt/zimbra/bin/zmshutil || exit 1
+source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars -f
 
 #
 # Sanity checks
 #
-zmassert -x /opt/zimbra/common/bin/mysqladmin
-zmassert -x /opt/zimbra/common/bin/mysql
-zmassert -x /opt/zimbra/bin/zmlocalconfig
-zmassert -x /opt/zimbra/bin/zmcontrol
+zmassert -x /opt/zextras/common/bin/mysqladmin
+zmassert -x /opt/zextras/common/bin/mysql
+zmassert -x /opt/zextras/bin/zmlocalconfig
+zmassert -x /opt/zextras/bin/zmcontrol
 zmassert -r ${zimbra_db_directory}/db.sql
-if [ ! -x /opt/zimbra/common/bin/mysql ]; then
+if [ ! -x /opt/zextras/common/bin/mysql ]; then
   echo "Mysql not found on this host."
   exit 1
 fi
@@ -116,23 +105,23 @@ if [ $response != "yes" ]; then
   exit
 fi
 
-/opt/zimbra/bin/zmcontrol stop
+/opt/zextras/bin/zmcontrol stop
 
 echo "Starting mysqld"
-/opt/zimbra/common/bin/mysqld_safe --defaults-file=${mysql_mycnf} --skip-grant-tables --ledir=/opt/zimbra/common/sbin &
+/opt/zextras/common/bin/mysqld_safe --defaults-file=${mysql_mycnf} --skip-grant-tables --ledir=/opt/zextras/common/sbin &
 sleep 10
 
-echo "Changing zimbra passwd"
-/opt/zimbra/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'zimbra';"
-/opt/zimbra/bin/zmlocalconfig -f -e zimbra_mysql_password=$password
+echo "Changing zextras passwd"
+/opt/zextras/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'zextras';"
+/opt/zextras/bin/zmlocalconfig -f -e zimbra_mysql_password=$password
 
 echo "Changing root passwd"
-/opt/zimbra/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'root';"
-/opt/zimbra/bin/zmlocalconfig -f -e mysql_root_password=$password
+/opt/zextras/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'root';"
+/opt/zextras/bin/zmlocalconfig -f -e mysql_root_password=$password
 
 echo "Flushing privileges";
-/opt/zimbra/bin/mysql -Dmysql -P ${mysql_port} -e "flush privileges;"
-/opt/zimbra/bin/mysql.server stop
+/opt/zextras/bin/mysql -Dmysql -P ${mysql_port} -e "flush privileges;"
+/opt/zextras/bin/mysql.server stop
 
-echo "Restarting zimbra services"
-/opt/zimbra/bin/zmcontrol start
+echo "Restarting carbonio services"
+/opt/zextras/bin/zmcontrol start
diff --git a/src/libexec/zmsacompile b/src/libexec/zmsacompile
--- a/src/libexec/zmsacompile
+++ b/src/libexec/zmsacompile
@@ -1,32 +1,36 @@
 #!/bin/bash
 
-if [ ! -x /opt/zimbra/common/sbin/amavisd ]; then
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: AGPL-3.0-only
+
+if [ ! -x /opt/zextras/common/sbin/amavisd ]; then
   echo "Error: Must be run on an MTA"
   exit 1
 fi
 
-u=`id -un`
-if [ $u != "zimbra" ]; then
-    echo "Error: must be run as the zimbra user"
-    exit 1
+u=$(id -un)
+if [ $u != "zextras" ]; then
+  echo "Error: must be run as the zextras user"
+  exit 1
 fi
 
-re2c=`which re2c`
+re2c=$(which re2c)
 if [ x"$re2c" = "x" ]; then
   echo "Error: re2c is required to compile rules"
   exit 1
 fi
 
-make=`which make`
+make=$(which make)
 if [ x"$make" = "x" ]; then
   echo "Error: make is required to compile rules"
   exit 1
 fi
 
-NICE=`which nice`
+NICE=$(which nice)
 if [ x"$NICE" = "x" ]; then
-  /opt/zimbra/common/bin/sa-compile >/dev/null 2>&1
+  /opt/zextras/common/bin/sa-compile >/dev/null 2>&1
 else
   NICED="$NICE -n 19"
-  $NICED /opt/zimbra/common/bin/sa-compile >/dev/null 2>&1
+  $NICED /opt/zextras/common/bin/sa-compile >/dev/null 2>&1
 fi
diff --git a/src/libexec/zmslapadd b/src/libexec/zmslapadd
--- a/src/libexec/zmslapadd
+++ b/src/libexec/zmslapadd
@@ -1,124 +1,115 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
-ulimit -n 32768
-ulimit -c unlimited
-ulimit -v unlimited
-export LD_PRELOAD=/opt/zimbra/common/lib/libtcmalloc_minimal.so
 
-umask 027
-source /opt/zimbra/bin/zmshutil || exit 1
-zmsetvars
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
 
-if [ ! -x /opt/zimbra/common/sbin/slapadd ]; then
-	exit 0
+if [ ! -f /.dockerenv ]; then
+  ulimit -n 32768
+  ulimit -c unlimited
+  ulimit -v unlimited
 fi
 
-u=`id -un`
+umask 027
+source /opt/zextras/bin/zmshutil || exit 1
+zmsetvars
+
+if [ ! -x /opt/zextras/common/sbin/slapadd ]; then
+  exit 0
+fi
+
+u=$(id -un)
 if [ $u != ${zimbra_user} ]; then
-    echo "Error: must be run as ${zimbra_user} user"
-    exit 1
+  echo "Error: must be run as ${zimbra_user} user"
+  exit 1
 fi
 
 zgood=no
 bgood=no
-zcat=`which zcat 2>/dev/null`
-bzcat=`which bzcat 2>/dev/null`
+zcat=$(which zcat 2>/dev/null)
+bzcat=$(which bzcat 2>/dev/null)
 
 if [ -x $zcat ]; then
-	zgood=yes
+  zgood=yes
 fi
 
 if [ -x $bzcat ]; then
-	bgood=yes
+  bgood=yes
 fi
 
 if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
-	echo "USAGE: Imports LDAP databases"
-	echo "Main database: zmslapadd <FILE> [-w]"
-	echo "Config database: zmslapadd -c <FILE>"
-	echo "Accesslog database: zmslapadd -a <FILE>"
-	exit 1
+  echo "USAGE: Imports LDAP databases"
+  echo "Main database: zmslapadd <FILE> [-w]"
+  echo "Config database: zmslapadd -c <FILE>"
+  echo "Accesslog database: zmslapadd -a <FILE>"
+  exit 1
 fi
 
 CONFIG=no
 ALOG=no
 WRITESYNCREPL=""
 if [ x$1 = "x-c" ]; then
-	CONFIG=yes
-	SRC=$2
+  CONFIG=yes
+  SRC=$2
 elif [ x$1 = "x-a" ]; then
-	ALOG=yes
-	SRC=$2
+  ALOG=yes
+  SRC=$2
 else
-	SRC=$1
-	if [ x$2 = "x-w" ]; then
-		WRITESYNCREPL=$2
-	fi
+  SRC=$1
+  if [ x$2 = "x-w" ]; then
+    WRITESYNCREPL=$2
+  fi
 fi
 
 comp=0
 computil=
 
 if [ ! -f $SRC ]; then
-	echo "Error: Input file does not exist"
-	exit 1
+  echo "Error: Input file does not exist"
+  exit 1
 fi
 
 if [[ "$SRC" == *".gz" ]]; then
-	if [ x$zgood = "xno" ]; then
-		echo "Error: zcat is missing."
-		exit 1
-	fi
-	computil=$zcat
-	comp=1
+  if [ x$zgood = "xno" ]; then
+    echo "Error: zcat is missing."
+    exit 1
+  fi
+  computil=$zcat
+  comp=1
 elif [[ "$SRC" == *".bz2" ]]; then
-	if [ x$bgood = "xno" ]; then
-		echo "Error: bzcat is missing."
-		exit 1
-	fi
-	computil=$bzcat
-	comp=1
+  if [ x$bgood = "xno" ]; then
+    echo "Error: bzcat is missing."
+    exit 1
+  fi
+  computil=$bzcat
+  comp=1
 fi
 
 if [ x$CONFIG = "xyes" ]; then
-	if [ x$comp = "x0" ]; then
-		/opt/zimbra/common/sbin/slapadd -q -F /opt/zimbra/data/ldap/config -n 0 -l $SRC
-		RETVAL=$?
-	else
-		$computil $SRC | /opt/zimbra/common/sbin/slapadd -q -F /opt/zimbra/data/ldap/config -n 0
-		RETVAL=$?
-	fi
+  if [ x$comp = "x0" ]; then
+    /opt/zextras/common/sbin/slapadd -q -F /opt/zextras/data/ldap/config -n 0 -l $SRC
+    RETVAL=$?
+  else
+    $computil $SRC | /opt/zextras/common/sbin/slapadd -q -F /opt/zextras/data/ldap/config -n 0
+    RETVAL=$?
+  fi
 elif [ x$ALOG = "xyes" ]; then
-	if [ x$comp = "x0" ]; then
-		/opt/zimbra/common/sbin/slapadd -q -F /opt/zimbra/data/ldap/config -b "cn=accesslog" -l $SRC
-		RETVAL=$?
-	else
-		$computil $SRC | /opt/zimbra/common/sbin/slapadd -q -F /opt/zimbra/data/ldap/config -b "cn=accesslog"
-		RETVAL=$?
-	fi
+  if [ x$comp = "x0" ]; then
+    /opt/zextras/common/sbin/slapadd -q -F /opt/zextras/data/ldap/config -b "cn=accesslog" -l $SRC
+    RETVAL=$?
+  else
+    $computil $SRC | /opt/zextras/common/sbin/slapadd -q -F /opt/zextras/data/ldap/config -b "cn=accesslog"
+    RETVAL=$?
+  fi
 else
-	if [ x$comp = "x0" ]; then
-		/opt/zimbra/common/sbin/slapadd $WRITESYNCREPL -q -F /opt/zimbra/data/ldap/config -b "" -l $SRC
-		RETVAL=$?
-	else
-		$computil $SRC | /opt/zimbra/common/sbin/slapadd $WRITESYNCREPL -q -F /opt/zimbra/data/ldap/config -b ""
-		RETVAL=$?
-	fi
+  if [ x$comp = "x0" ]; then
+    /opt/zextras/common/sbin/slapadd $WRITESYNCREPL -q -F /opt/zextras/data/ldap/config -b "" -l $SRC
+    RETVAL=$?
+  else
+    $computil $SRC | /opt/zextras/common/sbin/slapadd $WRITESYNCREPL -q -F /opt/zextras/data/ldap/config -b ""
+    RETVAL=$?
+  fi
 fi
 
 exit $RETVAL
diff --git a/src/libexec/zmslapcat b/src/libexec/zmslapcat
--- a/src/libexec/zmslapcat
+++ b/src/libexec/zmslapcat
@@ -1,80 +1,71 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2013, 2014, 2015, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
-ulimit -n 32768
-ulimit -c unlimited
-ulimit -v unlimited
-export LD_PRELOAD=/opt/zimbra/common/lib/libtcmalloc_minimal.so
 
-umask 027
-source /opt/zimbra/bin/zmshutil || exit 1
-zmsetvars
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
 
-if [ ! -x /opt/zimbra/common/sbin/slapcat ]; then
-	exit 0
+if [ ! -f /.dockerenv ]; then
+  ulimit -n 32768
+  ulimit -c unlimited
+  ulimit -v unlimited
 fi
 
-u=`id -un`
+umask 027
+source /opt/zextras/bin/zmshutil || exit 1
+zmsetvars
+
+if [ ! -x /opt/zextras/common/sbin/slapcat ]; then
+  exit 0
+fi
+
+u=$(id -un)
 if [ $u != ${zimbra_user} ]; then
-    echo "Error: must be run as ${zimbra_user} user"
-    exit 1
+  echo "Error: must be run as ${zimbra_user} user"
+  exit 1
 fi
 
 if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
-	echo "USAGE: Exports LDAP databases"
-	echo "Main database: zmslapcat <DIR>"
-	echo "Config database: zmslapcat -c <DIR>"
-	echo "Accesslog database: zmslapcat -a <DIR>"
-	exit 1
+  echo "USAGE: Exports LDAP databases"
+  echo "Main database: zmslapcat <DIR>"
+  echo "Config database: zmslapcat -c <DIR>"
+  echo "Accesslog database: zmslapcat -a <DIR>"
+  exit 1
 fi
 
-D=`date +%Y%m%d%H%M%S`
+D=$(date +%Y%m%d%H%M%S)
 CONFIG=no
 FILE=ldap.bak.${D}
 NFILE=ldap.bak
 if [ x$1 = "x-c" ]; then
-	CONFIG=yes
-	FILE=ldap-config.bak.${D}
-	NFILE=ldap-config.bak
-	DEST=$2
+  CONFIG=yes
+  FILE=ldap-config.bak.${D}
+  NFILE=ldap-config.bak
+  DEST=$2
 elif [ x$1 = "x-a" ]; then
-	ALOG=yes
-	FILE=ldap-accesslog.bak.${D}
-	NFILE=ldap-accesslog.bak
-	DEST=$2
+  ALOG=yes
+  FILE=ldap-accesslog.bak.${D}
+  NFILE=ldap-accesslog.bak
+  DEST=$2
 else
-	DEST=$1
+  DEST=$1
 fi
 
 mkdir -p $DEST
 RC=0
 if [ x$CONFIG = "xyes" ]; then
-	/opt/zimbra/common/sbin/slapcat -F /opt/zimbra/data/ldap/config -n 0 -l ${DEST}/${FILE}
-	RC=$?
+  /opt/zextras/common/sbin/slapcat -F /opt/zextras/data/ldap/config -n 0 -l ${DEST}/${FILE}
+  RC=$?
 elif [ x$ALOG = "xyes" ]; then
-	if [ -d /opt/zimbra/data/ldap/accesslog/db ]; then
-		/opt/zimbra/common/sbin/slapcat -F /opt/zimbra/data/ldap/config -b "cn=accesslog" -l ${DEST}/${FILE}
-		RC=$?
-	else
-		exit $RC
-	fi
+  if [ -d /opt/zextras/data/ldap/accesslog/db ]; then
+    /opt/zextras/common/sbin/slapcat -F /opt/zextras/data/ldap/config -b "cn=accesslog" -l ${DEST}/${FILE}
+    RC=$?
+  else
+    exit $RC
+  fi
 else
-	/opt/zimbra/common/sbin/slapcat -F /opt/zimbra/data/ldap/config -b "" -l ${DEST}/${FILE}
-	RC=$?
+  /opt/zextras/common/sbin/slapcat -F /opt/zextras/data/ldap/config -b "" -l ${DEST}/${FILE}
+  RC=$?
 fi
 
 cp -f ${DEST}/${FILE} ${DEST}/${NFILE}
diff --git a/src/libexec/zmstat-cleanup b/src/libexec/zmstat-cleanup
--- a/src/libexec/zmstat-cleanup
+++ b/src/libexec/zmstat-cleanup
@@ -1,94 +1,71 @@
 #!/bin/bash
-# 
-# ***** BEGIN LICENSE BLOCK *****
-# Zimbra Collaboration Suite Server
-# Copyright (C) 2010, 2013, 2014, 2016 Synacor, Inc.
-#
-# This program is free software: you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software Foundation,
-# version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-# See the GNU General Public License for more details.
-# You should have received a copy of the GNU General Public License along with this program.
-# If not, see <https://www.gnu.org/licenses/>.
-# ***** END LICENSE BLOCK *****
-# 
 
-source /opt/zimbra/bin/zmshutil || exit 1
+# SPDX-FileCopyrightText: 2022 Synacor, Inc.
+# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
+#
+# SPDX-License-Identifier: GPL-2.0-only
+
+source /opt/zextras/bin/zmshutil || exit 1
 
 usage() {
-    echo "Usage: $0 [-k <keep count>] [-h] [-l] [-p]"
-    echo ""
-    echo "    -h|--help    Help/usage information"
-    echo "    -k|--keep    Number of archived copies of zmstat data to retain."
-    echo "    -l|--list    Generate a listing of log dates archived."
-    echo "    -p|--purge   Purge ALL archived zmstats data."
-    echo ""
-    exit
+  echo "Usage: $0 [-k <keep count>] [-h] [-l] [-p]"
+  echo ""
+  echo "    -h|--help    Help/usage information"
+  echo "    -k|--keep    Number of archived copies of zmstat data to retain."
+  echo "    -l|--list    Generate a listing of log dates archived."
+  echo "    -p|--purge   Purge ALL archived zmstats data."
+  echo ""
+  exit
 }
 
 zmsetvars
 
-
-while [ $# -gt 0 ]
-do
-    case $1 in
-        -h | --help)
-            usage
-            ;;
-        -k | --keep)
-            shift
-            zmstat_max_retention=$1
-            ;;
-        -l | --list)
-            listArchives=TRUE
-            ;;
-        -p | --purge)
-            purgeAll=TRUE
-            ;;
-        *)
-            echo "ERROR: Unknown option $1"
-            usage
-            ;;
-    esac
+while [ $# -gt 0 ]; do
+  case $1 in
+  -h | --help)
+    usage
+    ;;
+  -k | --keep)
     shift
+    zmstat_max_retention=$1
+    ;;
+  -l | --list)
+    listArchives=TRUE
+    ;;
+  -p | --purge)
+    purgeAll=TRUE
+    ;;
+  *)
+    echo "ERROR: Unknown option $1"
+    usage
+    ;;
+  esac
+  shift
 done
 
-
-cd /opt/zimbra/zmstat 2>/dev/null
-if [ $? -ne 0 -o "${PWD}" != "/opt/zimbra/zmstat" ]
-then
-    echo "ERROR: Cannot change to the zmstats log directory /opt/zimbra/zmstat."
-    exit -1
+cd /opt/zextras/zmstat 2>/dev/null
+if [ $? -ne 0 -o "${PWD}" != "/opt/zextras/zmstat" ]; then
+  echo "ERROR: Cannot change to the zmstats log directory /opt/zextras/zmstat."
+  exit -1
 fi
 
+if [ "${listArchives}x" == "TRUEx" ]; then
+  if [ "$(ls -1A | egrep '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | wc -l)" -gt 0 ]; then
+    /bin/ls -d1 [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
+  fi
+elif [ "${purgeAll}x" == "TRUEx" ]; then
+  DIR_LIST=$(find . -type d -print | egrep '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "s%./%%")
+  for d in ${DIR_LIST}; do
+    echo "Deleting ${d} zmstat archive."
+    /bin/rm -rf ${d}
+  done
+elif [ ${zmstat_max_retention:-"0"} -gt 0 ]; then
+  DIR_LIST=$(find . -type d -print | egrep '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "1,${zmstat_max_retention}d ; s%./%%")
 
-if [ "${listArchives}x" == "TRUEx" ]
-then
-    if [ "`ls -1A | egrep '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | wc -l`" -gt 0 ]
-    then
-        /bin/ls -d1 [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
-    fi
-elif [ "${purgeAll}x" == "TRUEx" ]
-then
-    DIR_LIST=`find . -type d -print | egrep '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "s%./%%"`
-    for d in ${DIR_LIST}
-    do
-        echo "Deleting ${d} zmstat archive."
-        /bin/rm -rf ${d}
-    done
-elif [ ${zmstat_max_retention:-"0"} -gt 0 ]
-then
-    DIR_LIST=`find . -type d -print | egrep '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "1,${zmstat_max_retention}d ; s%./%%"`
-
-    for d in ${DIR_LIST}
-    do
-        echo "Deleting ${d} zmstat archive."
-        /bin/rm -rf ${d}
-    done
+  for d in ${DIR_LIST}; do
+    echo "Deleting ${d} zmstat archive."
+    /bin/rm -rf ${d}
+  done
 else
-    echo "WARNING: zmstat_max_retention is set to 0 or is undefined.  No zmstat data has been pruned."
+  echo "WARNING: zmstat_max_retention is set to 0 or is undefined.  No zmstat data has been pruned."
 fi
-
