chore: apply shfmt indentations to all shell scripts

diff --git a/src/bin/zmfreshclamctl b/src/bin/zmfreshclamctl
--- a/src/bin/zmfreshclamctl
+++ b/src/bin/zmfreshclamctl
@@ -59,72 +59,72 @@ pskillall() {
 # Main
 #
 case "$1" in
-'start')
+  'start')
 
-  if [ x$2 = "x" ]; then
-    rewriteconfig
-  fi
+    if [ x$2 = "x" ]; then
+      rewriteconfig
+    fi
 
-  checkrunning
-  echo -n "Starting freshclam..."
-  if [ $frunning = 1 ]; then
-    echo "freshclam is already running."
-  else
-    /opt/zextras/common/bin/freshclam \
-      --config-file=/opt/zextras/conf/freshclam.conf --quiet --daemon --checks=12 \
-      >>${zimbra_log_directory}/freshclam.log 2>&1 &
-    echo "done."
-  fi
-  exit 0
-  ;;
+    checkrunning
+    echo -n "Starting freshclam..."
+    if [ $frunning = 1 ]; then
+      echo "freshclam is already running."
+    else
+      /opt/zextras/common/bin/freshclam \
+        --config-file=/opt/zextras/conf/freshclam.conf --quiet --daemon --checks=12 \
+        >>${zimbra_log_directory}/freshclam.log 2>&1 &
+      echo "done."
+    fi
+    exit 0
+    ;;
 
-'kill')
-  if [ -f /opt/zextras/log/freshclam.pid ]; then
-    cpid=$(cat /opt/zextras/log/freshclam.pid)
-    kill "$cpid" 2>/dev/null
-  fi
-  pskillall /opt/zextras/common/bin/freshclam
-  exit 0
-  ;;
+  'kill')
+    if [ -f /opt/zextras/log/freshclam.pid ]; then
+      cpid=$(cat /opt/zextras/log/freshclam.pid)
+      kill "$cpid" 2>/dev/null
+    fi
+    pskillall /opt/zextras/common/bin/freshclam
+    exit 0
+    ;;
 
-'stop')
-  checkrunning
-  echo -n "Stopping freshclam..."
-  if [ $frunning = 0 ]; then
-    echo "freshclam is not running."
-  else
-    if [ x"$fpid" != "x" ]; then
-      kill "$fpid" 2>/dev/null
-      if [ $? = 0 ]; then
-        echo "done."
-      else
-        echo "failed."
+  'stop')
+    checkrunning
+    echo -n "Stopping freshclam..."
+    if [ $frunning = 0 ]; then
+      echo "freshclam is not running."
+    else
+      if [ x"$fpid" != "x" ]; then
+        kill "$fpid" 2>/dev/null
+        if [ $? = 0 ]; then
+          echo "done."
+        else
+          echo "failed."
+        fi
       fi
     fi
-  fi
 
-  exit 0
-  ;;
-
-'restart' | 'reload')
-  $0 stop
-  $0 start $2
-  ;;
-
-'status')
-  checkrunning
-  echo -n "freshclam is "
-  if [ $frunning = 1 ]; then
-    echo "running."
     exit 0
-  else
-    echo "not runnning."
-    exit 1
-  fi
-  ;;
+    ;;
 
-*)
-  echo "Usage: $0 start|stop|kill|restart|status"
-  exit 1
-  ;;
+  'restart' | 'reload')
+    $0 stop
+    $0 start $2
+    ;;
+
+  'status')
+    checkrunning
+    echo -n "freshclam is "
+    if [ $frunning = 1 ]; then
+      echo "running."
+      exit 0
+    else
+      echo "not runnning."
+      exit 1
+    fi
+    ;;
+
+  *)
+    echo "Usage: $0 start|stop|kill|restart|status"
+    exit 1
+    ;;
 esac
diff --git a/src/bin/zmmemcachedctl b/src/bin/zmmemcachedctl
--- a/src/bin/zmmemcachedctl
+++ b/src/bin/zmmemcachedctl
@@ -39,94 +39,94 @@ checkrunning() {
 }
 
 case "$1" in
-start)
+  start)
 
-  if [ ! -x /opt/zextras/common/bin/memcached ]; then
-    echo "Error: memcached not installed"
-    exit 1
-  fi
-
-  checkrunning
-  echo -n "Starting ${servicename}..."
-  if [ $running = 1 ]; then
-    echo "${servicename} is already running."
-    exit 0
-  fi
-
-  addr=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindAddress | awk '/^zimbraMemcachedBindAddress:/{ print $2 }')
-  addr="${addr//$'\n'/,}"
-  port=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindPort | awk '/^zimbraMemcachedBindPort:/{ print $2 }')
-  if [ x"$addr" = "x" ]; then
-    /opt/zextras/common/bin/${servicename} -d -P ${pidfile} -U 0 -l 127.0.1.1,127.0.0.1 -p ${port:-11211}
-  else
-    /opt/zextras/common/bin/${servicename} -d -P ${pidfile} -U 0 -l ${addr} -p ${port:-11211}
-  fi
-  for ((i = 0; i < 30; i++)); do
-    checkrunning
-    if [ $running = 1 ]; then
-      break
+    if [ ! -x /opt/zextras/common/bin/memcached ]; then
+      echo "Error: memcached not installed"
+      exit 1
     fi
-    sleep 1
-  done
-  if [ "x$pid" != "x" ]; then
-    echo "done."
-    exit 0
-  else
-    echo "failed."
-    exit 1
-  fi
-  ;;
-stop)
-  checkrunning
-  echo -n "Stopping ${servicename}..."
-  if [ $running = 0 ]; then
-    echo "${servicename} is not running."
-    exit 0
-  else
+
+    checkrunning
+    echo -n "Starting ${servicename}..."
+    if [ $running = 1 ]; then
+      echo "${servicename} is already running."
+      exit 0
+    fi
+
+    addr=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindAddress | awk '/^zimbraMemcachedBindAddress:/{ print $2 }')
+    addr="${addr//$'\n'/,}"
+    port=$(/opt/zextras/bin/zmprov -l gs ${zimbra_server_hostname} zimbraMemcachedBindPort | awk '/^zimbraMemcachedBindPort:/{ print $2 }')
+    if [ x"$addr" = "x" ]; then
+      /opt/zextras/common/bin/${servicename} -d -P ${pidfile} -U 0 -l 127.0.1.1,127.0.0.1 -p ${port:-11211}
+    else
+      /opt/zextras/common/bin/${servicename} -d -P ${pidfile} -U 0 -l ${addr} -p ${port:-11211}
+    fi
     for ((i = 0; i < 30; i++)); do
-      kill -0 $pid 2>/dev/null
-      if [ $? != 0 ]; then
-        rm -rf ${pidfile}
+      checkrunning
+      if [ $running = 1 ]; then
         break
       fi
-      kill $pid
       sleep 1
     done
-  fi
-  if [ -s ${pidfile} ]; then
-    echo "failed."
-    exit 1
-  else
-    echo "done."
-  fi
-  exit 0
-  ;;
-restart)
-  $0 stop
-  $0 start
-  ;;
-reload)
-  checkrunning
-  if [ $running = 1 -a "x$pid" != "x" ]; then
-    echo -n "Reloading ${servicename}..."
-    kill -HUP $pid
-    echo "done."
-  fi
-
-  ;;
-status)
-  echo -n "${servicename} is "
-  checkrunning
-  if [ $running = 0 ]; then
-    echo "not running."
-    exit 1
-  else
-    echo "running."
+    if [ "x$pid" != "x" ]; then
+      echo "done."
+      exit 0
+    else
+      echo "failed."
+      exit 1
+    fi
+    ;;
+  stop)
+    checkrunning
+    echo -n "Stopping ${servicename}..."
+    if [ $running = 0 ]; then
+      echo "${servicename} is not running."
+      exit 0
+    else
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2>/dev/null
+        if [ $? != 0 ]; then
+          rm -rf ${pidfile}
+          break
+        fi
+        kill $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      echo "failed."
+      exit 1
+    else
+      echo "done."
+    fi
     exit 0
-  fi
-  ;;
-*)
-  echo "$0 start|stop|restart|reload|status"
-  exit 1
-  ;;
+    ;;
+  restart)
+    $0 stop
+    $0 start
+    ;;
+  reload)
+    checkrunning
+    if [ $running = 1 -a "x$pid" != "x" ]; then
+      echo -n "Reloading ${servicename}..."
+      kill -HUP $pid
+      echo "done."
+    fi
+
+    ;;
+  status)
+    echo -n "${servicename} is "
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+      exit 0
+    fi
+    ;;
+  *)
+    echo "$0 start|stop|restart|reload|status"
+    exit 1
+    ;;
 esac
diff --git a/src/bin/zmmtactl b/src/bin/zmmtactl
--- a/src/bin/zmmtactl
+++ b/src/bin/zmmtactl
@@ -11,84 +11,84 @@ zmsetvars
 BASE=/opt/zextras
 
 if [ ! -x /opt/zextras/common/sbin/postfix ]; then
-	echo "Error: postfix not installed"
-	exit 1
+  echo "Error: postfix not installed"
+  exit 1
 fi
 
 if [ -f "/opt/zextras/conf/mta_milter_options" ]; then
-	source /opt/zextras/conf/mta_milter_options
+  source /opt/zextras/conf/mta_milter_options
 fi
 zimbraMilterServerEnabled=${zimbraMilterServerEnabled:=FALSE}
 
 if [ x"$zimbraMilterServerEnabled" = "xTRUE" ]; then
-	START_SCRIPTS="zmmilterctl zmsaslauthdctl postfix"
-	STOP_SCRIPTS="postfix zmsaslauthdctl zmmilterctl"
+  START_SCRIPTS="zmmilterctl zmsaslauthdctl postfix"
+  STOP_SCRIPTS="postfix zmsaslauthdctl zmmilterctl"
 else
-	START_SCRIPTS="zmsaslauthdctl postfix"
-	STOP_SCRIPTS="postfix zmsaslauthdctl"
+  START_SCRIPTS="zmsaslauthdctl postfix"
+  STOP_SCRIPTS="postfix zmsaslauthdctl"
 fi
 
 rewriteconfig() {
-	echo -n "Rewriting configuration files..."
-	if [ ! -f /opt/zextras/common/conf/main.cf ]; then
-		touch /opt/zextras/common/conf/main.cf
-		/opt/zextras/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
-	fi
-	/opt/zextras/libexec/configrewrite antispam antivirus opendkim mta sasl >/dev/null 2>&1
-	if [ $? = 0 ]; then
-		echo "done."
-	else
-		echo "failed."
-	fi
+  echo -n "Rewriting configuration files..."
+  if [ ! -f /opt/zextras/common/conf/main.cf ]; then
+    touch /opt/zextras/common/conf/main.cf
+    /opt/zextras/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
+  fi
+  /opt/zextras/libexec/configrewrite antispam antivirus opendkim mta sasl >/dev/null 2>&1
+  if [ $? = 0 ]; then
+    echo "done."
+  else
+    echo "failed."
+  fi
 }
 
 case "$1" in
-start)
-	if [ x$2 = "x" ]; then
-		rewriteconfig
-	fi
-	STATUS=0
-	for i in $START_SCRIPTS; do
-		/opt/zextras/bin/$i start norewrite
-		R=$?
-		if [ $R -ne "0" ]; then
-			echo "$i failed to start"
-			STATUS=$R
-		fi
-	done
-	exit $STATUS
-	;;
-stop)
-	for i in $STOP_SCRIPTS; do
-		/opt/zextras/bin/$i stop
-	done
-	;;
-reload | restart)
-	if [ x$2 = "x" ]; then
-		rewriteconfig
-	fi
-	for i in $START_SCRIPTS; do
-		if [ x$2 = "x" ]; then
-			/opt/zextras/bin/$i reload
-		else
-			/opt/zextras/bin/$i reload $2
-		fi
-	done
-	;;
-status)
-	STATUS=0
-	for i in $START_SCRIPTS; do
-		/opt/zextras/bin/$i status >/dev/null 2>&1
-		R=$?
-		if [ $R -ne "0" ]; then
-			echo "$i is not running"
-			STATUS=$R
-		fi
-	done
-	exit $STATUS
-	;;
-*)
-	echo "$0 start|stop|restart|reload|status"
-	exit 1
-	;;
+  start)
+    if [ x$2 = "x" ]; then
+      rewriteconfig
+    fi
+    STATUS=0
+    for i in $START_SCRIPTS; do
+      /opt/zextras/bin/$i start norewrite
+      R=$?
+      if [ $R -ne "0" ]; then
+        echo "$i failed to start"
+        STATUS=$R
+      fi
+    done
+    exit $STATUS
+    ;;
+  stop)
+    for i in $STOP_SCRIPTS; do
+      /opt/zextras/bin/$i stop
+    done
+    ;;
+  reload | restart)
+    if [ x$2 = "x" ]; then
+      rewriteconfig
+    fi
+    for i in $START_SCRIPTS; do
+      if [ x$2 = "x" ]; then
+        /opt/zextras/bin/$i reload
+      else
+        /opt/zextras/bin/$i reload $2
+      fi
+    done
+    ;;
+  status)
+    STATUS=0
+    for i in $START_SCRIPTS; do
+      /opt/zextras/bin/$i status >/dev/null 2>&1
+      R=$?
+      if [ $R -ne "0" ]; then
+        echo "$i is not running"
+        STATUS=$R
+      fi
+    done
+    exit $STATUS
+    ;;
+  *)
+    echo "$0 start|stop|restart|reload|status"
+    exit 1
+    ;;
 esac
diff --git a/src/bin/zmsaslauthdctl b/src/bin/zmsaslauthdctl
--- a/src/bin/zmsaslauthdctl
+++ b/src/bin/zmsaslauthdctl
@@ -44,73 +44,73 @@ checkrunning() {
 # Main
 #
 case "$1" in
-'start')
-  checkrunning
-  echo -n "Starting saslauthd..."
-  if [ $running = 1 ]; then
-    echo "already running."
-    exit 0
-  fi
-  mkdir -p /opt/zextras/data/sasl2/state
-  if [ x$2 = "x" ]; then
-    rewriteconfig
-  fi
-  /opt/zextras/common/sbin/saslauthd -r -a zimbra
-  for ((i = 0; i < 30; i++)); do
+  'start')
     checkrunning
+    echo -n "Starting saslauthd..."
     if [ $running = 1 ]; then
-      echo "done."
+      echo "already running."
       exit 0
     fi
-    sleep 1
-  done
-  echo "failed."
-  exit 1
-  ;;
-
-'kill' | 'stop')
-  checkrunning
-  if [ $running = 0 ]; then
-    echo "saslauthd is not running."
-    exit 0
-  else
-    echo -n "Stopping saslauthd..."
+    mkdir -p /opt/zextras/data/sasl2/state
+    if [ x$2 = "x" ]; then
+      rewriteconfig
+    fi
+    /opt/zextras/common/sbin/saslauthd -r -a zimbra
     for ((i = 0; i < 30; i++)); do
-      kill -0 $pid 2>/dev/null
-      if [ $? != 0 ]; then
-        rm -rf ${pidfile}
-        break
+      checkrunning
+      if [ $running = 1 ]; then
+        echo "done."
+        exit 0
       fi
-      kill $pid
       sleep 1
     done
-  fi
-  if [ -s ${pidfile} ]; then
+    echo "failed."
     exit 1
-  else
-    echo "done."
-  fi
-  exit 0
-  ;;
+    ;;
 
-'restart' | 'reload')
-  $0 stop
-  $0 start $2
-  ;;
-
-'status')
-  checkrunning
-  if [ $running = 1 ]; then
-    echo "saslauthd is running."
+  'kill' | 'stop')
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "saslauthd is not running."
+      exit 0
+    else
+      echo -n "Stopping saslauthd..."
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2>/dev/null
+        if [ $? != 0 ]; then
+          rm -rf ${pidfile}
+          break
+        fi
+        kill $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      exit 1
+    else
+      echo "done."
+    fi
     exit 0
-  else
-    echo "saslauthd is not running."
-    exit 1
-  fi
-  ;;
+    ;;
 
-*)
-  echo "Usage: $0 start|stop|kill|restart|reload|status"
-  exit 1
-  ;;
+  'restart' | 'reload')
+    $0 stop
+    $0 start $2
+    ;;
+
+  'status')
+    checkrunning
+    if [ $running = 1 ]; then
+      echo "saslauthd is running."
+      exit 0
+    else
+      echo "saslauthd is not running."
+      exit 1
+    fi
+    ;;
+
+  *)
+    echo "Usage: $0 start|stop|kill|restart|reload|status"
+    exit 1
+    ;;
 esac
diff --git a/src/perl/test-zminiutil b/src/perl/test-zminiutil
--- a/src/perl/test-zminiutil
+++ b/src/perl/test-zminiutil
@@ -1,38 +1,56 @@
 #!/bin/bash
-# 
+#
 # SPDX-FileCopyrightText: 2022 Synacor, Inc.
 # SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 #
 # SPDX-License-Identifier: GPL-2.0-only
-# 
+#
 
-ini=/tmp/initest.$$ 
+ini=/tmp/initest.$$
 inix=/tmp/initest-x.$$
 zminiutil=./zminiutil
 
 asf() {
-    echo "==== asf:" $@
-    if $@; then	echo "==== test failed! aborting! ===="; exit 1; fi
+  echo "==== asf:" $@
+  if $@; then
+    echo "==== test failed! aborting! ===="
+    exit 1
+  fi
 }
 
 ast() {
-    echo "==== ast:" $@
-    if ! $@; then echo "==== test failed"; exit 1; fi
+  echo "==== ast:" $@
+  if ! $@; then
+    echo "==== test failed"
+    exit 1
+  fi
 }
 
 ase() {
-    echo "==== ase:" $@; expected=$1; shift; run=$@;
-    actual="$($run)"
-    if [ "x$expected" != "x$actual" ]; then echo "==== test failed"; exit 1; fi
+  echo "==== ase:" $@
+  expected=$1
+  shift
+  run=$@
+  actual="$($run)"
+  if [ "x$expected" != "x$actual" ]; then
+    echo "==== test failed"
+    exit 1
+  fi
 }
-      
+
 ast ${zminiutil} --help
 asf ${zminiutil}
 asf ${zminiutil} --set
 asf ${zminiutil} --set --get
 
-(echo '[xxx]'; echo 'aaa=10'; echo '[yyy]'; echo 'bbb=20'; \
-echo '[zzz]'; echo 'ccc=30' ) > ${ini}
+(
+  echo '[xxx]'
+  echo 'aaa=10'
+  echo '[yyy]'
+  echo 'bbb=20'
+  echo '[zzz]'
+  echo 'ccc=30'
+) >${ini}
 
 ast ${zminiutil} --list ${ini}
 #ast ${zminiutil} --debug --list my.1 ${ini}
@@ -56,25 +74,31 @@ ase "30" ${zminiutil} --get --section zzz --key ccc ${ini}
 
 # test for new key, empty value
 for section in xxx yyy zzz; do
-ast ${zminiutil} --set --section $section --key foo ${ini} > ${inix}
-echo --------------------; cat ${inix}; echo --------------------
-ast ${zminiutil} --list ${inix}
-ast ${zminiutil} --isset --section $section --key foo ${inix}
-ase "" ${zminiutil} --get --section $section  --key foo ${inix}
+  ast ${zminiutil} --set --section $section --key foo ${ini} >${inix}
+  echo --------------------
+  cat ${inix}
+  echo --------------------
+  ast ${zminiutil} --list ${inix}
+  ast ${zminiutil} --isset --section $section --key foo ${inix}
+  ase "" ${zminiutil} --get --section $section --key foo ${inix}
 done
 
 # test for new key, some value
 for section in xxx yyy zzz; do
-ast ${zminiutil} --set --section $section --key foo ${ini} --value 12345 > ${inix}
-echo --------------------; cat ${inix}; echo --------------------
-ast ${zminiutil} --list ${inix}
-ast ${zminiutil} --isset --section $section --key foo ${inix}
-ase "12345" ${zminiutil} --get --section $section  --key foo ${inix}
+  ast ${zminiutil} --set --section $section --key foo ${ini} --value 12345 >${inix}
+  echo --------------------
+  cat ${inix}
+  echo --------------------
+  ast ${zminiutil} --list ${inix}
+  ast ${zminiutil} --isset --section $section --key foo ${inix}
+  ase "12345" ${zminiutil} --get --section $section --key foo ${inix}
 done
 
 # modify existing key
-ast ${zminiutil} --set --section xxx --key aaa ${ini} --value 56789 > ${inix}
-echo --------------------; cat ${inix}; echo --------------------
+ast ${zminiutil} --set --section xxx --key aaa ${ini} --value 56789 >${inix}
+echo --------------------
+cat ${inix}
+echo --------------------
 ast ${zminiutil} --list ${inix}
 ast ${zminiutil} --isset --section xxx --key aaa ${inix}
 ase "56789" ${zminiutil} --get --section xxx --key aaa ${inix}
