chore: milterctl: enhance start/stop of service

diff --git a/src/bin/zmmilterctl b/src/bin/zmmilterctl
--- a/src/bin/zmmilterctl
+++ b/src/bin/zmmilterctl
@@ -65,21 +65,18 @@ case "$1" in
       echo "milter server is not running."
       exit 0
     else
-      for ((i = 0; i < 30; i++)); do
-        kill "$pid" 2>/dev/null
-        rc=$?
-        if [ $rc -eq 0 ]; then
-          break
-        fi
+      kill "$pid" 2>/dev/null
+      rc=$?
+      while [ $running = 1 ]; do
+        checkrunning
         sleep 1
       done
-    fi
-    checkrunning
-    if [[ "${pid}" != "" ]]; then
-      echo "failed."
-      exit 1
-    else
-      echo "done."
+      if [ "$rc" -ne 0 ]; then
+        echo "failed."
+        exit 1
+      else
+        echo "done."
+      fi
     fi
     exit 0
     ;;
