chore: shellcheck: general cleanup

diff --git a/src/bin/zmshutil b/src/bin/zmshutil
--- a/src/bin/zmshutil
+++ b/src/bin/zmshutil
@@ -1,3 +1,4 @@
+#!/bin/bash
 # SPDX-FileCopyrightText: 2022 Synacor, Inc.
 # SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 #
@@ -36,7 +37,7 @@ zmassert() {
   if [ "$@" ]; then
     return
   fi
-  echo Error: assertion "'$@'" failed && exit 1
+  echo "Error: assertion" "$@" "failed" && exit 1
 }
 
 #
diff --git a/src/libexec/zmclientcertmgr b/src/libexec/zmclientcertmgr
--- a/src/libexec/zmclientcertmgr
+++ b/src/libexec/zmclientcertmgr
@@ -14,18 +14,14 @@ umask 027
 source /opt/zextras/bin/zmshutil || exit 1
 zmsetvars -f
 
-exp_thres_days=${zimbra_zmcertmgr_expiration_threshold:=30}
-exp_thres_secs=$((exp_thres_days * 24 * 60 * 60))
-
-zimbra_domain_cert_directory=/opt/zextras/conf/domaincerts
-
 ERROR_PREFIX="ERROR:"
 
 saveConfigKey() {
   local key=$1
   local file=$2
   local location=$3
-  local content=$(cat "$file")
+  local content
+  content=$(cat "$file")
   if [ "$location" = "global" ]; then
     local zmprov_opts="mcf"
   elif [ "$location" = "server" ]; then
@@ -39,8 +35,8 @@ saveConfigKey() {
   fi
 
   echo -n "** Saving $location config key $key..."
-  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "$key" "$content" 2>/dev/null
-  if [ "$?" = 0 ]; then
+
+  if /opt/zextras/bin/zmprov -m -l "${zmprov_opts}" "$key" "$content" 2>/dev/null; then
     echo "done."
   else
     echo "failed."
@@ -63,8 +59,9 @@ cleanConfigKey() {
   fi
 
   echo -n "** Clean $location config key $key..."
-  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "$key" "" 2>/dev/null
-  if [ "$?" = 0 ]; then
+  /opt/zextras/bin/zmprov -m -l "${zmprov_opts}" "$key" "" 2>/dev/null
+  rc=$?
+  if [ $rc -eq 0 ]; then
     echo "done."
   else
     echo "failed."
@@ -91,14 +88,16 @@ loadConfigKey() {
     return
   fi
   TMPDIR="${zimbra_tmp_directory}"
-  local tmpfile=$(mktemp -t zmcertmgr.XXXXXX 2>/dev/null) || {
+  local tmpfile
+  tmpfile=$(mktemp -t zmcertmgr.XXXXXX 2>/dev/null) || {
     echo "Failed to create tmpfile"
     exit 1
   }
   if [ ! -s "$file" ]; then
     echo -n "** Retrieving $location config key $key..."
-    /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "${key}" | sed -e 's/^${key}: //' >"$tmpfile" 2>/dev/null && mv -f "$tmpfile" "$file" 2>/dev/null
-    if [ $? = 0 ] && [ -s "$file" ]; then
+    /opt/zextras/bin/zmprov -m -l "${zmprov_opts}" "${key}" | sed -e "s/^${key}: //" >"$tmpfile" 2>/dev/null && mv -f "$tmpfile" "$file" 2>/dev/null
+    rc=$?
+    if [ "$rc" -eq 0 ] && [ -s "$file" ]; then
       chmod 400 "$file" 2>/dev/null
       echo "done."
     else
@@ -115,16 +114,14 @@ deployCerts() {
     fi
   fi
 
-  DOMAINS=$(/opt/zextras/bin/zmprov -m -l garpd | awk '{print $1}')
-  if [ $? != 0 ]; then
+  DOMAINS=$(/opt/zextras/bin/zmprov -m -l garpd | awk '{print $1}') || {
     echo "Unable to retrieve list of domains with SSL certificates"
     exit 1
-  fi
+  }
 
   for i in ${DOMAINS}; do
     echo -n "** Deploying cert for $i..."
-    getClientCertFromLdap "$i" >/dev/null 2>&1
-    if [ $? = 0 ]; then
+    if getClientCertFromLdap "$i" >/dev/null 2>&1; then
       echo "done."
     else
       echo "failed."
@@ -227,7 +224,7 @@ else
   for arg in "$ACTION" "$@"; do
     [[ "$arg" =~ ^-?-h ]] && usage 0
   done
-  echo "$ERROR_PREFIX unknown argument(s): $ACTION $@"
+  echo "$ERROR_PREFIX unknown argument(s): $ACTION" "$@"
   usage
 fi
 
diff --git a/src/libexec/zmstat-cleanup b/src/libexec/zmstat-cleanup
--- a/src/libexec/zmstat-cleanup
+++ b/src/libexec/zmstat-cleanup
@@ -43,28 +43,29 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-cd /opt/zextras/zmstat 2>/dev/null
-if [ $? -ne 0 ] || [ "${PWD}" != "/opt/zextras/zmstat" ]; then
-  echo "ERROR: Cannot change to the zmstats log directory /opt/zextras/zmstat."
-  exit -1
+cd /opt/zextras/zmstat || return 1
+rc=$?
+if [ $rc -ne 0 ] || [ "${PWD}" != "$zmstat_dir" ]; then
+  echo "ERROR: Cannot change to the zmstats log directory $zmstat_dir."
+  exit 1
 fi
 
-if [ "${listArchives}x" == "TRUEx" ]; then
-  if [ "$(ls -1A | egrep '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | wc -l)" -gt 0 ]; then
-    /bin/ls -d1 [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
+if [ "${listArchives}" == "TRUE" ]; then
+  if [ "$(find . -maxdepth 1 -type d -name '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' | wc -l)" -gt 0 ]; then
+    find . -maxdepth 1 -type d -name '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
   fi
-elif [ "${purgeAll}x" == "TRUEx" ]; then
-  DIR_LIST=$(find . -type d -print | egrep '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "s%./%%")
+elif [ "${purgeAll}" == "TRUE" ]; then
+  DIR_LIST=$(find . -type d -print | grep -E '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "s%./%%")
   for d in ${DIR_LIST}; do
     echo "Deleting ${d} zmstat archive."
-    /bin/rm -rf "${d}"
+    rm -rf "${d}"
   done
 elif [ "${zmstat_max_retention:-"0"}" -gt 0 ]; then
-  DIR_LIST=$(find . -type d -print | egrep '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "1,${zmstat_max_retention}d ; s%./%%")
+  DIR_LIST=$(find . -type d -print | grep -E '^\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' | sort -r | sed -e "1,${zmstat_max_retention}d ; s%./%%")
 
   for d in ${DIR_LIST}; do
     echo "Deleting ${d} zmstat archive."
-    /bin/rm -rf "${d}"
+    rm -rf "${d}"
   done
 else
   echo "WARNING: zmstat_max_retention is set to 0 or is undefined.  No zmstat data has been pruned."
