chore: format using shfmt

diff --git a/src/libexec/ldapmoduleconfupdate b/src/libexec/ldapmoduleconfupdate
--- a/src/libexec/ldapmoduleconfupdate
+++ b/src/libexec/ldapmoduleconfupdate
@@ -12,31 +12,31 @@ BACKUP_DIR="/opt/zextras/data/ldap-post-install-backup/"
 BACKUP_MODULE_CONF_FILE="$BACKUP_DIR/cn=module{0}.ldif.bak"
 
 backup_module_config() {
-    echo "* Creating backup of module config file at $BACKUP_MODULE_CONF_FILE"
-    su - zextras -c "mkdir -p $BACKUP_DIR"
-    cp "$TARGET_MODULE_CONF_FILE" "$BACKUP_MODULE_CONF_FILE"
+  echo "* Creating backup of module config file at $BACKUP_MODULE_CONF_FILE"
+  su - zextras -c "mkdir -p $BACKUP_DIR"
+  cp "$TARGET_MODULE_CONF_FILE" "$BACKUP_MODULE_CONF_FILE"
 }
 
 update_module_config() {
-    echo "* Updating module config $TARGET_MODULE_CONF_FILE"
-    cp "$SOURCE_MODULE_CONF_FILE" "$TARGET_MODULE_CONF_FILE"
+  echo "* Updating module config $TARGET_MODULE_CONF_FILE"
+  cp "$SOURCE_MODULE_CONF_FILE" "$TARGET_MODULE_CONF_FILE"
 }
 
 main() {
-    if [ ! -f "$TARGET_MODULE_CONF_FILE" ]; then
-        echo "Error: Target module config file $TARGET_MODULE_CONF_FILE does not exist."
-        exit 1
-    fi
+  if [ ! -f "$TARGET_MODULE_CONF_FILE" ]; then
+    echo "Error: Target module config file $TARGET_MODULE_CONF_FILE does not exist."
+    exit 1
+  fi
 
-    if [ ! -f "$SOURCE_MODULE_CONF_FILE" ]; then
-        echo "Error: Source module config file $SOURCE_MODULE_CONF_FILE does not exist."
-        exit 1
-    fi
+  if [ ! -f "$SOURCE_MODULE_CONF_FILE" ]; then
+    echo "Error: Source module config file $SOURCE_MODULE_CONF_FILE does not exist."
+    exit 1
+  fi
 
-    if ! diff "$TARGET_MODULE_CONF_FILE" "$SOURCE_MODULE_CONF_FILE" > /dev/null; then
-        backup_module_config
-        update_module_config
-    fi
+  if ! diff "$TARGET_MODULE_CONF_FILE" "$SOURCE_MODULE_CONF_FILE" >/dev/null; then
+    backup_module_config
+    update_module_config
+  fi
 }
 
 main
