chore: shellcheck: general cleanup

diff --git a/src/libexec/zmdomaincertmgr b/src/libexec/zmdomaincertmgr
--- a/src/libexec/zmdomaincertmgr
+++ b/src/libexec/zmdomaincertmgr
@@ -40,11 +40,6 @@ else
   CACERTS=${zimbra_java_home}/jre/lib/security/cacerts
 fi
 
-isLdapRunning() {
-  /opt/zextras/bin/ldap status >/dev/null 2>&1
-  LDAP_IS_RUNNING=$?
-}
-
 saveConfigKey() {
   local key=$1
   local file=$2
@@ -64,8 +59,9 @@ saveConfigKey() {
   fi
 
   echo -n "** Saving $location config key $key..."
-  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "${key}" "$content" 2>/dev/null
-  if [ "$?" = 0 ]; then
+  /opt/zextras/bin/zmprov -m -l "${zmprov_opts}" "${key}" "$content" 2>/dev/null
+  rc=$?
+  if [ $rc -eq 0 ]; then
     echo "done."
   else
     echo "failed."
@@ -101,8 +97,9 @@ loadConfigKey() {
     cp -a "${file}" "${file}.$(date +%Y%m%d)"
   fi
   echo -n "** Retrieving $location config key $key..."
-  /opt/zextras/bin/zmprov -m -l ${zmprov_opts} "${key}" | sed -e "s/^${key}: //" >"${tmpfile}" 2>/dev/null
-  if [ "$?" = 0 ] && [ -s "${tmpfile}" ]; then
+  /opt/zextras/bin/zmprov -m -l "${zmprov_opts}" "${key}" | sed -e "s/^${key}: //" >"${tmpfile}" 2>/dev/null
+  rc=$?
+  if [ $rc -eq 0 ] && [ -s "${tmpfile}" ]; then
     chmod 400 "${tmpfile}"
     mv -f "${tmpfile}" "${file}"
     echo "done."
@@ -118,8 +115,9 @@ deployCerts() {
   fi
 
   DOMAINS=$(/opt/zextras/bin/zmprov -m -l garpd | awk '{print $1}')
-  if [ $? != 0 ]; then
-    echo "$ERROR_PREFIX zmprov -m -l getAllReverseProxyDomains failed (rc=$?)."
+  rc=$?
+  if [ $rc != 0 ]; then
+    echo "$ERROR_PREFIX zmprov -m -l getAllReverseProxyDomains failed (rc=$rc)."
     exit 1
   fi
 
@@ -132,7 +130,8 @@ deployCerts() {
   for i in $DOMAINS; do
     echo -n "** Deploying cert for ${i}..."
     getDomainCertFromLdap "$i" >/dev/null 2>&1
-    if [ $? = 0 ]; then
+    rc=$?
+    if [ $rc -eq 0 ]; then
       echo "done."
     else
       echo "failed."
@@ -252,7 +251,8 @@ checkCertExpiration() {
     #echo "::service mta::"
     if [ -f "${service_crt}" ]; then
       ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
-      if [ $? != 0 ]; then
+      rc=$?
+      if [ "$rc" -ne 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
         ${openssl} x509 -in ${service_crt} -enddate -noout
@@ -262,12 +262,13 @@ checkCertExpiration() {
     fi
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "proxy" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "proxy" ]; then
     service_crt=/opt/zextras/conf/nginx.crt
     #echo "::service proxy::"
     if [ -f "${service_crt}" ]; then
       ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
-      if [ $? != 0 ]; then
+      rc=$?
+      if [ $rc != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
         ${openssl} x509 -in ${service_crt} -enddate -noout
@@ -277,7 +278,7 @@ checkCertExpiration() {
     fi
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "mailboxd" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "mailboxd" ]; then
     service_der=/opt/zextras/mailboxd/etc/mailboxd.der
     service_crt=/opt/zextras/mailboxd/etc/mailboxd.pem
     #echo "::service mailboxd::"
@@ -287,17 +288,19 @@ checkCertExpiration() {
     }
     ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
       -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} >${tmpfile} 2>&1
-    if [ $? != 0 ]; then
+    rc=$?
+    if [ $rc != 0 ]; then
       echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
       echo
       cat $tmpfile
       echo
     fi
-    rm -f $tmpfile 2>/dev/null
+    rm -f "$tmpfile" 2>/dev/null
     if [ -f "${service_der}" ]; then
       ${openssl} x509 -inform DER -outform PEM -in ${service_der} -out ${service_crt}
       ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
-      if [ $? != 0 ]; then
+      rc=$?
+      if [ $rc != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
         ${openssl} x509 -in ${service_crt} -enddate -noout
@@ -307,12 +310,13 @@ checkCertExpiration() {
     fi
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "ldap" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "ldap" ]; then
     service_crt=/opt/zextras/conf/slapd.crt
     #echo "::service ldap::"
     if [ -f "${service_crt}" ]; then
       ${openssl} x509 -in ${service_crt} -noout -checkend ${exp_thres_secs}
-      if [ $? != 0 ]; then
+      rc=$?
+      if [ $rc != 0 ]; then
         status=1
         echo "${service_crt} is expiring within ${exp_thres_days} days."
         ${openssl} x509 -in ${service_crt} -enddate -noout
@@ -322,7 +326,7 @@ checkCertExpiration() {
     fi
   fi
 
-  exit $status
+  exit "$status"
 }
 
 viewdeployedcrt() {
@@ -335,18 +339,18 @@ viewdeployedcrt() {
     return
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "mta" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "mta" ]; then
     service_crt=/opt/zextras/conf/smtpd.crt
     echo "::service mta::"
     if [ -f "${service_crt}" ]; then
       ${openssl} x509 -in ${service_crt} -dates -subject -issuer -noout
-      getsubjectaltnames $service_crt crt
+      getsubjectaltnames "$service_crt" crt
     else
       echo "${ERROR_PREFIX} ${service_crt} does not exist"
     fi
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "proxy" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "proxy" ]; then
     service_crt=/opt/zextras/conf/nginx.crt
     echo "::service proxy::"
     if [ -f "${service_crt}" ]; then
@@ -357,7 +361,7 @@ viewdeployedcrt() {
     fi
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "mailboxd" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "mailboxd" ]; then
     service_der=/opt/zextras/mailboxd/etc/mailboxd.der
     service_crt=/opt/zextras/mailboxd/etc/mailboxd.pem
     echo "::service mailboxd::"
@@ -367,13 +371,14 @@ viewdeployedcrt() {
     }
     ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
       -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} >${tmpfile} 2>&1
-    if [ $? != 0 ]; then
+    rc=$?
+    if [ $rc != 0 ]; then
       echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
       echo
-      cat $tmpfile
+      cat "$tmpfile"
       echo
     fi
-    rm -f $tmpfile 2>/dev/null
+    rm -f "$tmpfile" 2>/dev/null
     if [ -f "${service_der}" ]; then
       ${openssl} x509 -inform DER -outform PEM -in ${service_der} -out ${service_crt}
       ${openssl} x509 -in ${service_crt} -dates -subject -issuer -noout
@@ -383,7 +388,7 @@ viewdeployedcrt() {
     fi
   fi
 
-  if [ $VIEW = "all" ] || [ $VIEW = "ldap" ]; then
+  if [ "$VIEW" = "all" ] || [ "$VIEW" = "ldap" ]; then
     service_crt=/opt/zextras/conf/slapd.crt
     echo "::service ldap::"
     if [ -f "${service_crt}" ]; then
